exports.ephesians =
  { 1:  { 1:  [ {class: "vs", text: "Paul, an apostle of Christ Jesus through the will of God, to the saints who are at Ephesus, and the faithful in Christ Jesus:"} ]
        , 2:  [ {class: "vs", text: "Grace to you and peace from God our Father and the Lord Jesus Christ."} ]
        , 3:  [ {class: "vs", text: "Blessed be the God and Father of our Lord Jesus Christ, who has blessed us with every spiritual blessing in the heavenly places in Christ,"} ]
        , 4:  [ {class: "vs", text: "even as he chose us in him before the foundation of the world, that we would be holy and without defect before him in love,"} ]
        , 5:  [ {class: "vs", text: "having predestined us for adoption as children through Jesus Christ to himself, according to the good pleasure of his desire,"} ]
        , 6:  [ {class: "vs", text: "to the praise of the glory of his grace, by which he freely gave us favor in the Beloved,"} ]
        , 7:  [ {class: "vs", text: "in whom we have our redemption through his blood, the forgiveness of our trespasses, according to the riches of his grace,"} ]
        , 8:  [ {class: "vs", text: "which he made to abound toward us in all wisdom and prudence,"} ]
        , 9:  [ {class: "vs", text: "making known to us the mystery of his will, according to his good pleasure which he purposed in him"} ]
        , 10: [ {class: "vs", text: "to an administration of the fullness of the times, to sum up all things in Christ, the things in the heavens and the things on the earth, in him."} ]
        , 11: [ {class: "vs", text: "We were also assigned an inheritance in him, having been foreordained according to the purpose of him who does all things after the counsel of his will,"} ]
        , 12: [ {class: "vs", text: "to the end that we should be to the praise of his glory, we who had before hoped in Christ."} ]
        , 13: [ {class: "vs", text: "In him you also, having heard the word of the truth, the Good News of your salvation—in whom, having also believed, you were sealed with the promised Holy Spirit,"} ]
        , 14: [ {class: "vs", text: "who is a pledge of our inheritance, to the redemption of God’s own possession, to the praise of his glory."} ]
        , 15: [ {class: "vs", text: "For this cause I also, having heard of the faith in the Lord Jesus which is among you, and the love which you have toward all the saints,"} ]
        , 16: [ {class: "vs", text: "don’t cease to give thanks for you, making mention of you in my prayers,"} ]
        , 17: [ {class: "vs", text: "that the God of our Lord Jesus Christ, the Father of glory, may give to you a spirit of wisdom and revelation in the knowledge of him,"} ]
        , 18: [ {class: "vs", text: "having the eyes of your hearts enlightened, that you may know what is the hope of his calling, and what are the riches of the glory of his inheritance in the saints,"} ]
        , 19: [ {class: "vs", text: "and what is the exceeding greatness of his power toward us who believe, according to that working of the strength of his might"} ]
        , 20: [ {class: "vs", text: "which he worked in Christ, when he raised him from the dead and made him to sit at his right hand in the heavenly places,"} ]
        , 21: [ {class: "vs", text: "far above all rule, authority, power, dominion, and every name that is named, not only in this age, but also in that which is to come."} ]
        , 22: [ {class: "vs", text: "He put all things in subjection under his feet, and gave him to be head over all things for the assembly,"} ]
        , 23: [ {class: "vs", text: "which is his body, the fullness of him who fills all in all."} ]
        }
  , 2:  { 1:  [ {class: "vs", text: "You were made alive when you were dead in transgressions and sins,"} ]
        , 2:  [ {class: "vs", text: "in which you once walked according to the course of this world, according to the prince of the power of the air, the spirit who now works in the children of disobedience."} ]
        , 3:  [ {class: "vs", text: "We also all once lived among them in the lusts of our flesh, doing the desires of the flesh and of the mind, and were by nature children of wrath, even as the rest."} ]
        , 4:  [ {class: "vs", text: "But God, being rich in mercy, for his great love with which he loved us,"} ]
        , 5:  [ {class: "vs", text: "even when we were dead through our trespasses, made us alive together with Christ—by grace you have been saved—"} ]
        , 6:  [ {class: "vs", text: "and raised us up with him, and made us to sit with him in the heavenly places in Christ Jesus,"} ]
        , 7:  [ {class: "vs", text: "that in the ages to come he might show the exceeding riches of his grace in kindness toward us in Christ Jesus;"} ]
        , 8:  [ {class: "vs", text: "for by grace you have been saved through faith, and that not of yourselves; it is the gift of God,"} ]
        , 9:  [ {class: "vs", text: "not of works, that no one would boast."} ]
        , 10: [ {class: "vs", text: "For we are his workmanship, created in Christ Jesus for good works, which God prepared before that we would walk in them."} ]
        , 11: [ {class: "vs", text: "Therefore remember that once you, the Gentiles in the flesh, who are called “uncircumcision” by that which is called “circumcision” (in the flesh, made by hands),"} ]
        , 12: [ {class: "vs", text: "that you were at that time separate from Christ, alienated from the commonwealth of Israel, and strangers from the covenants of the promise, having no hope and without God in the world."} ]
        , 13: [ {class: "vs", text: "But now in Christ Jesus you who once were far off are made near in the blood of Christ."} ]
        , 14: [ {class: "vs", text: "For he is our peace, who made both one, and broke down the middle wall of separation,"} ]
        , 15: [ {class: "vs", text: "having abolished in his flesh the hostility, the law of commandments contained in ordinances, that he might create in himself one new man of the two, making peace,"} ]
        , 16: [ {class: "vs", text: "and might reconcile them both in one body to God through the cross, having killed the hostility through it."} ]
        , 17: [ {class: "vs", text: "He came and preached peace to you who were far off and to those who were near."} ]
        , 18: [ {class: "vs", text: "For through him we both have our access in one Spirit to the Father."} ]
        , 19: [ {class: "vs", text: "So then you are no longer strangers and foreigners, but you are fellow citizens with the saints and of the household of God,"} ]
        , 20: [ {class: "vs", text: "being built on the foundation of the apostles and prophets, Christ Jesus himself being the chief cornerstone;"} ]
        , 21: [ {class: "vs", text: "in whom the whole building, fitted together, grows into a holy temple in the Lord;"} ]
        , 22: [ {class: "vs", text: "in whom you also are built together for a habitation of God in the Spirit."} ]
        }
  , 3:  { 1:  [ {class: "vs", text: "For this cause I, Paul, am the prisoner of Christ Jesus on behalf of you Gentiles,"} ]
        , 2:  [ {class: "vs", text: "if it is so that you have heard of the administration of that grace of God which was given me toward you,"} ]
        , 3:  [ {class: "vs", text: "how that by revelation the mystery was made known to me, as I wrote before in few words,"} ]
        , 4:  [ {class: "vs", text: "by which, when you read, you can perceive my understanding in the mystery of Christ,"} ]
        , 5:  [ {class: "vs", text: "which in other generations was not made known to the children of men, as it has now been revealed to his holy apostles and prophets in the Spirit,"} ]
        , 6:  [ {class: "vs", text: "that the Gentiles are fellow heirs and fellow members of the body, and fellow partakers of his promise in Christ Jesus through the Good News,"} ]
        , 7:  [ {class: "vs", text: "of which I was made a servant according to the gift of that grace of God which was given me according to the working of his power."} ]
        , 8:  [ {class: "vs", text: "To me, the very least of all saints, was this grace given, to preach to the Gentiles the unsearchable riches of Christ,"} ]
        , 9:  [ {class: "vs", text: "and to make all men see what is the administration of the mystery which for ages has been hidden in God, who created all things through Jesus Christ,"} ]
        , 10: [ {class: "vs", text: "to the intent that now through the assembly the manifold wisdom of God might be made known to the principalities and the powers in the heavenly places,"} ]
        , 11: [ {class: "vs", text: "according to the eternal purpose which he accomplished in Christ Jesus our Lord."} ]
        , 12: [ {class: "vs", text: "In him we have boldness and access in confidence through our faith in him."} ]
        , 13: [ {class: "vs", text: "Therefore I ask that you may not lose heart at my troubles for you, which are your glory."} ]
        , 14: [ {class: "vs", text: "For this cause, I bow my knees to the Father of our Lord Jesus Christ,"} ]
        , 15: [ {class: "vs", text: "from whom every family in heaven and on earth is named,"} ]
        , 16: [ {class: "vs", text: "that he would grant you, according to the riches of his glory, that you may be strengthened with power through his Spirit in the inner person,"} ]
        , 17: [ {class: "vs", text: "that Christ may dwell in your hearts through faith, to the end that you, being rooted and grounded in love,"} ]
        , 18: [ {class: "vs", text: "may be strengthened to comprehend with all the saints what is the width and length and height and depth,"} ]
        , 19: [ {class: "vs", text: "and to know Christ’s love which surpasses knowledge, that you may be filled with all the fullness of God."} ]
        , 20: [ {class: "vs", text: "Now to him who is able to do exceedingly abundantly above all that we ask or think, according to the power that works in us,"} ]
        , 21: [ {class: "vs", text: "to him be the glory in the assembly and in Christ Jesus to all generations forever and ever. Amen."} ]
        }
  , 4:  { 1:  [ {class: "vs", text: "I therefore, the prisoner in the Lord, beg you to walk worthily of the calling with which you were called,"} ]
        , 2:  [ {class: "vs", text: "with all lowliness and humility, with patience, bearing with one another in love,"} ]
        , 3:  [ {class: "vs", text: "being eager to keep the unity of the Spirit in the bond of peace."} ]
        , 4:  [ {class: "vs", text: "There is one body and one Spirit, even as you also were called in one hope of your calling,"} ]
        , 5:  [ {class: "vs", text: "one Lord, one faith, one baptism,"} ]
        , 6:  [ {class: "vs", text: "one God and Father of all, who is over all and through all, and in us all."} ]
        , 7:  [ {class: "vs", text: "But to each one of us, the grace was given according to the measure of the gift of Christ."} ]
        , 8:  [ {class: "endpara", text: "Therefore he says,"}
              , {class: "q", text: "“When he ascended on high,"}
              , {class: "q2", text: "he led captivity captive,"}
              , {class: "q2", text: "and gave gifts to people.”"}
              ]
        , 9:  [ {class: "vs", text: "Now this, “He ascended”, what is it but that he also first descended into the lower parts of the earth?"} ]
        , 10: [ {class: "vs", text: "He who descended is the one who also ascended far above all the heavens, that he might fill all things."} ]
        , 11: [ {class: "vs", text: "He gave some to be apostles; and some, prophets; and some, evangelists; and some, shepherds and teachers;"} ]
        , 12: [ {class: "vs", text: "for the perfecting of the saints, to the work of serving, to the building up of the body of Christ,"} ]
        , 13: [ {class: "vs", text: "until we all attain to the unity of the faith and of the knowledge of the Son of God, to a full grown man, to the measure of the stature of the fullness of Christ,"} ]
        , 14: [ {class: "vs", text: "that we may no longer be children, tossed back and forth and carried about with every wind of doctrine, by the trickery of men, in craftiness, after the wiles of error;"} ]
        , 15: [ {class: "vs", text: "but speaking truth in love, we may grow up in all things into him who is the head, Christ,"} ]
        , 16: [ {class: "vs", text: "from whom all the body, being fitted and knit together through that which every joint supplies, according to the working in measure of each individual part, makes the body increase to the building up of itself in love."} ]
        , 17: [ {class: "vs", text: "This I say therefore, and testify in the Lord, that you no longer walk as the rest of the Gentiles also walk, in the futility of their mind,"} ]
        , 18: [ {class: "vs", text: "being darkened in their understanding, alienated from the life of God because of the ignorance that is in them, because of the hardening of their hearts."} ]
        , 19: [ {class: "vs", text: "They, having become callous, gave themselves up to lust, to work all uncleanness with greediness."} ]
        , 20: [ {class: "vs", text: "But you didn’t learn Christ that way,"} ]
        , 21: [ {class: "vs", text: "if indeed you heard him, and were taught in him, even as truth is in Jesus:"} ]
        , 22: [ {class: "vs", text: "that you put away, as concerning your former way of life, the old man that grows corrupt after the lusts of deceit,"} ]
        , 23: [ {class: "vs", text: "and that you be renewed in the spirit of your mind,"} ]
        , 24: [ {class: "vs", text: "and put on the new man, who in the likeness of God has been created in righteousness and holiness of truth."} ]
        , 25: [ {class: "vs", text: "Therefore putting away falsehood, speak truth each one with his neighbor. For we are members of one another."} ]
        , 26: [ {class: "vs", text: "“Be angry, and don’t sin.” Don’t let the sun go down on your wrath,"} ]
        , 27: [ {class: "vs", text: "and don’t give place to the devil."} ]
        , 28: [ {class: "vs", text: "Let him who stole steal no more; but rather let him labor, producing with his hands something that is good, that he may have something to give to him who has need."} ]
        , 29: [ {class: "vs", text: "Let no corrupt speech proceed out of your mouth, but only what is good for building others up as the need may be, that it may give grace to those who hear."} ]
        , 30: [ {class: "vs", text: "Don’t grieve the Holy Spirit of God, in whom you were sealed for the day of redemption."} ]
        , 31: [ {class: "vs", text: "Let all bitterness, wrath, anger, outcry, and slander be put away from you, with all malice."} ]
        , 32: [ {class: "vs", text: "And be kind to one another, tender hearted, forgiving each other, just as God also in Christ forgave you."} ]
        }
  , 5:  { 1:  [ {class: "vs", text: "Be therefore imitators of God, as beloved children."} ]
        , 2:  [ {class: "vs", text: "Walk in love, even as Christ also loved us and gave himself up for us, an offering and a sacrifice to God for a sweet-smelling fragrance."} ]
        , 3:  [ {class: "vs", text: "But sexual immorality, and all uncleanness or covetousness, let it not even be mentioned among you, as becomes saints;"} ]
        , 4:  [ {class: "vs", text: "nor filthiness, nor foolish talking, nor jesting, which are not appropriate, but rather giving of thanks."} ]
        , 5:  [ {class: "vs", text: "Know this for sure, that no sexually immoral person, nor unclean person, nor covetous man, who is an idolater, has any inheritance in the Kingdom of Christ and God."} ]
        , 6:  [ {class: "vs", text: "Let no one deceive you with empty words. For because of these things, the wrath of God comes on the children of disobedience."} ]
        , 7:  [ {class: "vs", text: "Therefore don’t be partakers with them."} ]
        , 8:  [ {class: "vs", text: "For you were once darkness, but are now light in the Lord. Walk as children of light,"} ]
        , 9:  [ {class: "vs", text: "for the fruit of the Spirit is in all goodness and righteousness and truth,"} ]
        , 10: [ {class: "vs", text: "proving what is well pleasing to the Lord."} ]
        , 11: [ {class: "vs", text: "Have no fellowship with the unfruitful deeds of darkness, but rather even reprove them."} ]
        , 12: [ {class: "vs", text: "For it is a shame even to speak of the things which are done by them in secret."} ]
        , 13: [ {class: "vs", text: "But all things, when they are reproved, are revealed by the light, for everything that reveals is light."} ]
        , 14: [ {class: "vs", text: "Therefore he says, “Awake, you who sleep, and arise from the dead, and Christ will shine on you.”"} ]
        , 15: [ {class: "vs", text: "Therefore watch carefully how you walk, not as unwise, but as wise,"} ]
        , 16: [ {class: "vs", text: "redeeming the time, because the days are evil."} ]
        , 17: [ {class: "vs", text: "Therefore don’t be foolish, but understand what the will of the Lord is."} ]
        , 18: [ {class: "vs", text: "Don’t be drunken with wine, in which is dissipation, but be filled with the Spirit,"} ]
        , 19: [ {class: "vs", text: "speaking to one another in psalms, hymns, and spiritual songs; singing and making melody in your heart to the Lord;"} ]
        , 20: [ {class: "vs", text: "giving thanks always concerning all things in the name of our Lord Jesus Christ, to God, even the Father;"} ]
        , 21: [ {class: "vs", text: "subjecting yourselves to one another in the fear of Christ."} ]
        , 22: [ {class: "vs", text: "Wives, be subject to your own husbands, as to the Lord."} ]
        , 23: [ {class: "vs", text: "For the husband is the head of the wife, as Christ also is the head of the assembly, being himself the savior of the body."} ]
        , 24: [ {class: "vs", text: "But as the assembly is subject to Christ, so let the wives also be to their own husbands in everything."} ]
        , 25: [ {class: "vs", text: "Husbands, love your wives, even as Christ also loved the assembly, and gave himself up for it;"} ]
        , 26: [ {class: "vs", text: "that he might sanctify it, having cleansed it by the washing of water with the word,"} ]
        , 27: [ {class: "vs", text: "that he might present the assembly to himself gloriously, not having spot or wrinkle or any such thing; but that it should be holy and without defect."} ]
        , 28: [ {class: "vs", text: "Even so husbands also ought to love their own wives as their own bodies. He who loves his own wife loves himself."} ]
        , 29: [ {class: "vs", text: "For no man ever hated his own flesh; but nourishes and cherishes it, even as the Lord also does the assembly;"} ]
        , 30: [ {class: "vs", text: "because we are members of his body, of his flesh and bones."} ]
        , 31: [ {class: "vs", text: "“For this cause a man will leave his father and mother, and will be joined to his wife. The two will become one flesh.”"} ]
        , 32: [ {class: "vs", text: "This mystery is great, but I speak concerning Christ and of the assembly."} ]
        , 33: [ {class: "vs", text: "Nevertheless each of you must also love his own wife even as himself; and let the wife see that she respects her husband."} ]
        }
  , 6:  { 1:  [ {class: "vs", text: "Children, obey your parents in the Lord, for this is right."} ]
        , 2:  [ {class: "vs", text: "“Honor your father and mother,” which is the first commandment with a promise:"} ]
        , 3:  [ {class: "vs", text: "“that it may be well with you, and you may live long on the earth.”"} ]
        , 4:  [ {class: "vs", text: "You fathers, don’t provoke your children to wrath, but nurture them in the discipline and instruction of the Lord."} ]
        , 5:  [ {class: "vs", text: "Servants, be obedient to those who according to the flesh are your masters, with fear and trembling, in singleness of your heart, as to Christ,"} ]
        , 6:  [ {class: "vs", text: "not in the way of service only when eyes are on you, as men pleasers, but as servants of Christ, doing the will of God from the heart,"} ]
        , 7:  [ {class: "vs", text: "with good will doing service as to the Lord, and not to men,"} ]
        , 8:  [ {class: "vs", text: "knowing that whatever good thing each one does, he will receive the same good again from the Lord, whether he is bound or free."} ]
        , 9:  [ {class: "vs", text: "You masters, do the same things to them, and give up threatening, knowing that he who is both their Master and yours is in heaven, and there is no partiality with him."} ]
        , 10: [ {class: "vs", text: "Finally, be strong in the Lord, and in the strength of his might."} ]
        , 11: [ {class: "vs", text: "Put on the whole armor of God, that you may be able to stand against the wiles of the devil."} ]
        , 12: [ {class: "vs", text: "For our wrestling is not against flesh and blood, but against the principalities, against the powers, against the world’s rulers of the darkness of this age, and against the spiritual forces of wickedness in the heavenly places."} ]
        , 13: [ {class: "vs", text: "Therefore put on the whole armor of God, that you may be able to withstand in the evil day, and having done all, to stand."} ]
        , 14: [ {class: "vs", text: "Stand therefore, having the utility belt of truth buckled around your waist, and having put on the breastplate of righteousness,"} ]
        , 15: [ {class: "vs", text: "and having fitted your feet with the preparation of the Good News of peace,"} ]
        , 16: [ {class: "vs", text: "above all, taking up the shield of faith, with which you will be able to quench all the fiery darts of the evil one."} ]
        , 17: [ {class: "vs", text: "And take the helmet of salvation, and the sword of the Spirit, which is the word of God;"} ]
        , 18: [ {class: "vs", text: "with all prayer and requests, praying at all times in the Spirit, and being watchful to this end in all perseverance and requests for all the saints:"} ]
        , 19: [ {class: "vs", text: "on my behalf, that utterance may be given to me in opening my mouth, to make known with boldness the mystery of the Good News,"} ]
        , 20: [ {class: "vs", text: "for which I am an ambassador in chains; that in it I may speak boldly, as I ought to speak."} ]
        , 21: [ {class: "vs", text: "But that you also may know my affairs, how I am doing, Tychicus, the beloved brother and faithful servant in the Lord, will make known to you all things."} ]
        , 22: [ {class: "vs", text: "I have sent him to you for this very purpose, that you may know our state and that he may comfort your hearts."} ]
        , 23: [ {class: "vs", text: "Peace be to the brothers, and love with faith, from God the Father and the Lord Jesus Christ."} ]
        , 24: [ {class: "vs", text: "Grace be with all those who love our Lord Jesus Christ with incorruptible love. Amen."} ]
        }
  }