exports.ezra =
  { 1: { 1: [ {class: "vs", text: "Now in the first year of Cyrus king of Persia, that Yahweh’s word by Jeremiah’s mouth might be accomplished, Yahweh stirred up the spirit of Cyrus king of Persia, so that he made a proclamation throughout all his kingdom, and put it also in writing, saying,"} ]
        , 2:  [ {class: "vs", text: "“Cyrus king of Persia says, ‘Yahweh, the God of heaven, has given me all the kingdoms of the earth; and he has commanded me to build him a house in Jerusalem, which is in Judah."} ]
        , 3:  [ {class: "vs", text: "Whoever there is among you of all his people, may his God be with him, and let him go up to Jerusalem, which is in Judah, and build the house of Yahweh, the God of Israel (he is God), which is in Jerusalem."} ]
        , 4:  [ {class: "vs", text: "Whoever is left, in any place where he lives, let the men of his place help him with silver, with gold, with goods, and with animals, in addition to the free will offering for God’s house which is in Jerusalem.’”"} ]
        , 5:  [ {class: "vs", text: "Then the heads of fathers’ households of Judah and Benjamin, the priests, and the Levites, all whose spirit God had stirred to go up rose up to build Yahweh’s house which is in Jerusalem."} ]
        , 6:  [ {class: "vs", text: "All those who were around them strengthened their hands with vessels of silver, with gold, with goods, with animals, and with precious things, in addition to all that was willingly offered."} ]
        , 7:  [ {class: "vs", text: "Also Cyrus the king brought out the vessels of Yahweh’s house, which Nebuchadnezzar had brought out of Jerusalem, and had put in the house of his gods;"} ]
        , 8:  [ {class: "vs", text: "even those, Cyrus king of Persia brought out by the hand of Mithredath the treasurer, and counted them out to Sheshbazzar, the prince of Judah."} ]
        , 9:  [ {class: "vs", text: "This is the number of them: thirty platters of gold, one thousand platters of silver, twenty-nine knives,"} ]
        , 10: [ {class: "vs", text: "thirty bowls of gold, four hundred ten silver bowls of a second sort, and one thousand other vessels."} ]
        , 11: [ {class: "vs", text: "All the vessels of gold and of silver were five thousand four hundred. Sheshbazzar brought all these up when the captives were brought up from Babylon to Jerusalem."} ]
        }
  , 10: { 1:  [ {class: "vs", text: "Now while Ezra prayed and made confession, weeping and casting himself down before God’s house, there was gathered together to him out of Israel a very great assembly of men and women and children; for the people wept very bitterly."} ]
        , 2:  [ {class: "vs", text: "Shecaniah the son of Jehiel, one of the sons of Elam, answered Ezra, “We have trespassed against our God, and have married foreign women of the peoples of the land. Yet now there is hope for Israel concerning this thing."} ]
        , 3:  [ {class: "vs", text: "Now therefore let’s make a covenant with our God to put away all the wives, and those who are born of them, according to the counsel of my lord, and of those who tremble at the commandment of our God. Let it be done according to the law."} ]
        , 4:  [ {class: "vs", text: "Arise; for the matter belongs to you, and we are with you. Be courageous, and do it.”"} ]
        , 5:  [ {class: "vs", text: "Then Ezra arose, and made the chiefs of the priests, the Levites, and all Israel, to swear that they would do according to this word. So they swore."} ]
        , 6:  [ {class: "vs", text: "Then Ezra rose up from before God’s house, and went into the room of Jehohanan the son of Eliashib. When he came there, he ate no bread, nor drank water; for he mourned because of their trespass of the captivity."} ]
        , 7:  [ {class: "vs", text: "They made a proclamation throughout Judah and Jerusalem to all the children of the captivity, that they should gather themselves together to Jerusalem;"} ]
        , 8:  [ {class: "vs", text: "and that whoever didn’t come within three days, according to the counsel of the princes and the elders, all his possessions should be forfeited, and himself separated from the assembly of the captivity."} ]
        , 9:  [ {class: "vs", text: "Then all the men of Judah and Benjamin gathered themselves together to Jerusalem within the three days. It was the ninth month, on the twentieth day of the month; and all the people sat in the wide place in front of God’s house, trembling because of this matter, and because of the great rain."} ]
        , 10: [ {class: "vs", text: "Ezra the priest stood up and said to them, “You have trespassed, and have married foreign women, to increase the guilt of Israel."} ]
        , 11: [ {class: "vs", text: "Now therefore make confession to Yahweh, the God of your fathers, and do his pleasure; and separate yourselves from the peoples of the land, and from the foreign women.”"} ]
        , 12: [ {class: "vs", text: "Then all the assembly answered with a loud voice, “We must do as you have said concerning us."} ]
        , 13: [ {class: "vs", text: "But the people are many, and it is a time of much rain, and we are not able to stand outside. This is not a work of one day or two, for we have greatly transgressed in this matter."} ]
        , 14: [ {class: "vs", text: "Now let our princes be appointed for all the assembly, and let all those who are in our cities who have married foreign women come at appointed times, and with them the elders of every city, and its judges, until the fierce wrath of our God is turned from us, until this matter is resolved.”"} ]
        , 15: [ {class: "vs", text: "Only Jonathan the son of Asahel and Jahzeiah the son of Tikvah stood up against this; and Meshullam and Shabbethai the Levite helped them."} ]
        , 16: [ {class: "vs", text: "The children of the captivity did so. Ezra the priest, with certain heads of fathers’ households, after their fathers’ houses, and all of them by their names, were set apart; and they sat down in the first day of the tenth month to examine the matter."} ]
        , 17: [ {class: "vs", text: "They finished with all the men who had married foreign women by the first day of the first month."} ]
        , 18: [ {class: "vs", text: "Among the sons of the priests there were found who had married foreign women:</p><p class=\"li\"> of the sons of Jeshua, the son of Jozadak, and his brothers, Maaseiah, and Eliezer, and Jarib, and Gedaliah."} ]
        , 19: [ {class: "vs", text: "They gave their hand that they would put away their wives; and being guilty, they offered a ram of the flock for their guilt."} ]
        , 20: [ {class: "vs", text: "Of the sons of Immer: Hanani and Zebadiah."} ]
        , 21: [ {class: "vs", text: "Of the sons of Harim: Maaseiah, and Elijah, and Shemaiah, and Jehiel, and Uzziah."} ]
        , 22: [ {class: "vs", text: "Of the sons of Pashhur: Elioenai, Maaseiah, Ishmael, Nethanel, Jozabad, and Elasah."} ]
        , 23: [ {class: "vs", text: "Of the Levites: Jozabad, and Shimei, and Kelaiah (also called Kelita), Pethahiah, Judah, and Eliezer."} ]
        , 24: [ {class: "vs", text: "Of the singers: Eliashib. Of the gatekeepers: Shallum, and Telem, and Uri."} ]
        , 25: [ {class: "vs", text: "Of Israel: Of the sons of Parosh: Ramiah, and Izziah, and Malchijah, and Mijamin, and Eleazar, and Malchijah, and Benaiah."} ]
        , 26: [ {class: "vs", text: "Of the sons of Elam: Mattaniah, Zechariah, and Jehiel, and Abdi, and Jeremoth, and Elijah."} ]
        , 27: [ {class: "vs", text: "Of the sons of Zattu: Elioenai, Eliashib, Mattaniah, and Jeremoth, and Zabad, and Aziza."} ]
        , 28: [ {class: "vs", text: "Of the sons of Bebai: Jehohanan, Hananiah, Zabbai, Athlai."} ]
        , 29: [ {class: "vs", text: "Of the sons of Bani: Meshullam, Malluch, and Adaiah, Jashub, and Sheal, Jeremoth."} ]
        , 30: [ {class: "vs", text: "Of the sons of Pahathmoab: Adna, and Chelal, Benaiah, Maaseiah, Mattaniah, Bezalel, and Binnui, and Manasseh."} ]
        , 31: [ {class: "vs", text: "Of the sons of Harim: Eliezer, Isshijah, Malchijah, Shemaiah, Shimeon,"} ]
        , 32: [ {class: "vs", text: "Benjamin, Malluch, Shemariah."} ]
        , 33: [ {class: "vs", text: "Of the sons of Hashum: Mattenai, Mattattah, Zabad, Eliphelet, Jeremai, Manasseh, Shimei."} ]
        , 34: [ {class: "vs", text: "Of the sons of Bani: Maadai, Amram, and Uel,"} ]
        , 35: [ {class: "vs", text: "Benaiah, Bedeiah, Cheluhi,"} ]
        , 36: [ {class: "vs", text: "Vaniah, Meremoth, Eliashib,"} ]
        , 37: [ {class: "vs", text: "Mattaniah, Mattenai, and Jaasu,"} ]
        , 38: [ {class: "vs", text: "and Bani, and Binnui, Shimei,"} ]
        , 39: [ {class: "vs", text: "and Shelemiah, and Nathan, and Adaiah,"} ]
        , 40: [ {class: "vs", text: "Machnadebai, Shashai, Sharai,"} ]
        , 41: [ {class: "vs", text: "Azarel, and Shelemiah, Shemariah,"} ]
        , 42: [ {class: "vs", text: "Shallum, Amariah, Joseph."} ]
        , 43: [ {class: "vs", text: "Of the sons of Nebo: Jeiel, Mattithiah, Zabad, Zebina, Iddo, and Joel, Benaiah."} ]
        , 44: [ {class: "vs", text: "All these had taken foreign wives; and some of them had wives by whom they had children."} ]
        }
  , 2:  { 1:  [ {class: "vs", text: "Now these are the children of the province, who went up out of the captivity of those who had been carried away, whom Nebuchadnezzar the king of Babylon had carried away to Babylon, and who returned to Jerusalem and Judah, everyone to his city;"} ]
        , 2:  [ {class: "vs", text: "who came with Zerubbabel, Jeshua, Nehemiah, Seraiah, Reelaiah, Mordecai, Bilshan, Mispar, Bigvai, Rehum, and Baanah.</p><p> The number of the men of the people of Israel:"} ]
        , 3:  [ {class: "vs", text: "The children of Parosh, two thousand one hundred seventy-two."} ]
        , 4:  [ {class: "vs", text: "The children of Shephatiah, three hundred seventy-two."} ]
        , 5:  [ {class: "vs", text: "The children of Arah, seven hundred seventy-five."} ]
        , 6:  [ {class: "vs", text: "The children of Pahathmoab, of the children of Jeshua and Joab, two thousand eight hundred twelve."} ]
        , 7:  [ {class: "vs", text: "The children of Elam, one thousand two hundred fifty-four."} ]
        , 8:  [ {class: "vs", text: "The children of Zattu, nine hundred forty-five."} ]
        , 9:  [ {class: "vs", text: "The children of Zaccai, seven hundred sixty."} ]
        , 10: [ {class: "vs", text: "The children of Bani, six hundred forty-two."} ]
        , 11: [ {class: "vs", text: "The children of Bebai, six hundred twenty-three."} ]
        , 12: [ {class: "vs", text: "The children of Azgad, one thousand two hundred twenty-two."} ]
        , 13: [ {class: "vs", text: "The children of Adonikam, six hundred sixty-six."} ]
        , 14: [ {class: "vs", text: "The children of Bigvai, two thousand fifty-six."} ]
        , 15: [ {class: "vs", text: "The children of Adin, four hundred fifty-four."} ]
        , 16: [ {class: "vs", text: "The children of Ater, of Hezekiah, ninety-eight."} ]
        , 17: [ {class: "vs", text: "The children of Bezai, three hundred twenty-three."} ]
        , 18: [ {class: "vs", text: "The children of Jorah, one hundred twelve."} ]
        , 19: [ {class: "vs", text: "The children of Hashum, two hundred twenty-three."} ]
        , 20: [ {class: "vs", text: "The children of Gibbar, ninety-five."} ]
        , 21: [ {class: "vs", text: "The children of Bethlehem, one hundred twenty-three."} ]
        , 22: [ {class: "vs", text: "The men of Netophah, fifty-six."} ]
        , 23: [ {class: "vs", text: "The men of Anathoth, one hundred twenty-eight."} ]
        , 24: [ {class: "vs", text: "The children of Azmaveth, forty-two."} ]
        , 25: [ {class: "vs", text: "The children of Kiriath Arim, Chephirah, and Beeroth, seven hundred forty-three."} ]
        , 26: [ {class: "vs", text: "The children of Ramah and Geba, six hundred twenty-one."} ]
        , 27: [ {class: "vs", text: "The men of Michmas, one hundred twenty-two."} ]
        , 28: [ {class: "vs", text: "The men of Bethel and Ai, two hundred twenty-three."} ]
        , 29: [ {class: "vs", text: "The children of Nebo, fifty-two."} ]
        , 30: [ {class: "vs", text: "The children of Magbish, one hundred fifty-six."} ]
        , 31: [ {class: "vs", text: "The children of the other Elam, one thousand two hundred fifty-four."} ]
        , 32: [ {class: "vs", text: "The children of Harim, three hundred twenty."} ]
        , 33: [ {class: "vs", text: "The children of Lod, Hadid, and Ono, seven hundred twenty-five."} ]
        , 34: [ {class: "vs", text: "The children of Jericho, three hundred forty-five."} ]
        , 35: [ {class: "vs", text: "The children of Senaah, three thousand six hundred thirty."} ]
        , 36: [ {class: "vs", text: "The priests: the children of Jedaiah, of the house of Jeshua, nine hundred seventy-three."} ]
        , 37: [ {class: "vs", text: "The children of Immer, one thousand fifty-two."} ]
        , 38: [ {class: "vs", text: "The children of Pashhur, one thousand two hundred forty-seven."} ]
        , 39: [ {class: "vs", text: "The children of Harim, one thousand seventeen."} ]
        , 40: [ {class: "vs", text: "The Levites: the children of Jeshua and Kadmiel, of the children of Hodaviah, seventy-four."} ]
        , 41: [ {class: "vs", text: "The singers: the children of Asaph, one hundred twenty-eight."} ]
        , 42: [ {class: "vs", text: "The children of the gatekeepers: the children of Shallum, the children of Ater, the children of Talmon, the children of Akkub, the children of Hatita, the children of Shobai, in all one hundred thirty-nine."} ]
        , 43: [ {class: "vs", text: "The temple servants: the children of Ziha, the children of Hasupha, the children of Tabbaoth,"} ]
        , 44: [ {class: "vs", text: "the children of Keros, the children of Siaha, the children of Padon,"} ]
        , 45: [ {class: "vs", text: "the children of Lebanah, the children of Hagabah, the children of Akkub,"} ]
        , 46: [ {class: "vs", text: "the children of Hagab, the children of Shamlai, the children of Hanan,"} ]
        , 47: [ {class: "vs", text: "the children of Giddel, the children of Gahar, the children of Reaiah,"} ]
        , 48: [ {class: "vs", text: "the children of Rezin, the children of Nekoda, the children of Gazzam,"} ]
        , 49: [ {class: "vs", text: "the children of Uzza, the children of Paseah, the children of Besai,"} ]
        , 50: [ {class: "vs", text: "the children of Asnah, the children of Meunim, the children of Nephisim,"} ]
        , 51: [ {class: "vs", text: "the children of Bakbuk, the children of Hakupha, the children of Harhur,"} ]
        , 52: [ {class: "vs", text: "the children of Bazluth, the children of Mehida, the children of Harsha,"} ]
        , 53: [ {class: "vs", text: "the children of Barkos, the children of Sisera, the children of Temah,"} ]
        , 54: [ {class: "vs", text: "the children of Neziah, the children of Hatipha."} ]
        , 55: [ {class: "vs", text: "The children of Solomon’s servants: the children of Sotai, the children of Hassophereth, the children of Peruda,"} ]
        , 56: [ {class: "vs", text: "the children of Jaalah, the children of Darkon, the children of Giddel,"} ]
        , 57: [ {class: "vs", text: "the children of Shephatiah, the children of Hattil, the children of Pochereth Hazzebaim, the children of Ami."} ]
        , 58: [ {class: "vs", text: "All the temple servants, and the children of Solomon’s servants, were three hundred ninety-two."} ]
        , 59: [ {class: "vs", text: "These were those who went up from Tel Melah, Tel Harsha, Cherub, Addan, and Immer; but they could not show their fathers’ houses, and their offspring, whether they were of Israel:"} ]
        , 60: [ {class: "vs", text: "the children of Delaiah, the children of Tobiah, the children of Nekoda, six hundred fifty-two."} ]
        , 61: [ {class: "vs", text: "Of the children of the priests: the children of Habaiah, the children of Hakkoz, and the children of Barzillai, who took a wife of the daughters of Barzillai the Gileadite, and was called after their name."} ]
        , 62: [ {class: "vs", text: "These sought their place among those who were registered by genealogy, but they were not found: therefore were they deemed disqualified and removed from the priesthood."} ]
        , 63: [ {class: "vs", text: "The governor told them that they should not eat of the most holy things until a priest stood up to serve with Urim and with Thummim."} ]
        , 64: [ {class: "vs", text: "The whole assembly together was forty-two thousand three hundred sixty,"} ]
        , 65: [ {class: "vs", text: "in addition to their male servants and their female servants, of whom there were seven thousand three hundred thirty-seven; and they had two hundred singing men and singing women."} ]
        , 66: [ {class: "vs", text: "Their horses were seven hundred thirty-six; their mules, two hundred forty-five;"} ]
        , 67: [ {class: "vs", text: "their camels, four hundred thirty-five; their donkeys, six thousand seven hundred twenty."} ]
        , 68: [ {class: "vs", text: "Some of the heads of fathers’ households, when they came to Yahweh’s house which is in Jerusalem, offered willingly for God’s house to set it up in its place."} ]
        , 69: [ {class: "vs", text: "They gave according to their ability into the treasury of the work sixty-one thousand darics of gold, and five thousand minas of silver, and one hundred priests’ garments."} ]
        , 70: [ {class: "vs", text: "So the priests and the Levites, with some of the people, the singers, the gatekeepers, and the temple servants, lived in their cities, and all Israel in their cities."} ]
        }
  , 3:  { 1:  [ {class: "vs", text: "When the seventh month had come, and the children of Israel were in the cities, the people gathered themselves together as one man to Jerusalem."} ]
        , 2:  [ {class: "vs", text: "Then Jeshua the son of Jozadak stood up with his brothers the priests, and Zerubbabel the son of Shealtiel and his brothers, and built the altar of the God of Israel, to offer burnt offerings on it, as it is written in the law of Moses the man of God."} ]
        , 3:  [ {class: "vs", text: "In spite of their fear because of the peoples of the surrounding lands, they set the altar on its base; and they offered burnt offerings on it to Yahweh, even burnt offerings morning and evening."} ]
        , 4:  [ {class: "vs", text: "They kept the feast of booths, as it is written, and offered the daily burnt offerings by number, according to the ordinance, as the duty of every day required;"} ]
        , 5:  [ {class: "vs", text: "and afterward the continual burnt offering, the offerings of the new moons, of all the set feasts of Yahweh that were consecrated, and of everyone who willingly offered a free will offering to Yahweh."} ]
        , 6:  [ {class: "vs", text: "From the first day of the seventh month, they began to offer burnt offerings to Yahweh; but the foundation of Yahweh’s temple was not yet laid."} ]
        , 7:  [ {class: "vs", text: "They also gave money to the masons, and to the carpenters. They also gave food, drink, and oil to the people of Sidon and Tyre, to bring cedar trees from Lebanon to the sea, to Joppa, according to the grant that they had from Cyrus King of Persia."} ]
        , 8:  [ {class: "vs", text: "Now in the second year of their coming to God’s house at Jerusalem, in the second month, Zerubbabel the son of Shealtiel, and Jeshua the son of Jozadak, and the rest of their brothers the priests and the Levites, and all those who had come out of the captivity to Jerusalem, began the work and appointed the Levites, from twenty years old and upward, to have the oversight of the work of Yahweh’s house."} ]
        , 9:  [ {class: "vs", text: "Then Jeshua stood with his sons and his brothers, Kadmiel and his sons, the sons of Judah, together, to have the oversight of the workmen in God’s house: the sons of Henadad, with their sons and their brothers the Levites."} ]
        , 10: [ {class: "vs", text: "When the builders laid the foundation of Yahweh’s temple, they set the priests in their clothing with trumpets, with the Levites the sons of Asaph with cymbals, to praise Yahweh, according to the directions of David king of Israel."} ]
        , 11: [ {class: "vs", text: "They sang to one another in praising and giving thanks to Yahweh, “For he is good, for his loving kindness endures forever toward Israel.” All the people shouted with a great shout, when they praised Yahweh, because the foundation of Yahweh’s house had been laid."} ]
        , 12: [ {class: "vs", text: "But many of the priests and Levites and heads of fathers’ households, the old men who had seen the first house, when the foundation of this house was laid before their eyes, wept with a loud voice. Many also shouted aloud for joy,"} ]
        , 13: [ {class: "vs", text: "so that the people could not discern the noise of the shout of joy from the noise of the weeping of the people; for the people shouted with a loud shout, and the noise was heard far away."} ]
        }
  , 4:  { 1:  [ {class: "vs", text: "Now when the adversaries of Judah and Benjamin heard that the children of the captivity were building a temple to Yahweh, the God of Israel;"} ]
        , 2:  [ {class: "vs", text: "they came near to Zerubbabel, and to the heads of fathers’ households, and said to them, “Let us build with you; for we seek your God, as you do; and we have been sacrificing to him since the days of Esar Haddon king of Assyria, who brought us up here.”"} ]
        , 3:  [ {class: "vs", text: "But Zerubbabel, and Jeshua, and the rest of the heads of fathers’ households of Israel, said to them, “You have nothing to do with us in building a house to our God; but we ourselves together will build to Yahweh, the God of Israel, as king Cyrus the king of Persia has commanded us.”"} ]
        , 4:  [ {class: "vs", text: "Then the people of the land weakened the hands of the people of Judah, and troubled them in building."} ]
        , 5:  [ {class: "vs", text: "They hired counselors against them, to frustrate their purpose, all the days of Cyrus king of Persia, even until the reign of Darius king of Persia."} ]
        , 6:  [ {class: "vs", text: "In the reign of Ahasuerus, in the beginning of his reign, they wrote an accusation against the inhabitants of Judah and Jerusalem."} ]
        , 7:  [ {class: "vs", text: "In the days of Artaxerxes, Bishlam, Mithredath, Tabeel, and the rest of his companions, wrote to Artaxerxes king of Persia; and the writing of the letter was written in Syrian, and delivered in the Syrian language."} ]
        , 8:  [ {class: "vs", text: "Rehum the chancellor and Shimshai the scribe wrote a letter against Jerusalem to Artaxerxes the king as follows,"} ]
        , 9:  [ {class: "vs", text: "then Rehum the chancellor, Shimshai the scribe, and the rest of their companions, the Dinaites, and the Apharsathchites, the Tarpelites, the Apharsites, the Archevites, the Babylonians, the Shushanchites, the Dehaites, the Elamites,"} ]
        , 10: [ {class: "vs", text: "and the rest of the nations whom the great and noble Osnappar brought over, and set in the city of Samaria, and in the rest of the country beyond the River, and so forth, wrote."} ]
        , 11: [ {class: "vs", text: "This is the copy of the letter that they sent:</p><br /><p class=\"mi\"> To King Artaxerxes,</p><p class=\"mi\"> From your servants the men beyond the River."} ]
        , 12: [ {class: "vs", text: "Be it known to the king that the Jews who came up from you have come to us to Jerusalem. They are building the rebellious and bad city, and have finished the walls, and repaired the foundations."} ]
        , 13: [ {class: "vs", text: "Be it known now to the king that if this city is built and the walls finished, they will not pay tribute, custom, or toll, and in the end it will be hurtful to the kings."} ]
        , 14: [ {class: "vs", text: "Now because we eat the salt of the palace, and it is not appropriate for us to see the king’s dishonor, therefore we have sent and informed the king,"} ]
        , 15: [ {class: "vs", text: "that search may be made in the book of the records of your fathers. You will see in the book of the records, and know that this city is a rebellious city, and hurtful to kings and provinces, and that they have started rebellions within it in the past. That is why this city was destroyed."} ]
        , 16: [ {class: "vs", text: "We inform the king that, if this city is built and the walls finished, then you will have no possession beyond the River."} ]
        , 17: [ {class: "vs", text: "Then the king sent an answer to Rehum the chancellor, and to Shimshai the scribe, and to the rest of their companions who live in Samaria, and in the rest of the country beyond the River:</p><br /><p class=\"mi\"> Peace."} ]
        , 18: [ {class: "vs", text: "The letter which you sent to us has been plainly read before me."} ]
        , 19: [ {class: "vs", text: "I decreed, and search has been made, and it was found that this city has made insurrection against kings in the past, and that rebellion and revolts have been made in it."} ]
        , 20: [ {class: "vs", text: "There have also been mighty kings over Jerusalem, who have ruled over all the country beyond the River; and tribute, custom, and toll, was paid to them."} ]
        , 21: [ {class: "vs", text: "Make a decree now to cause these men to cease, and that this city not be built, until a decree is made by me."} ]
        , 22: [ {class: "vs", text: "Be careful that you not be slack doing so. Why should damage grow to the hurt of the kings?"} ]
        , 23: [ {class: "vs", text: "Then when the copy of king Artaxerxes’ letter was read before Rehum, Shimshai the scribe, and their companions, they went in haste to Jerusalem to the Jews, and made them to cease by force of arms."} ]
        , 24: [ {class: "vs", text: "Then work stopped on God’s house which is at Jerusalem. It stopped until the second year of the reign of Darius king of Persia."} ]
        }
  , 5:  { 1:  [ {class: "vs", text: "Now the prophets, Haggai the prophet and Zechariah the son of Iddo, prophesied to the Jews who were in Judah and Jerusalem. They prophesied to them in the name of the God of Israel."} ]
        , 2:  [ {class: "vs", text: "Then Zerubbabel the son of Shealtiel, and Jeshua the son of Jozadak rose up and began to build God’s house which is at Jerusalem; and with them were the prophets of God, helping them."} ]
        , 3:  [ {class: "vs", text: "At the same time Tattenai, the governor beyond the River came to them, with Shetharbozenai, and their companions, and asked them, “Who gave you a decree to build this house, and to finish this wall?”"} ]
        , 4:  [ {class: "vs", text: "They also asked for the names of the men were who were making this building."} ]
        , 5:  [ {class: "vs", text: "But the eye of their God was on the elders of the Jews, and they didn’t make them cease, until the matter should come to Darius, and an answer should be returned by letter concerning it."} ]
        , 6:  [ {class: "vs", text: "The copy of the letter that Tattenai, the governor beyond the River, and Shetharbozenai, and his companions the Apharsachites, who were beyond the River, sent to Darius the king follows."} ]
        , 7:  [ {class: "vs", text: "They sent a letter to him, in which was written:</p><br /><p class=\"mi\"> To Darius the king, all peace."} ]
        , 8:  [ {class: "vs", text: "Be it known to the king that we went into the province of Judah, to the house of the great God, which is built with great stones, and timber is laid in the walls. This work goes on with diligence and prospers in their hands."} ]
        , 9:  [ {class: "vs", text: "Then we asked those elders, and said to them thus, “Who gave you a decree to build this house, and to finish this wall?”"} ]
        , 10: [ {class: "vs", text: "We asked them their names also, to inform you that we might write the names of the men who were at their head."} ]
        , 11: [ {class: "vs", text: "Thus they returned us answer, saying, “We are the servants of the God of heaven and earth, and are building the house that was built these many years ago, which a great king of Israel built and finished."} ]
        , 12: [ {class: "vs", text: "But after our fathers had provoked the God of heaven to wrath, he gave them into the hand of Nebuchadnezzar king of Babylon, the Chaldean, who destroyed this house, and carried the people away into Babylon."} ]
        , 13: [ {class: "vs", text: "But in the first year of Cyrus king of Babylon, Cyrus the king made a decree to build this house of God."} ]
        , 14: [ {class: "vs", text: "The gold and silver vessels of God’s house, which Nebuchadnezzar took out of the temple that was in Jerusalem, and brought into the temple of Babylon, those Cyrus the king also took out of the temple of Babylon, and they were delivered to one whose name was Sheshbazzar, whom he had made governor."} ]
        , 15: [ {class: "vs", text: "He said to him, ‘Take these vessels, go, put them in the temple that is in Jerusalem, and let God’s house be built in its place.’"} ]
        , 16: [ {class: "vs", text: "Then the same Sheshbazzar came and laid the foundations of God’s house which is in Jerusalem. Since that time even until now it has been being built, and yet it is not completed."} ]
        , 17: [ {class: "vs", text: "Now therefore, if it seems good to the king, let a search be made in the king’s treasure house, which is there at Babylon, whether it is so, that a decree was made of Cyrus the king to build this house of God at Jerusalem; and let the king send his pleasure to us concerning this matter.”"} ]
       }
        , 6:  { 1:  [ {class: "vs", text: "Then Darius the king made a decree, and the house of the archives, where the treasures were laid up in Babylon, was searched."} ]
        , 2:  [ {class: "vs", text: "A scroll was found at Achmetha, in the palace that is in the province of Media, and in it this was written for a record:"} ]
        , 3:  [ {class: "vs", text: "In the first year of Cyrus the king, Cyrus the king made a decree: Concerning God’s house at Jerusalem, let the house be built, the place where they offer sacrifices, and let its foundations be strongly laid; with its height sixty cubits, and its width sixty cubits;"} ]
        , 4:  [ {class: "vs", text: "with three courses of great stones and a course of new timber. Let the expenses be given out of the king’s house."} ]
        , 5:  [ {class: "vs", text: "Also let the gold and silver vessels of God’s house, which Nebuchadnezzar took out of the temple which is at Jerusalem, and brought to Babylon, be restored and brought again to the temple which is at Jerusalem, everything to its place. You shall put them in God’s house."} ]
        , 6:  [ {class: "vs", text: "Now therefore, Tattenai, governor beyond the River, Shetharbozenai, and your companions the Apharsachites, who are beyond the River, you must stay far from there."} ]
        , 7:  [ {class: "vs", text: "Leave the work of this house of God alone; let the governor of the Jews and the elders of the Jews build this house of God in its place."} ]
        , 8:  [ {class: "vs", text: "Moreover I make a decree what you shall do for these elders of the Jews for the building of this house of God: that of the king’s goods, even of the tribute beyond the River, expenses must be given with all diligence to these men, that they not be hindered."} ]
        , 9:  [ {class: "vs", text: "That which they have need of, including young bulls, rams, and lambs, for burnt offerings to the God of heaven; also wheat, salt, wine, and oil, according to the word of the priests who are at Jerusalem, let it be given them day by day without fail;"} ]
        , 10: [ {class: "vs", text: "that they may offer sacrifices of pleasant aroma to the God of heaven, and pray for the life of the king, and of his sons."} ]
        , 11: [ {class: "vs", text: "I have also made a decree that whoever alters this message, let a beam be pulled out from his house, and let him be lifted up and fastened on it; and let his house be made a dunghill for this."} ]
        , 12: [ {class: "vs", text: "May the God who has caused his name to dwell there overthrow all kings and peoples who stretch out their hand to alter this, to destroy this house of God which is at Jerusalem. I Darius have made a decree. Let it be done with all diligence."} ]
        , 13: [ {class: "vs", text: "Then Tattenai, the governor beyond the River, Shetharbozenai, and their companions did accordingly with all diligence, because Darius the king had sent a decree."} ]
        , 14: [ {class: "vs", text: "The elders of the Jews built and prospered, through the prophesying of Haggai the prophet and Zechariah the son of Iddo. They built and finished it, according to the commandment of the God of Israel, and according to the decree of Cyrus, Darius, and Artaxerxes king of Persia."} ]
        , 15: [ {class: "vs", text: "This house was finished on the third day of the month Adar, which was in the sixth year of the reign of Darius the king."} ]
        , 16: [ {class: "vs", text: "The children of Israel, the priests, the Levites, and the rest of the children of the captivity, kept the dedication of this house of God with joy."} ]
        , 17: [ {class: "vs", text: "They offered at the dedication of this house of God one hundred bulls, two hundred rams, four hundred lambs; and for a sin offering for all Israel, twelve male goats, according to the number of the tribes of Israel."} ]
        , 18: [ {class: "vs", text: "They set the priests in their divisions, and the Levites in their courses, for the service of God, which is at Jerusalem, as it is written in the book of Moses."} ]
        , 19: [ {class: "vs", text: "The children of the captivity kept the Passover on the fourteenth day of the first month."} ]
        , 20: [ {class: "vs", text: "Because the priests and the Levites had purified themselves together, all of them were pure. They killed the Passover for all the children of the captivity, for their brothers the priests, and for themselves."} ]
        , 21: [ {class: "vs", text: "The children of Israel who had returned out of the captivity, and all who had separated themselves to them from the filthiness of the nations of the land, to seek Yahweh, the God of Israel, ate,"} ]
        , 22: [ {class: "vs", text: "and kept the feast of unleavened bread seven days with joy; because Yahweh had made them joyful, and had turned the heart of the king of Assyria to them, to strengthen their hands in the work of God, the God of Israel’s house."} ]
        }
  , 7:  { 1:  [ {class: "vs", text: "Now after these things, in the reign of Artaxerxes king of Persia, Ezra the son of Seraiah, the son of Azariah, the son of Hilkiah,"} ]
        , 2:  [ {class: "vs", text: "the son of Shallum, the son of Zadok, the son of Ahitub,"} ]
        , 3:  [ {class: "vs", text: "the son of Amariah, the son of Azariah, the son of Meraioth,"} ]
        , 4:  [ {class: "vs", text: "the son of Zerahiah, the son of Uzzi, the son of Bukki,"} ]
        , 5:  [ {class: "vs", text: "the son of Abishua, the son of Phinehas, the son of Eleazar, the son of Aaron the chief priest—"} ]
        , 6:  [ {class: "vs", text: "this Ezra went up from Babylon. He was a skilled scribe in the law of Moses, which Yahweh, the God of Israel, had given; and the king granted him all his request, according to Yahweh his God’s hand on him."} ]
        , 7:  [ {class: "vs", text: "Some of the children of Israel, including some of the priests, the Levites, the singers, the gatekeepers, and the temple servants went up to Jerusalem in the seventh year of Artaxerxes the king."} ]
        , 8:  [ {class: "vs", text: "He came to Jerusalem in the fifth month, which was in the seventh year of the king."} ]
        , 9:  [ {class: "vs", text: "For on the first day of the first month he began to go up from Babylon; and on the first day of the fifth month he came to Jerusalem, according to the good hand of his God on him."} ]
        , 10: [ {class: "vs", text: "For Ezra had set his heart to seek Yahweh’s law, and to do it, and to teach statutes and ordinances in Israel."} ]
        , 11: [ {class: "vs", text: "Now this is the copy of the letter that the king Artaxerxes gave to Ezra the priest, the scribe, even the scribe of the words of Yahweh’s commandments, and of his statutes to Israel:"} ]
        , 12: [ {class: "vs", text: "Artaxerxes, king of kings,</p><p class=\"mi\"> To Ezra the priest, the scribe of the law of the perfect God of heaven.</p><p class=\"pi\"> Now"} ]
        , 13: [ {class: "vs", text: "I make a decree, that all those of the people of Israel, and their priests and the Levites, in my realm, who intend of their own free will to go to Jerusalem, go with you."} ]
        , 14: [ {class: "vs", text: "Because you are sent by the king and his seven counselors, to inquire concerning Judah and Jerusalem, according to the law of your God which is in your hand,"} ]
        , 15: [ {class: "vs", text: "and to carry the silver and gold, which the king and his counselors have freely offered to the God of Israel, whose habitation is in Jerusalem,"} ]
        , 16: [ {class: "vs", text: "and all the silver and gold that you will find in all the province of Babylon, with the free will offering of the people, and of the priests, offering willingly for the house of their God which is in Jerusalem;"} ]
        , 17: [ {class: "vs", text: "therefore you shall with all diligence buy with this money bulls, rams, lambs, with their meal offerings and their drink offerings, and shall offer them on the altar of the house of your God which is in Jerusalem."} ]
        , 18: [ {class: "vs", text: "Whatever seems good to you and to your brothers to do with the rest of the silver and the gold, do that according to the will of your God."} ]
        , 19: [ {class: "vs", text: "The vessels that are given to you for the service of the house of your God, deliver before the God of Jerusalem."} ]
        , 20: [ {class: "vs", text: "Whatever more will be needed for the house of your God, which you may have occasion to give, give it out of the king’s treasure house."} ]
        , 21: [ {class: "vs", text: "I, even I Artaxerxes the king, make a decree to all the treasurers who are beyond the River, that whatever Ezra the priest, the scribe of the law of the God of heaven, requires of you, it shall be done with all diligence,"} ]
        , 22: [ {class: "vs", text: "up to one hundred talents of silver, and to one hundred cors of wheat, and to one hundred baths of wine, and to one hundred baths of oil, and salt without prescribing how much."} ]
        , 23: [ {class: "vs", text: "Whatever is commanded by the God of heaven, let it be done exactly for the house of the God of heaven; for why should there be wrath against the realm of the king and his sons?"} ]
        , 24: [ {class: "vs", text: "Also we inform you that it shall not be lawful to impose tribute, custom, or toll, on any of the priests, Levites, singers, gatekeepers, temple servants, or laborers of this house of God."} ]
        , 25: [ {class: "vs", text: "You, Ezra, according to the wisdom of your God that is in your hand, appoint magistrates and judges, who may judge all the people who are beyond the River, who all know the laws of your God; and teach him who doesn’t know them."} ]
        , 26: [ {class: "vs", text: "Whoever will not do the law of your God and the law of the king, let judgment be executed on him with all diligence, whether it is to death, or to banishment, or to confiscation of goods, or to imprisonment."} ]
        , 27: [ {class: "vs", text: "Blessed be Yahweh, the God of our fathers, who has put such a thing as this in the king’s heart, to beautify Yahweh’s house which is in Jerusalem;"} ]
        , 28: [ {class: "vs", text: "and has extended loving kindness to me before the king and his counselors, and before all the king’s mighty princes. I was strengthened according to Yahweh my God’s hand on me, and I gathered together chief men out of Israel to go up with me."} ]
        }
  , 8:  { 1:  [ {class: "vs", text: "Now these are the heads of their fathers’ households, and this is the genealogy of those who went up with me from Babylon, in the reign of Artaxerxes the king:"} ]
        , 2:  [ {class: "vs", text: "Of the sons of Phinehas, Gershom.</p><p class=\"li\"> Of the sons of Ithamar, Daniel.</p><p class=\"li\"> Of the sons of David, Hattush."} ]
        , 3:  [ {class: "vs", text: "Of the sons of Shecaniah, of the sons of Parosh, Zechariah; and with him were listed by genealogy of the males one hundred fifty."} ]
        , 4:  [ {class: "vs", text: "Of the sons of Pahathmoab, Eliehoenai the son of Zerahiah; and with him two hundred males."} ]
        , 5:  [ {class: "vs", text: "Of the sons of Shecaniah, the son of Jahaziel; and with him three hundred males."} ]
        , 6:  [ {class: "vs", text: "Of the sons of Adin, Ebed the son of Jonathan; and with him fifty males."} ]
        , 7:  [ {class: "vs", text: "Of the sons of Elam, Jeshaiah the son of Athaliah; and with him seventy males."} ]
        , 8:  [ {class: "vs", text: "Of the sons of Shephatiah, Zebadiah the son of Michael; and with him eighty males."} ]
        , 9:  [ {class: "vs", text: "Of the sons of Joab, Obadiah the son of Jehiel; and with him two hundred eighteen males."} ]
        , 10: [ {class: "vs", text: "Of the sons of Shelomith, the son of Josiphiah; and with him one hundred sixty males."} ]
        , 11: [ {class: "vs", text: "Of the sons of Bebai, Zechariah the son of Bebai; and with him twenty-eight males."} ]
        , 12: [ {class: "vs", text: "Of the sons of Azgad, Johanan the son of Hakkatan; and with him one hundred ten males."} ]
        , 13: [ {class: "vs", text: "Of the sons of Adonikam, who were the last; and these are their names: Eliphelet, Jeuel, and Shemaiah; and with them sixty males."} ]
        , 14: [ {class: "vs", text: "Of the sons of Bigvai, Uthai and Zabbud; and with them seventy males."} ]
        , 15: [ {class: "vs", text: "I gathered them together to the river that runs to Ahava; and there we encamped three days: and I looked around at the people and the priests, and found there were none of the sons of Levi."} ]
        , 16: [ {class: "vs", text: "Then sent I for Eliezer, for Ariel, for Shemaiah, for Elnathan, for Jarib, for Elnathan, for Nathan, for Zechariah, and for Meshullam, chief men; also for Joiarib and for Elnathan, who were teachers."} ]
        , 17: [ {class: "vs", text: "I sent them out to Iddo the chief at the place Casiphia; and I told them what they should tell Iddo, and his brothers the temple servants, at the place Casiphia, that they should bring to us ministers for the house of our God."} ]
        , 18: [ {class: "vs", text: "According to the good hand of our God on us they brought us a man of discretion, of the sons of Mahli, the son of Levi, the son of Israel; and Sherebiah, with his sons and his brothers, eighteen;"} ]
        , 19: [ {class: "vs", text: "and Hashabiah, and with him Jeshaiah of the sons of Merari, his brothers and their sons, twenty;"} ]
        , 20: [ {class: "vs", text: "and of the temple servants, whom David and the princes had given for the service of the Levites, two hundred twenty temple servants. All of them were mentioned by name."} ]
        , 21: [ {class: "vs", text: "Then I proclaimed a fast there, at the river Ahava, that we might humble ourselves before our God, to seek from him a straight way for us, and for our little ones, and for all our possessions."} ]
        , 22: [ {class: "vs", text: "For I was ashamed to ask of the king a band of soldiers and horsemen to help us against the enemy on the way, because we had spoken to the king, saying, “The hand of our God is on all those who seek him, for good; but his power and his wrath is against all those who forsake him.”"} ]
        , 23: [ {class: "vs", text: "So we fasted and begged our God for this: and he granted our request."} ]
        , 24: [ {class: "vs", text: "Then I set apart twelve of the chiefs of the priests, even Sherebiah, Hashabiah, and ten of their brothers with them,"} ]
        , 25: [ {class: "vs", text: "and weighed to them the silver, the gold, and the vessels, even the offering for the house of our God, which the king, his counselors, his princes, and all Israel there present, had offered."} ]
        , 26: [ {class: "vs", text: "I weighed into their hand six hundred fifty talents of silver, one hundred talents of silver vessels; one hundred talents of gold,"} ]
        , 27: [ {class: "vs", text: "twenty bowls of gold weighing one thousand darics; and two vessels of fine bright bronze, precious as gold."} ]
        , 28: [ {class: "vs", text: "I said to them, “You are holy to Yahweh, and the vessels are holy. The silver and the gold are a free will offering to Yahweh, the God of your fathers."} ]
        , 29: [ {class: "vs", text: "Watch and keep them, until you weigh them before the chiefs of the priests and the Levites, and the princes of the fathers’ households of Israel, at Jerusalem, in the rooms of Yahweh’s house.”"} ]
        , 30: [ {class: "vs", text: "So the priests and the Levites received the weight of the silver and the gold, and the vessels, to bring them to Jerusalem to the house of our God."} ]
        , 31: [ {class: "vs", text: "Then we departed from the river Ahava on the twelfth day of the first month, to go to Jerusalem. The hand of our God was on us, and he delivered us from the hand of the enemy and the bandit by the way."} ]
        , 32: [ {class: "vs", text: "We came to Jerusalem, and stayed there three days."} ]
        , 33: [ {class: "vs", text: "On the fourth day the silver and the gold and the vessels were weighed in the house of our God into the hand of Meremoth the son of Uriah the priest; and with him was Eleazar the son of Phinehas; and with them was Jozabad the son of Jeshua, and Noadiah the son of Binnui, the Levite;"} ]
        , 34: [ {class: "vs", text: "everything by number and by weight; and all the weight was written at that time."} ]
        , 35: [ {class: "vs", text: "The children of the captivity, who had come out of exile, offered burnt offerings to the God of Israel, twelve bulls for all Israel, ninety-six rams, seventy-seven lambs, and twelve male goats for a sin offering. All this was a burnt offering to Yahweh."} ]
        , 36: [ {class: "vs", text: "They delivered the king’s commissions to the king’s local governors, and to the governors beyond the River. So they supported the people and God’s house."} ]
        }
  , 9:  { 1:  [ {class: "vs", text: "Now when these things were done, the princes came near to me, saying, “The people of Israel, the priests, and the Levites, have not separated themselves from the peoples of the lands, following their abominations, even those of the Canaanites, the Hittites, the Perizzites, the Jebusites, the Ammonites, the Moabites, the Egyptians, and the Amorites."} ]
        , 2:  [ {class: "vs", text: "For they have taken of their daughters for themselves and for their sons, so that the holy offspring have mixed themselves with the peoples of the lands. Yes, the hand of the princes and rulers has been chief in this trespass.”"} ]
        , 3:  [ {class: "vs", text: "When I heard this thing, I tore my garment and my robe, and pulled the hair out of my head and of my beard, and sat down confounded."} ]
        , 4:  [ {class: "vs", text: "Then everyone who trembled at the words of the God of Israel were assembled to me, because of their trespass of the captivity; and I sat confounded until the evening offering."} ]
        , 5:  [ {class: "vs", text: "At the evening offering I arose up from my humiliation, even with my garment and my robe torn; and I fell on my knees, and spread out my hands to Yahweh my God;"} ]
        , 6:  [ {class: "vs", text: "and I said, “My God, I am ashamed and blush to lift up my face to you, my God; for our iniquities have increased over our head, and our guiltiness has grown up to the heavens."} ]
        , 7:  [ {class: "vs", text: "Since the days of our fathers we have been exceedingly guilty to this day; and for our iniquities we, our kings, and our priests, have been delivered into the hand of the kings of the lands, to the sword, to captivity, to plunder, and to confusion of face, as it is this day."} ]
        , 8:  [ {class: "vs", text: "Now for a little moment grace has been shown from Yahweh our God, to leave us a remnant to escape, and to give us a nail in his holy place, that our God may lighten our eyes, and revived us a little in our bondage."} ]
        , 9:  [ {class: "vs", text: "For we are bondservants; yet our God has not forsaken us in our bondage, but has extended loving kindness to us in the sight of the kings of Persia, to revive us, to set up the house of our God, and to repair its ruins, and to give us a wall in Judah and in Jerusalem."} ]
        , 10: [ {class: "vs", text: "“Now, our God, what shall we say after this? For we have forsaken your commandments,"} ]
        , 11: [ {class: "vs", text: "which you have commanded by your servants the prophets, saying, ‘The land, to which you go to possess it, is an unclean land through the uncleanness of the peoples of the lands, through their abominations, which have filled it from one end to another with their filthiness."} ]
        , 12: [ {class: "vs", text: "Now therefore don’t give your daughters to their sons. Don’t take their daughters to your sons, nor seek their peace or their prosperity forever; that you may be strong, and eat the good of the land, and leave it for an inheritance to your children forever.’"} ]
        , 13: [ {class: "vs", text: "“After all that has come on us for our evil deeds, and for our great guilt, since you, our God, have punished us less than our iniquities deserve, and have given us such a remnant,"} ]
        , 14: [ {class: "vs", text: "shall we again break your commandments, and join ourselves with the peoples that do these abominations? Wouldn’t you be angry with us until you had consumed us, so that there would be no remnant, nor any to escape?"} ]
        , 15: [ {class: "vs", text: "Yahweh, the God of Israel, you are righteous; for we are left a remnant that has escaped, as it is today. Behold, we are before you in our guiltiness; for no one can stand before you because of this.”"} ]
        }
  }