exports.philippians =
  { 1:  { 1:  [ {class: "vs", text: "Paul and Timothy, servants of Jesus Christ;</p><p> To all the saints in Christ Jesus who are at Philippi, with the overseers and servants:"} ]
        , 2:  [ {class: "vs", text: "Grace to you, and peace from God our Father and the Lord Jesus Christ."} ]
        , 3:  [ {class: "vs", text: "I thank my God whenever I remember you,"} ]
        , 4:  [ {class: "vs", text: "always in every request of mine on behalf of you all, making my requests with joy,"} ]
        , 5:  [ {class: "vs", text: "for your partnership in furtherance of the Good News from the first day until now;"} ]
        , 6:  [ {class: "vs", text: "being confident of this very thing, that he who began a good work in you will complete it until the day of Jesus Christ."} ]
        , 7:  [ {class: "vs", text: "It is even right for me to think this way on behalf of all of you, because I have you in my heart, because both in my bonds and in the defense and confirmation of the Good News, you all are partakers with me of grace."} ]
        , 8:  [ {class: "vs", text: "For God is my witness, how I long after all of you in the tender mercies of Christ Jesus."} ]
        , 9:  [ {class: "vs", text: "This I pray, that your love may abound yet more and more in knowledge and all discernment,"} ]
        , 10: [ {class: "vs", text: "so that you may approve the things that are excellent, that you may be sincere and without offense to the day of Christ,"} ]
        , 11: [ {class: "vs", text: "being filled with the fruits of righteousness, which are through Jesus Christ, to the glory and praise of God."} ]
        , 12: [ {class: "vs", text: "Now I desire to have you know, brothers, that the things which happened to me have turned out rather to the progress of the Good News,"} ]
        , 13: [ {class: "vs", text: "so that it became evident to the whole palace guard, and to all the rest, that my bonds are in Christ,"} ]
        , 14: [ {class: "vs", text: "and that most of the brothers in the Lord, being confident through my bonds, are more abundantly bold to speak the word of God without fear."} ]
        , 15: [ {class: "vs", text: "Some indeed preach Christ even out of envy and strife, and some also out of good will."} ]
        , 16: [ {class: "vs", text: "The former insincerely preach Christ from selfish ambition, thinking that they add affliction to my chains;"} ]
        , 17: [ {class: "vs", text: "but the latter out of love, knowing that I am appointed for the defense of the Good News."} ]
        , 18: [ {class: "vs", text: "What does it matter? Only that in every way, whether in pretense or in truth, Christ is proclaimed. I rejoice in this, yes, and will rejoice."} ]
        , 19: [ {class: "vs", text: "For I know that this will turn out to my salvation, through your prayers and the supply of the Spirit of Jesus Christ,"} ]
        , 20: [ {class: "vs", text: "according to my earnest expectation and hope, that I will in no way be disappointed, but with all boldness, as always, now also Christ will be magnified in my body, whether by life or by death."} ]
        , 21: [ {class: "vs", text: "For to me to live is Christ, and to die is gain."} ]
        , 22: [ {class: "vs", text: "But if I live on in the flesh, this will bring fruit from my work; yet I don’t know what I will choose."} ]
        , 23: [ {class: "vs", text: "But I am hard pressed between the two, having the desire to depart and be with Christ, which is far better."} ]
        , 24: [ {class: "vs", text: "Yet to remain in the flesh is more needful for your sake."} ]
        , 25: [ {class: "vs", text: "Having this confidence, I know that I will remain, yes, and remain with you all for your progress and joy in the faith,"} ]
        , 26: [ {class: "vs", text: "that your rejoicing may abound in Christ Jesus in me through my presence with you again."} ]
        , 27: [ {class: "vs", text: "Only let your way of life be worthy of the Good News of Christ, that whether I come and see you or am absent, I may hear of your state, that you stand firm in one spirit, with one soul striving for the faith of the Good News;"} ]
        , 28: [ {class: "vs", text: "and in nothing frightened by the adversaries, which is for them a proof of destruction, but to you of salvation, and that from God."} ]
        , 29: [ {class: "vs", text: "Because it has been granted to you on behalf of Christ, not only to believe in him, but also to suffer on his behalf,"} ]
        , 30: [ {class: "vs", text: "having the same conflict which you saw in me and now hear is in me."} ]
        }
  , 2:  { 1:  [ {class: "vs", text: "If therefore there is any exhortation in Christ, if any consolation of love, if any fellowship of the Spirit, if any tender mercies and compassion,"} ]
        , 2:  [ {class: "vs", text: "make my joy full by being like-minded, having the same love, being of one accord, of one mind;"} ]
        , 3:  [ {class: "vs", text: "doing nothing through rivalry or through conceit, but in humility, each counting others better than himself;"} ]
        , 4:  [ {class: "vs", text: "each of you not just looking to his own things, but each of you also to the things of others."} ]
        , 5:  [ {class: "vs", text: "Have this in your mind, which was also in Christ Jesus,"} ]
        , 6:  [ {class: "vs", text: "who, existing in the form of God, didn’t consider equality with God a thing to be grasped,"} ]
        , 7:  [ {class: "vs", text: "but emptied himself, taking the form of a servant, being made in the likeness of men."} ]
        , 8:  [ {class: "vs", text: "And being found in human form, he humbled himself, becoming obedient to the point of death, yes, the death of the cross."} ]
        , 9:  [ {class: "vs", text: "Therefore God also highly exalted him, and gave to him the name which is above every name,"} ]
        , 10: [ {class: "vs", text: "that at the name of Jesus every knee should bow, of those in heaven, those on earth, and those under the earth,"} ]
        , 11: [ {class: "vs", text: "and that every tongue should confess that Jesus Christ is Lord, to the glory of God the Father."} ]
        , 12: [ {class: "vs", text: "So then, my beloved, even as you have always obeyed, not only in my presence, but now much more in my absence, work out your own salvation with fear and trembling."} ]
        , 13: [ {class: "vs", text: "For it is God who works in you both to will and to work, for his good pleasure."} ]
        , 14: [ {class: "vs", text: "Do all things without complaining and arguing,"} ]
        , 15: [ {class: "vs", text: "that you may become blameless and harmless, children of God without defect in the middle of a crooked and perverse generation, among whom you are seen as lights in the world,"} ]
        , 16: [ {class: "vs", text: "holding up the word of life, that I may have something to boast in the day of Christ, that I didn’t run in vain nor labor in vain."} ]
        , 17: [ {class: "vs", text: "Yes, and if I am poured out on the sacrifice and service of your faith, I rejoice, and rejoice with you all."} ]
        , 18: [ {class: "vs", text: "In the same way, you also rejoice, and rejoice with me."} ]
        , 19: [ {class: "vs", text: "But I hope in the Lord Jesus to send Timothy to you soon, that I also may be cheered up when I know how you are doing."} ]
        , 20: [ {class: "vs", text: "For I have no one else like-minded, who will truly care about you."} ]
        , 21: [ {class: "vs", text: "For they all seek their own, not the things of Jesus Christ."} ]
        , 22: [ {class: "vs", text: "But you know the proof of him, that as a child serves a father, so he served with me in furtherance of the Good News."} ]
        , 23: [ {class: "vs", text: "Therefore I hope to send him at once, as soon as I see how it will go with me."} ]
        , 24: [ {class: "vs", text: "But I trust in the Lord that I myself also will come shortly."} ]
        , 25: [ {class: "vs", text: "But I counted it necessary to send to you Epaphroditus, my brother, fellow worker, fellow soldier, and your apostle and servant of my need,"} ]
        , 26: [ {class: "vs", text: "since he longed for you all, and was very troubled because you had heard that he was sick."} ]
        , 27: [ {class: "vs", text: "For indeed he was sick, nearly to death, but God had mercy on him, and not on him only, but on me also, that I might not have sorrow on sorrow."} ]
        , 28: [ {class: "vs", text: "I have sent him therefore the more diligently, that when you see him again, you may rejoice, and that I may be the less sorrowful."} ]
        , 29: [ {class: "vs", text: "Receive him therefore in the Lord with all joy, and hold such people in honor,"} ]
        , 30: [ {class: "vs", text: "because for the work of Christ he came near to death, risking his life to supply that which was lacking in your service toward me."} ]
        }
  , 3:  { 1:  [ {class: "vs", text: "Finally, my brothers, rejoice in the Lord! To write the same things to you, to me indeed is not tiresome, but for you it is safe."} ]
        , 2:  [ {class: "vs", text: "Beware of the dogs; beware of the evil workers; beware of the false circumcision."} ]
        , 3:  [ {class: "vs", text: "For we are the circumcision, who worship God in the Spirit, and rejoice in Christ Jesus, and have no confidence in the flesh;"} ]
        , 4:  [ {class: "vs", text: "though I myself might have confidence even in the flesh. If any other man thinks that he has confidence in the flesh, I yet more:"} ]
        , 5:  [ {class: "vs", text: "circumcised the eighth day, of the stock of Israel, of the tribe of Benjamin, a Hebrew of Hebrews; concerning the law, a Pharisee;"} ]
        , 6:  [ {class: "vs", text: "concerning zeal, persecuting the assembly; concerning the righteousness which is in the law, found blameless."} ]
        , 7:  [ {class: "vs", text: "However, I consider those things that were gain to me as a loss for Christ."} ]
        , 8:  [ {class: "vs", text: "Yes most certainly, and I count all things to be a loss for the excellency of the knowledge of Christ Jesus, my Lord, for whom I suffered the loss of all things, and count them nothing but refuse, that I may gain Christ"} ]
        , 9:  [ {class: "vs", text: "and be found in him, not having a righteousness of my own, that which is of the law, but that which is through faith in Christ, the righteousness which is from God by faith,"} ]
        , 10: [ {class: "vs", text: "that I may know him, and the power of his resurrection, and the fellowship of his sufferings, becoming conformed to his death,"} ]
        , 11: [ {class: "vs", text: "if by any means I may attain to the resurrection from the dead."} ]
        , 12: [ {class: "vs", text: "Not that I have already obtained, or am already made perfect; but I press on, that I may take hold of that for which also I was taken hold of by Christ Jesus."} ]
        , 13: [ {class: "vs", text: "Brothers, I don’t regard myself as yet having taken hold, but one thing I do: forgetting the things which are behind, and stretching forward to the things which are before,"} ]
        , 14: [ {class: "vs", text: "I press on toward the goal for the prize of the high calling of God in Christ Jesus."} ]
        , 15: [ {class: "vs", text: "Let us therefore, as many as are perfect, think this way. If in anything you think otherwise, God will also reveal that to you."} ]
        , 16: [ {class: "vs", text: "Nevertheless, to the extent that we have already attained, let’s walk by the same rule. Let’s be of the same mind."} ]
        , 17: [ {class: "vs", text: "Brothers, be imitators together of me, and note those who walk this way, even as you have us for an example."} ]
        , 18: [ {class: "vs", text: "For many walk, of whom I told you often, and now tell you even weeping, as the enemies of the cross of Christ,"} ]
        , 19: [ {class: "vs", text: "whose end is destruction, whose god is the belly, and whose glory is in their shame, who think about earthly things."} ]
        , 20: [ {class: "vs", text: "For our citizenship is in heaven, from where we also wait for a Savior, the Lord Jesus Christ,"} ]
        , 21: [ {class: "vs", text: "who will change the body of our humiliation to be conformed to the body of his glory, according to the working by which he is able even to subject all things to himself."} ]
        }
  , 4:  { 1:  [ {class: "vs", text: "Therefore, my brothers, beloved and longed for, my joy and crown, stand firm in the Lord in this way, my beloved."} ]
        , 2:  [ {class: "vs", text: "I exhort Euodia, and I exhort Syntyche, to think the same way in the Lord."} ]
        , 3:  [ {class: "vs", text: "Yes, I beg you also, true partner, help these women, for they labored with me in the Good News with Clement also, and the rest of my fellow workers, whose names are in the book of life."} ]
        , 4:  [ {class: "vs", text: "Rejoice in the Lord always! Again I will say, “Rejoice!”"} ]
        , 5:  [ {class: "vs", text: "Let your gentleness be known to all men. The Lord is at hand."} ]
        , 6:  [ {class: "vs", text: "In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God."} ]
        , 7:  [ {class: "vs", text: "And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus."} ]
        , 8:  [ {class: "vs", text: "Finally, brothers, whatever things are true, whatever things are honorable, whatever things are just, whatever things are pure, whatever things are lovely, whatever things are of good report: if there is any virtue and if there is any praise, think about these things."} ]
        , 9:  [ {class: "vs", text: "The things which you learned, received, heard, and saw in me: do these things, and the God of peace will be with you."} ]
        , 10: [ {class: "vs", text: "But I rejoice in the Lord greatly, that now at length you have revived your thought for me; in which you did indeed take thought, but you lacked opportunity."} ]
        , 11: [ {class: "vs", text: "Not that I speak because of lack, for I have learned in whatever state I am, to be content in it."} ]
        , 12: [ {class: "vs", text: "I know how to be humbled, and I also know how to abound. In everything and in all things I have learned the secret both to be filled and to be hungry, both to abound and to be in need."} ]
        , 13: [ {class: "vs", text: "I can do all things through Christ, who strengthens me."} ]
        , 14: [ {class: "vs", text: "However you did well that you shared in my affliction."} ]
        , 15: [ {class: "vs", text: "You yourselves also know, you Philippians, that in the beginning of the Good News, when I departed from Macedonia, no assembly shared with me in the matter of giving and receiving but you only."} ]
        , 16: [ {class: "vs", text: "For even in Thessalonica you sent once and again to my need."} ]
        , 17: [ {class: "vs", text: "Not that I seek for the gift, but I seek for the fruit that increases to your account."} ]
        , 18: [ {class: "vs", text: "But I have all things and abound. I am filled, having received from Epaphroditus the things that came from you, a sweet-smelling fragrance, an acceptable and well-pleasing sacrifice to God."} ]
        , 19: [ {class: "vs", text: "My God will supply every need of yours according to his riches in glory in Christ Jesus."} ]
        , 20: [ {class: "vs", text: "Now to our God and Father be the glory forever and ever! Amen."} ]
        , 21: [ {class: "vs", text: "Greet every saint in Christ Jesus. The brothers who are with me greet you."} ]
        , 22: [ {class: "vs", text: "All the saints greet you, especially those who are of Caesar’s household."} ]
        , 23: [ {class: "vs", text: "The grace of the Lord Jesus Christ be with you all. Amen."} ]
        }
  }