exports.romans =
  { 1:  { 1:  [ {class: "vs", text: "Paul, a servant of Jesus Christ, called to be an apostle, set apart for the Good News of God,"} ]
        , 2:  [ {class: "vs", text: "which he promised before through his prophets in the holy Scriptures,"} ]
        , 3:  [ {class: "vs", text: "concerning his Son, who was born of the offspring of David according to the flesh,"} ]
        , 4:  [ {class: "vs", text: "who was declared to be the Son of God with power, according to the Spirit of holiness, by the resurrection from the dead, Jesus Christ our Lord,"} ]
        , 5:  [ {class: "vs", text: "through whom we received grace and apostleship for obedience of faith among all the nations for his name’s sake;"} ]
        , 6:  [ {class: "vs", text: "among whom you are also called to belong to Jesus Christ;"} ]
        , 7:  [ {class: "vs", text: "to all who are in Rome, beloved of God, called to be saints: Grace to you and peace from God our Father and the Lord Jesus Christ."} ]
        , 8:  [ {class: "vs", text: "First, I thank my God through Jesus Christ for all of you, that your faith is proclaimed throughout the whole world."} ]
        , 9:  [ {class: "vs", text: "For God is my witness, whom I serve in my spirit in the Good News of his Son, how unceasingly I make mention of you always in my prayers,"} ]
        , 10: [ {class: "vs", text: "requesting, if by any means now at last I may be prospered by the will of God to come to you."} ]
        , 11: [ {class: "vs", text: "For I long to see you, that I may impart to you some spiritual gift, to the end that you may be established;"} ]
        , 12: [ {class: "vs", text: "that is, that I with you may be encouraged in you, each of us by the other’s faith, both yours and mine."} ]
        , 13: [ {class: "vs", text: "Now I don’t desire to have you unaware, brothers, that I often planned to come to you, and was hindered so far, that I might have some fruit among you also, even as among the rest of the Gentiles."} ]
        , 14: [ {class: "vs", text: "I am debtor both to Greeks and to foreigners, both to the wise and to the foolish."} ]
        , 15: [ {class: "vs", text: "So as much as is in me, I am eager to preach the Good News to you also who are in Rome."} ]
        , 16: [ {class: "vs", text: "For I am not ashamed of the Good News of Christ, because it is the power of God for salvation for everyone who believes, for the Jew first, and also for the Greek."} ]
        , 17: [ {class: "vs", text: "For in it is revealed God’s righteousness from faith to faith. As it is written, “But the righteous shall live by faith.”"} ]
        , 18: [ {class: "vs", text: "For the wrath of God is revealed from heaven against all ungodliness and unrighteousness of men who suppress the truth in unrighteousness,"} ]
        , 19: [ {class: "vs", text: "because that which is known of God is revealed in them, for God revealed it to them."} ]
        , 20: [ {class: "vs", text: "For the invisible things of him since the creation of the world are clearly seen, being perceived through the things that are made, even his everlasting power and divinity, that they may be without excuse."} ]
        , 21: [ {class: "vs", text: "Because knowing God, they didn’t glorify him as God, and didn’t give thanks, but became vain in their reasoning, and their senseless heart was darkened."} ]
        , 22: [ {class: "vs", text: "Professing themselves to be wise, they became fools,"} ]
        , 23: [ {class: "vs", text: "and traded the glory of the incorruptible God for the likeness of an image of corruptible man, and of birds, four-footed animals, and creeping things."} ]
        , 24: [ {class: "vs", text: "Therefore God also gave them up in the lusts of their hearts to uncleanness, that their bodies should be dishonored among themselves;"} ]
        , 25: [ {class: "vs", text: "who exchanged the truth of God for a lie, and worshiped and served the creature rather than the Creator, who is blessed forever. Amen."} ]
        , 26: [ {class: "vs", text: "For this reason, God gave them up to vile passions. For their women changed the natural function into that which is against nature."} ]
        , 27: [ {class: "vs", text: "Likewise also the men, leaving the natural function of the woman, burned in their lust toward one another, men doing what is inappropriate with men, and receiving in themselves the due penalty of their error."} ]
        , 28: [ {class: "vs", text: "Even as they refused to have God in their knowledge, God gave them up to a reprobate mind, to do those things which are not fitting;"} ]
        , 29: [ {class: "vs", text: "being filled with all unrighteousness, sexual immorality, wickedness, covetousness, malice; full of envy, murder, strife, deceit, evil habits, secret slanderers,"} ]
        , 30: [ {class: "vs", text: "backbiters, hateful to God, insolent, arrogant, boastful, inventors of evil things, disobedient to parents,"} ]
        , 31: [ {class: "vs", text: "without understanding, covenant breakers, without natural affection, unforgiving, unmerciful;"} ]
        , 32: [ {class: "vs", text: "who, knowing the ordinance of God, that those who practice such things are worthy of death, not only do the same, but also approve of those who practice them."} ]
        }
  , 10: { 1:  [ {class: "vs", text: "Brothers, my heart’s desire and my prayer to God is for Israel, that they may be saved."} ]
        , 2:  [ {class: "vs", text: "For I testify about them that they have a zeal for God, but not according to knowledge."} ]
        , 3:  [ {class: "vs", text: "For being ignorant of God’s righteousness, and seeking to establish their own righteousness, they didn’t subject themselves to the righteousness of God."} ]
        , 4:  [ {class: "vs", text: "For Christ is the fulfillment of the law for righteousness to everyone who believes."} ]
        , 5:  [ {class: "vs", text: "For Moses writes about the righteousness of the law, “The one who does them will live by them.”"} ]
        , 6:  [ {class: "vs", text: "But the righteousness which is of faith says this, “Don’t say in your heart, ‘Who will ascend into heaven?’ (that is, to bring Christ down);"} ]
        , 7:  [ {class: "vs", text: "or, ‘Who will descend into the abyss?’ (that is, to bring Christ up from the dead.)”"} ]
        , 8:  [ {class: "vs", text: "But what does it say? “The word is near you, in your mouth, and in your heart;” that is, the word of faith which we preach:"} ]
        , 9:  [ {class: "vs", text: "that if you will confess with your mouth that Jesus is Lord, and believe in your heart that God raised him from the dead, you will be saved."} ]
        , 10: [ {class: "vs", text: "For with the heart, one believes resulting in righteousness; and with the mouth confession is made resulting in salvation."} ]
        , 11: [ {class: "vs", text: "For the Scripture says, “Whoever believes in him will not be disappointed.”"} ]
        , 12: [ {class: "vs", text: "For there is no distinction between Jew and Greek; for the same Lord is Lord of all, and is rich to all who call on him."} ]
        , 13: [ {class: "vs", text: "For, “Whoever will call on the name of the Lord will be saved.”"} ]
        , 14: [ {class: "vs", text: "How then will they call on him in whom they have not believed? How will they believe in him whom they have not heard? How will they hear without a preacher?"} ]
        , 15: [ {class: "endpara", text: "And how will they preach unless they are sent? As it is written:"}
              , {class: "q", text: "“How beautiful are the feet of those who preach the Good News of peace,"}
              , {class: "q2", text: "who bring glad tidings of good things!”"}
              ]
        , 16: [ {class: "vs", text: "But they didn’t all listen to the glad news. For Isaiah says, “Lord, who has believed our report?”"} ]
        , 17: [ {class: "vs", text: "So faith comes by hearing, and hearing by the word of God."} ]
        , 18: [ {class: "endpara", text: "But I say, didn’t they hear? Yes, most certainly,"}
              , {class: "q", text: "“Their sound went out into all the earth,"}
              , {class: "q2", text: "their words to the ends of the world.”"}
              ]
        , 19: [ {class: "endpara", text: "But I ask, didn’t Israel know? First Moses says,"}
              , {class: "q", text: "“I will provoke you to jealousy with that which is no nation."}
              , {class: "q2", text: "I will make you angry with a nation void of understanding.”"}
              ]
        , 20: [ {class: "endpara", text: "Isaiah is very bold and says,"}
                , {class: "q", text: "“I was found by those who didn’t seek me."}
              , {class: "q2", text: "I was revealed to those who didn’t ask for me.”"}
              ]
        , 21: [ {class: "vs", text: "But about Israel he says, “All day long I stretched out my hands to a disobedient and contrary people.”"} ]
        }
  , 11: { 1:  [ {class: "vs", text: "I ask then, did God reject his people? May it never be! For I also am an Israelite, a descendant of Abraham, of the tribe of Benjamin."} ]
        , 2:  [ {class: "vs", text: "God didn’t reject his people, which he foreknew. Or don’t you know what the Scripture says about Elijah? How he pleads with God against Israel:"} ]
        , 3:  [ {class: "vs", text: "“Lord, they have killed your prophets, they have broken down your altars. I am left alone, and they seek my life.”"} ]
        , 4:  [ {class: "vs", text: "But how does God answer him? “I have reserved for myself seven thousand men who have not bowed the knee to Baal.”"} ]
        , 5:  [ {class: "vs", text: "Even so then at this present time also there is a remnant according to the election of grace."} ]
        , 6:  [ {class: "vs", text: "And if by grace, then it is no longer of works; otherwise grace is no longer grace. But if it is of works, it is no longer grace; otherwise work is no longer work."} ]
        , 7:  [ {class: "vs", text: "What then? That which Israel seeks for, that he didn’t obtain, but the chosen ones obtained it, and the rest were hardened."} ]
        , 8:  [ {class: "vs", text: "According as it is written, “God gave them a spirit of stupor, eyes that they should not see, and ears that they should not hear, to this very day.”"} ]
        , 9:  [ {class: "endpara", text: "David says,"}
              , {class: "q", text: "“Let their table be made a snare, a trap,"}
              , {class: "q2", text: "a stumbling block, and a retribution to them."}
              ]
        , 10: [ {class: "q", text: "Let their eyes be darkened, that they may not see."}
              , {class: "q2", text: "Always keep their backs bent.”"}
              ]
        , 11: [ {class: "vs", text: "I ask then, did they stumble that they might fall? May it never be! But by their fall salvation has come to the Gentiles, to provoke them to jealousy."} ]
        , 12: [ {class: "vs", text: "Now if their fall is the riches of the world, and their loss the riches of the Gentiles; how much more their fullness?"} ]
        , 13: [ {class: "vs", text: "For I speak to you who are Gentiles. Since then as I am an apostle to Gentiles, I glorify my ministry;"} ]
        , 14: [ {class: "vs", text: "if by any means I may provoke to jealousy those who are my flesh, and may save some of them."} ]
        , 15: [ {class: "vs", text: "For if the rejection of them is the reconciling of the world, what would their acceptance be, but life from the dead?"} ]
        , 16: [ {class: "vs", text: "If the first fruit is holy, so is the lump. If the root is holy, so are the branches."} ]
        , 17: [ {class: "vs", text: "But if some of the branches were broken off, and you, being a wild olive, were grafted in among them and became partaker with them of the root and of the richness of the olive tree,"} ]
        , 18: [ {class: "vs", text: "don’t boast over the branches. But if you boast, it is not you who support the root, but the root supports you."} ]
        , 19: [ {class: "vs", text: "You will say then, “Branches were broken off, that I might be grafted in.”"} ]
        , 20: [ {class: "vs", text: "True; by their unbelief they were broken off, and you stand by your faith. Don’t be conceited, but fear;"} ]
        , 21: [ {class: "vs", text: "for if God didn’t spare the natural branches, neither will he spare you."} ]
        , 22: [ {class: "vs", text: "See then the goodness and severity of God. Toward those who fell, severity; but toward you, goodness, if you continue in his goodness; otherwise you also will be cut off."} ]
        , 23: [ {class: "vs", text: "They also, if they don’t continue in their unbelief, will be grafted in, for God is able to graft them in again."} ]
        , 24: [ {class: "vs", text: "For if you were cut out of that which is by nature a wild olive tree, and were grafted contrary to nature into a good olive tree, how much more will these, which are the natural branches, be grafted into their own olive tree?"} ]
        , 25: [ {class: "vs", text: "For I don’t desire you to be ignorant, brothers, of this mystery, so that you won’t be wise in your own conceits, that a partial hardening has happened to Israel, until the fullness of the Gentiles has come in,"} ]
        , 26: [ {class: "endpara", text: "and so all Israel will be saved. Even as it is written,"}
              , {class: "q", text: "“There will come out of Zion the Deliverer,"}
              , {class: "q2", text: "and he will turn away ungodliness from Jacob."}
              ]
        , 27: [ {class: "q", text: "This is my covenant with them,"}
              , {class: "q2", text: "when I will take away their sins.”"}
              ]
        , 28: [ {class: "vs", text: "Concerning the Good News, they are enemies for your sake. But concerning the election, they are beloved for the fathers’ sake."} ]
        , 29: [ {class: "vs", text: "For the gifts and the calling of God are irrevocable."} ]
        , 30: [ {class: "vs", text: "For as you in time past were disobedient to God, but now have obtained mercy by their disobedience,"} ]
        , 31: [ {class: "vs", text: "even so these also have now been disobedient, that by the mercy shown to you they may also obtain mercy."} ]
        , 32: [ {class: "vs", text: "For God has bound all to disobedience, that he might have mercy on all."} ]
        , 33: [ {class: "vs", text: "Oh the depth of the riches both of the wisdom and the knowledge of God! How unsearchable are his judgments, and his ways past tracing out!"} ]
        , 34: [ {class: "q", text: "“For who has known the mind of the Lord?"}
              , {class: "q2", text: "Or who has been his counselor?”"}
              ]
        , 35: [ {class: "q", text: "“Or who has first given to him,"}
              , {class: "q2", text: "and it will be repaid to him again?”"}
              ]
        , 36: [ {class: "vs", text: "For of him, and through him, and to him are all things. To him be the glory for ever! Amen."} ]
        }
  , 12: { 1:  [ {class: "vs", text: "Therefore I urge you, brothers, by the mercies of God, to present your bodies a living sacrifice, holy, acceptable to God, which is your spiritual service."} ]
        , 2:  [ {class: "vs", text: "Don’t be conformed to this world, but be transformed by the renewing of your mind, so that you may prove what is the good, well-pleasing, and perfect will of God."} ]
        , 3:  [ {class: "vs", text: "For I say through the grace that was given me, to every man who is among you, not to think of himself more highly than he ought to think; but to think reasonably, as God has apportioned to each person a measure of faith."} ]
        , 4:  [ {class: "vs", text: "For even as we have many members in one body, and all the members don’t have the same function,"} ]
        , 5:  [ {class: "vs", text: "so we, who are many, are one body in Christ, and individually members of one another,"} ]
        , 6:  [ {class: "vs", text: "having gifts differing according to the grace that was given to us: if prophecy, let’s prophesy according to the proportion of our faith;"} ]
        , 7:  [ {class: "vs", text: "or service, let’s give ourselves to service; or he who teaches, to his teaching;"} ]
        , 8:  [ {class: "vs", text: "or he who exhorts, to his exhorting; he who gives, let him do it with generosity; he who rules, with diligence; he who shows mercy, with cheerfulness."} ]
        , 9:  [ {class: "vs", text: "Let love be without hypocrisy. Abhor that which is evil. Cling to that which is good."} ]
        , 10: [ {class: "vs", text: "In love of the brothers be tenderly affectionate to one another; in honor preferring one another;"} ]
        , 11: [ {class: "vs", text: "not lagging in diligence; fervent in spirit; serving the Lord;"} ]
        , 12: [ {class: "vs", text: "rejoicing in hope; enduring in troubles; continuing steadfastly in prayer;"} ]
        , 13: [ {class: "vs", text: "contributing to the needs of the saints; given to hospitality."} ]
        , 14: [ {class: "vs", text: "Bless those who persecute you; bless, and don’t curse."} ]
        , 15: [ {class: "vs", text: "Rejoice with those who rejoice. Weep with those who weep."} ]
        , 16: [ {class: "vs", text: "Be of the same mind one toward another. Don’t set your mind on high things, but associate with the humble. Don’t be wise in your own conceits."} ]
        , 17: [ {class: "vs", text: "Repay no one evil for evil. Respect what is honorable in the sight of all men."} ]
        , 18: [ {class: "vs", text: "If it is possible, as much as it is up to you, be at peace with all men."} ]
        , 19: [ {class: "vs", text: "Don’t seek revenge yourselves, beloved, but give place to God’s wrath. For it is written, “Vengeance belongs to me; I will repay, says the Lord.”"} ]
        , 20: [ {class: "endpara", text: "Therefore"}
              , {class: "q", text: "“If your enemy is hungry, feed him."}
              , {class: "q2", text: "If he is thirsty, give him a drink;"}
              , {class: "q2", text: "for in doing so, you will heap coals of fire on his head.”"}
              ]
        , 21: [ {class: "vs", text: "Don’t be overcome by evil, but overcome evil with good."} ]
        }
  , 13: { 1:  [ {class: "vs", text: "Let every soul be in subjection to the higher authorities, for there is no authority except from God, and those who exist are ordained by God."} ]
        , 2:  [ {class: "vs", text: "Therefore he who resists the authority withstands the ordinance of God; and those who withstand will receive to themselves judgment."} ]
        , 3:  [ {class: "vs", text: "For rulers are not a terror to the good work, but to the evil. Do you desire to have no fear of the authority? Do that which is good, and you will have praise from the authority,"} ]
        , 4:  [ {class: "vs", text: "for he is a servant of God to you for good. But if you do that which is evil, be afraid, for he doesn’t bear the sword in vain; for he is a servant of God, an avenger for wrath to him who does evil."} ]
        , 5:  [ {class: "vs", text: "Therefore you need to be in subjection, not only because of the wrath, but also for conscience’ sake."} ]
        , 6:  [ {class: "vs", text: "For this reason you also pay taxes, for they are servants of God’s service, continually doing this very thing."} ]
        , 7:  [ {class: "vs", text: "Therefore give everyone what you owe: if you owe taxes, pay taxes; if customs, then customs; if respect, then respect; if honor, then honor."} ]
        , 8:  [ {class: "vs", text: "Owe no one anything, except to love one another; for he who loves his neighbor has fulfilled the law."} ]
        , 9:  [ {class: "vs", text: "For the commandments, “You shall not commit adultery,” “You shall not murder,” “You shall not steal,” “You shall not covet,” and whatever other commandments there are, are all summed up in this saying, namely, “You shall love your neighbor as yourself.”"} ]
        , 10: [ {class: "vs", text: "Love doesn’t harm a neighbor. Love therefore is the fulfillment of the law."} ]
        , 11: [ {class: "vs", text: "Do this, knowing the time, that it is already time for you to awaken out of sleep, for salvation is now nearer to us than when we first believed."} ]
        , 12: [ {class: "vs", text: "The night is far gone, and the day is near. Let’s therefore throw off the deeds of darkness, and let’s put on the armor of light."} ]
        , 13: [ {class: "vs", text: "Let’s walk properly, as in the day; not in reveling and drunkenness, not in sexual promiscuity and lustful acts, and not in strife and jealousy."} ]
        , 14: [ {class: "vs", text: "But put on the Lord Jesus Christ, and make no provision for the flesh, for its lusts."} ]
        }
  , 14: { 1:  [ {class: "vs", text: "Now accept one who is weak in faith, but not for disputes over opinions."} ]
        , 2:  [ {class: "vs", text: "One man has faith to eat all things, but he who is weak eats only vegetables."} ]
        , 3:  [ {class: "vs", text: "Don’t let him who eats despise him who doesn’t eat. Don’t let him who doesn’t eat judge him who eats, for God has accepted him."} ]
        , 4:  [ {class: "vs", text: "Who are you who judge another’s servant? To his own lord he stands or falls. Yes, he will be made to stand, for God has power to make him stand."} ]
        , 5:  [ {class: "vs", text: "One man esteems one day as more important. Another esteems every day alike. Let each man be fully assured in his own mind."} ]
        , 6:  [ {class: "vs", text: "He who observes the day, observes it to the Lord; and he who does not observe the day, to the Lord he does not observe it. He who eats, eats to the Lord, for he gives God thanks. He who doesn’t eat, to the Lord he doesn’t eat, and gives God thanks."} ]
        , 7:  [ {class: "vs", text: "For none of us lives to himself, and none dies to himself."} ]
        , 8:  [ {class: "vs", text: "For if we live, we live to the Lord. Or if we die, we die to the Lord. If therefore we live or die, we are the Lord’s."} ]
        , 9:  [ {class: "vs", text: "For to this end Christ died, rose, and lived again, that he might be Lord of both the dead and the living."} ]
        , 10: [ {class: "vs", text: "But you, why do you judge your brother? Or you again, why do you despise your brother? For we will all stand before the judgment seat of Christ."} ]
        , 11: [ {class: "endpara", text: "For it is written,"}
              , {class: "q", text: "“‘As I live,’ says the Lord, ‘to me every knee will bow."}
              , {class: "q2", text: "Every tongue will confess to God.’”"}
              ]
        , 12: [ {class: "vs", text: "So then each one of us will give account of himself to God."} ]
        , 13: [ {class: "vs", text: "Therefore let’s not judge one another any more, but judge this rather, that no man put a stumbling block in his brother’s way, or an occasion for falling."} ]
        , 14: [ {class: "vs", text: "I know, and am persuaded in the Lord Jesus, that nothing is unclean of itself; except that to him who considers anything to be unclean, to him it is unclean."} ]
        , 15: [ {class: "vs", text: "Yet if because of food your brother is grieved, you walk no longer in love. Don’t destroy with your food him for whom Christ died."} ]
        , 16: [ {class: "vs", text: "Then don’t let your good be slandered,"} ]
        , 17: [ {class: "vs", text: "for God’s Kingdom is not eating and drinking, but righteousness, peace, and joy in the Holy Spirit."} ]
        , 18: [ {class: "vs", text: "For he who serves Christ in these things is acceptable to God and approved by men."} ]
        , 19: [ {class: "vs", text: "So then, let’s follow after things which make for peace, and things by which we may build one another up."} ]
        , 20: [ {class: "vs", text: "Don’t overthrow God’s work for food’s sake. All things indeed are clean, however it is evil for that man who creates a stumbling block by eating."} ]
        , 21: [ {class: "vs", text: "It is good to not eat meat, drink wine, nor do anything by which your brother stumbles, is offended, or is made weak."} ]
        , 22: [ {class: "vs", text: "Do you have faith? Have it to yourself before God. Happy is he who doesn’t judge himself in that which he approves."} ]
        , 23: [ {class: "vs", text: "But he who doubts is condemned if he eats, because it isn’t of faith; and whatever is not of faith is sin."} ]
        , 24: [ {class: "vs", text: "Now to him who is able to establish you according to my Good News and the preaching of Jesus Christ, according to the revelation of the mystery which has been kept secret through long ages,"} ]
        , 25: [ {class: "vs", text: "but now is revealed, and by the Scriptures of the prophets, according to the commandment of the eternal God, is made known for obedience of faith to all the nations;"} ]
        , 26: [ {class: "vs", text: "to the only wise God, through Jesus Christ, to whom be the glory forever! Amen."} ]
        }
  , 15: { 1:  [ {class: "vs", text: "Now we who are strong ought to bear the weaknesses of the weak, and not to please ourselves."} ]
        , 2:  [ {class: "vs", text: "Let each one of us please his neighbor for that which is good, to be building him up."} ]
        , 3:  [ {class: "vs", text: "For even Christ didn’t please himself. But, as it is written, “The reproaches of those who reproached you fell on me.”"} ]
        , 4:  [ {class: "vs", text: "For whatever things were written before were written for our learning, that through perseverance and through encouragement of the Scriptures we might have hope."} ]
        , 5:  [ {class: "vs", text: "Now the God of perseverance and of encouragement grant you to be of the same mind with one another according to Christ Jesus,"} ]
        , 6:  [ {class: "vs", text: "that with one accord you may with one mouth glorify the God and Father of our Lord Jesus Christ."} ]
        , 7:  [ {class: "vs", text: "Therefore accept one another, even as Christ also accepted you, to the glory of God."} ]
        , 8:  [ {class: "vs", text: "Now I say that Christ has been made a servant of the circumcision for the truth of God, that he might confirm the promises given to the fathers,"} ]
        , 9:  [ {class: "endpara", text: "and that the Gentiles might glorify God for his mercy. As it is written,"}
              , {class: "q", text: "“Therefore I will give praise to you among the Gentiles"}
              , {class: "q2", text: "and sing to your name.”"}
              ]
        , 10: [ {class: "endpara", text: "Again he says,"}
              , {class: "q", text: "“Rejoice, you Gentiles, with his people.”"}
              ]
        , 11: [ {class: "endpara", text: "Again,"}
              , {class: "q", text: "“Praise the Lord, all you Gentiles!"}
              , {class: "q2", text: "Let all the peoples praise him.”"}
              ]
        , 12: [ {class: "endpara", text: "Again, Isaiah says,"}
              , {class: "q", text: "“There will be the root of Jesse,"}
              , {class: "q2", text: "he who arises to rule over the Gentiles;"}
              , {class: "q2", text: "in him the Gentiles will hope.”"}
              ]
        , 13: [ {class: "vs", text: "Now may the God of hope fill you with all joy and peace in believing, that you may abound in hope, in the power of the Holy Spirit."} ]
        , 14: [ {class: "vs", text: "I myself am also persuaded about you, my brothers, that you yourselves are full of goodness, filled with all knowledge, able also to admonish others."} ]
        , 15: [ {class: "vs", text: "But I write the more boldly to you in part, as reminding you, because of the grace that was given to me by God,"} ]
        , 16: [ {class: "vs", text: "that I should be a servant of Christ Jesus to the Gentiles, serving as a priest of the Good News of God, that the offering up of the Gentiles might be made acceptable, sanctified by the Holy Spirit."} ]
        , 17: [ {class: "vs", text: "I have therefore my boasting in Christ Jesus in things pertaining to God."} ]
        , 18: [ {class: "vs", text: "For I will not dare to speak of any things except those which Christ worked through me, for the obedience of the Gentiles, by word and deed,"} ]
        , 19: [ {class: "vs", text: "in the power of signs and wonders, in the power of God’s Spirit; so that from Jerusalem, and around as far as to Illyricum, I have fully preached the Good News of Christ;"} ]
        , 20: [ {class: "vs", text: "yes, making it my aim to preach the Good News, not where Christ was already named, that I might not build on another’s foundation."} ]
        , 21: [ {class: "endpara", text: "But, as it is written,"}
              , {class: "q", text: "“They will see, to whom no news of him came."}
              , {class: "q2", text: "They who haven’t heard will understand.”"}
              ]
        , 22: [ {class: "vs", text: "Therefore also I was hindered these many times from coming to you,"} ]
        , 23: [ {class: "vs", text: "but now, no longer having any place in these regions, and having these many years a longing to come to you,"} ]
        , 24: [ {class: "vs", text: "whenever I travel to Spain, I will come to you. For I hope to see you on my journey, and to be helped on my way there by you, if first I may enjoy your company for a while."} ]
        , 25: [ {class: "vs", text: "But now, I say, I am going to Jerusalem, serving the saints."} ]
        , 26: [ {class: "vs", text: "For it has been the good pleasure of Macedonia and Achaia to make a certain contribution for the poor among the saints who are at Jerusalem."} ]
        , 27: [ {class: "vs", text: "Yes, it has been their good pleasure, and they are their debtors. For if the Gentiles have been made partakers of their spiritual things, they owe it to them also to serve them in fleshly things."} ]
        , 28: [ {class: "vs", text: "When therefore I have accomplished this, and have sealed to them this fruit, I will go on by way of you to Spain."} ]
        , 29: [ {class: "vs", text: "I know that when I come to you, I will come in the fullness of the blessing of the Good News of Christ."} ]
        , 30: [ {class: "vs", text: "Now I beg you, brothers, by our Lord Jesus Christ and by the love of the Spirit, that you strive together with me in your prayers to God for me,"} ]
        , 31: [ {class: "vs", text: "that I may be delivered from those who are disobedient in Judea, and that my service which I have for Jerusalem may be acceptable to the saints,"} ]
        , 32: [ {class: "vs", text: "that I may come to you in joy through the will of God, and together with you, find rest."} ]
        , 33: [ {class: "vs", text: "Now the God of peace be with you all. Amen."} ]
        }
  , 16: { 1:  [ {class: "vs", text: "I commend to you Phoebe, our sister, who is a servant of the assembly that is at Cenchreae,"} ]
        , 2:  [ {class: "vs", text: "that you receive her in the Lord, in a way worthy of the saints, and that you assist her in whatever matter she may need from you, for she herself also has been a helper of many, and of my own self."} ]
        , 3:  [ {class: "vs", text: "Greet Prisca and Aquila, my fellow workers in Christ Jesus,"} ]
        , 4:  [ {class: "vs", text: "who risked their own necks for my life, to whom not only I give thanks, but also all the assemblies of the Gentiles."} ]
        , 5:  [ {class: "vs", text: "Greet the assembly that is in their house. Greet Epaenetus, my beloved, who is the first fruits of Achaia to Christ."} ]
        , 6:  [ {class: "vs", text: "Greet Mary, who labored much for us."} ]
        , 7:  [ {class: "vs", text: "Greet Andronicus and Junia, my relatives and my fellow prisoners, who are notable among the apostles, who were also in Christ before me."} ]
        , 8:  [ {class: "vs", text: "Greet Amplias, my beloved in the Lord."} ]
        , 9:  [ {class: "vs", text: "Greet Urbanus, our fellow worker in Christ, and Stachys, my beloved."} ]
        , 10: [ {class: "vs", text: "Greet Apelles, the approved in Christ. Greet those who are of the household of Aristobulus."} ]
        , 11: [ {class: "vs", text: "Greet Herodion, my kinsman. Greet them of the household of Narcissus, who are in the Lord."} ]
        , 12: [ {class: "vs", text: "Greet Tryphaena and Tryphosa, who labor in the Lord. Greet Persis, the beloved, who labored much in the Lord."} ]
        , 13: [ {class: "vs", text: "Greet Rufus, the chosen in the Lord, and his mother and mine."} ]
        , 14: [ {class: "vs", text: "Greet Asyncritus, Phlegon, Hermes, Patrobas, Hermas, and the brothers who are with them."} ]
        , 15: [ {class: "vs", text: "Greet Philologus and Julia, Nereus and his sister, and Olympas, and all the saints who are with them."} ]
        , 16: [ {class: "vs", text: "Greet one another with a holy kiss. The assemblies of Christ greet you."} ]
        , 17: [ {class: "vs", text: "Now I beg you, brothers, look out for those who are causing the divisions and occasions of stumbling, contrary to the doctrine which you learned, and turn away from them."} ]
        , 18: [ {class: "vs", text: "For those who are such don’t serve our Lord, Jesus Christ, but their own belly; and by their smooth and flattering speech, they deceive the hearts of the innocent."} ]
        , 19: [ {class: "vs", text: "For your obedience has become known to all. I rejoice therefore over you. But I desire to have you wise in that which is good, but innocent in that which is evil."} ]
        , 20: [ {class: "vs", text: "And the God of peace will quickly crush Satan under your feet.</p><p> The grace of our Lord Jesus Christ be with you."} ]
        , 21: [ {class: "vs", text: "Timothy, my fellow worker, greets you, as do Lucius, Jason, and Sosipater, my relatives."} ]
        , 22: [ {class: "vs", text: "I, Tertius, who write the letter, greet you in the Lord."} ]
        , 23: [ {class: "vs", text: "Gaius, my host and host of the whole assembly, greets you. Erastus, the treasurer of the city, greets you, as does Quartus, the brother."} ]
        , 24: [ {class: "vs", text: "The grace of our Lord Jesus Christ be with you all! Amen."} ]
        }
  , 2:  { 1:  [ {class: "vs", text: "Therefore you are without excuse, O man, whoever you are who judge. For in that which you judge another, you condemn yourself. For you who judge practice the same things."} ]
        , 2:  [ {class: "vs", text: "We know that the judgment of God is according to truth against those who practice such things."} ]
        , 3:  [ {class: "vs", text: "Do you think this, O man who judges those who practice such things, and do the same, that you will escape the judgment of God?"} ]
        , 4:  [ {class: "vs", text: "Or do you despise the riches of his goodness, forbearance, and patience, not knowing that the goodness of God leads you to repentance?"} ]
        , 5:  [ {class: "vs", text: "But according to your hardness and unrepentant heart you are treasuring up for yourself wrath in the day of wrath, revelation, and of the righteous judgment of God;"} ]
        , 6:  [ {class: "vs", text: "who “will pay back to everyone according to their works:”"} ]
        , 7:  [ {class: "vs", text: "to those who by perseverance in well-doing seek for glory, honor, and incorruptibility, eternal life;"} ]
        , 8:  [ {class: "vs", text: "but to those who are self-seeking, and don’t obey the truth, but obey unrighteousness, will be wrath, indignation,"} ]
        , 9:  [ {class: "vs", text: "oppression, and anguish on every soul of man who does evil, to the Jew first, and also to the Greek."} ]
        , 10: [ {class: "vs", text: "But glory, honor, and peace go to every man who does good, to the Jew first, and also to the Greek."} ]
        , 11: [ {class: "vs", text: "For there is no partiality with God."} ]
        , 12: [ {class: "vs", text: "For as many as have sinned without the law will also perish without the law. As many as have sinned under the law will be judged by the law."} ]
        , 13: [ {class: "vs", text: "For it isn’t the hearers of the law who are righteous before God, but the doers of the law will be justified"} ]
        , 14: [ {class: "vs", text: "(for when Gentiles who don’t have the law do by nature the things of the law, these, not having the law, are a law to themselves,"} ]
        , 15: [ {class: "vs", text: "in that they show the work of the law written in their hearts, their conscience testifying with them, and their thoughts among themselves accusing or else excusing them)"} ]
        , 16: [ {class: "vs", text: "in the day when God will judge the secrets of men, according to my Good News, by Jesus Christ."} ]
        , 17: [ {class: "vs", text: "Indeed you bear the name of a Jew, rest on the law, glory in God,"} ]
        , 18: [ {class: "vs", text: "know his will, and approve the things that are excellent, being instructed out of the law,"} ]
        , 19: [ {class: "vs", text: "and are confident that you yourself are a guide of the blind, a light to those who are in darkness,"} ]
        , 20: [ {class: "vs", text: "a corrector of the foolish, a teacher of babies, having in the law the form of knowledge and of the truth."} ]
        , 21: [ {class: "vs", text: "You therefore who teach another, don’t you teach yourself? You who preach that a man shouldn’t steal, do you steal?"} ]
        , 22: [ {class: "vs", text: "You who say a man shouldn’t commit adultery, do you commit adultery? You who abhor idols, do you rob temples?"} ]
        , 23: [ {class: "vs", text: "You who glory in the law, do you dishonor God by disobeying the law?"} ]
        , 24: [ {class: "vs", text: "For “the name of God is blasphemed among the Gentiles because of you,” just as it is written."} ]
        , 25: [ {class: "vs", text: "For circumcision indeed profits, if you are a doer of the law, but if you are a transgressor of the law, your circumcision has become uncircumcision."} ]
        , 26: [ {class: "vs", text: "If therefore the uncircumcised keep the ordinances of the law, won’t his uncircumcision be accounted as circumcision?"} ]
        , 27: [ {class: "vs", text: "Won’t the uncircumcision which is by nature, if it fulfills the law, judge you, who with the letter and circumcision are a transgressor of the law?"} ]
        , 28: [ {class: "vs", text: "For he is not a Jew who is one outwardly, neither is that circumcision which is outward in the flesh;"} ]
        , 29: [ {class: "vs", text: "but he is a Jew who is one inwardly, and circumcision is that of the heart, in the spirit not in the letter; whose praise is not from men, but from God."} ]
        }
  , 3:  { 1:  [ {class: "vs", text: "Then what advantage does the Jew have? Or what is the profit of circumcision?"} ]
        , 2:  [ {class: "vs", text: "Much in every way! Because first of all, they were entrusted with the revelations of God."} ]
        , 3:  [ {class: "vs", text: "For what if some were without faith? Will their lack of faith nullify the faithfulness of God?"} ]
        , 4:  [ {class: "endpara", text: "May it never be! Yes, let God be found true, but every man a liar. As it is written,"}
              , {class: "q", text: "“that you might be justified in your words,"}
              , {class: "q2", text: "and might prevail when you come into judgment.”"}
              ]
        , 5:  [ {class: "vs", text: "But if our unrighteousness commends the righteousness of God, what will we say? Is God unrighteous who inflicts wrath? I speak like men do."} ]
        , 6:  [ {class: "vs", text: "May it never be! For then how will God judge the world?"} ]
        , 7:  [ {class: "vs", text: "For if the truth of God through my lie abounded to his glory, why am I also still judged as a sinner?"} ]
        , 8:  [ {class: "vs", text: "Why not (as we are slanderously reported, and as some affirm that we say), “Let’s do evil, that good may come?” Those who say so are justly condemned."} ]
        , 9:  [ {class: "vs", text: "What then? Are we better than they? No, in no way. For we previously warned both Jews and Greeks that they are all under sin."} ]
        , 10: [ {class: "endpara", text: "As it is written,"}
              , {class: "q", text: "“There is no one righteous;"}
              , {class: "q2", text: "no, not one."}
              ]
        , 11: [ {class: "q", text: "There is no one who understands."}
              , {class: "q2", text: "There is no one who seeks after God."}
              ]
        , 12: [ {class: "q", text: "They have all turned away."}
              , {class: "q2", text: "They have together become unprofitable."}
              , {class: "q", text: "There is no one who does good,"}
              , {class: "q2", text: "no, not so much as one.”"}
              ]
        , 13: [ {class: "q", text: "“Their throat is an open tomb."}
              , {class: "q2", text: "With their tongues they have used deceit.”"}
              , {class: "q", text: "“The poison of vipers is under their lips.”"}
              ]
        , 14: [ {class: "q2", text: "“Their mouth is full of cursing and bitterness.”"} ]
        , 15: [ {class: "q", text: "“Their feet are swift to shed blood."} ]
        , 16: [ {class: "q2", text: "</span> Destruction and misery are in their ways."} ]
        , 17: [ {class: "q2", text: "</span> The way of peace, they haven’t known.”"} ]
        , 18: [ {class: "q", text: "“There is no fear of God before their eyes.”"} ]
        , 19: [ {class: "vs", text: "Now we know that whatever things the law says, it speaks to those who are under the law, that every mouth may be closed, and all the world may be brought under the judgment of God."} ]
        , 20: [ {class: "vs", text: "Because by the works of the law, no flesh will be justified in his sight; for through the law comes the knowledge of sin."} ]
        , 21: [ {class: "vs", text: "But now apart from the law, a righteousness of God has been revealed, being testified by the law and the prophets;"} ]
        , 22: [ {class: "vs", text: "even the righteousness of God through faith in Jesus Christ to all and on all those who believe. For there is no distinction,"} ]
        , 23: [ {class: "vs", text: "for all have sinned, and fall short of the glory of God;"} ]
        , 24: [ {class: "vs", text: "being justified freely by his grace through the redemption that is in Christ Jesus;"} ]
        , 25: [ {class: "vs", text: "whom God sent to be an atoning sacrifice, through faith in his blood, for a demonstration of his righteousness through the passing over of prior sins, in God’s forbearance;"} ]
        , 26: [ {class: "vs", text: "to demonstrate his righteousness at this present time; that he might himself be just, and the justifier of him who has faith in Jesus."} ]
        , 27: [ {class: "vs", text: "Where then is the boasting? It is excluded. By what kind of law? Of works? No, but by a law of faith."} ]
        , 28: [ {class: "vs", text: "We maintain therefore that a man is justified by faith apart from the works of the law."} ]
        , 29: [ {class: "vs", text: "Or is God the God of Jews only? Isn’t he the God of Gentiles also? Yes, of Gentiles also,"} ]
        , 30: [ {class: "vs", text: "since indeed there is one God who will justify the circumcised by faith, and the uncircumcised through faith."} ]
        , 31: [ {class: "vs", text: "Do we then nullify the law through faith? May it never be! No, we establish the law."} ]
        }
  , 4:  { 1:  [ {class: "vs", text: "What then will we say that Abraham, our forefather, has found according to the flesh?"} ]
        , 2:  [ {class: "vs", text: "For if Abraham was justified by works, he has something to boast about, but not toward God."} ]
        , 3:  [ {class: "vs", text: "For what does the Scripture say? “Abraham believed God, and it was accounted to him for righteousness.”"} ]
        , 4:  [ {class: "vs", text: "Now to him who works, the reward is not counted as grace, but as something owed."} ]
        , 5:  [ {class: "vs", text: "But to him who doesn’t work, but believes in him who justifies the ungodly, his faith is accounted for righteousness."} ]
        , 6:  [ {class: "vs", text: "Even as David also pronounces blessing on the man to whom God counts righteousness apart from works,"} ]
        , 7:  [ {class: "q", text: "“Blessed are they whose iniquities are forgiven,"}
              , {class: "q2", text: "whose sins are covered."}
              ]
        , 8:  [ {class: "q", text: "Blessed is the man whom the Lord will by no means charge with sin.”"} ]
        , 9:  [ {class: "vs", text: "Is this blessing then pronounced on the circumcised, or on the uncircumcised also? For we say that faith was accounted to Abraham for righteousness."} ]
        , 10: [ {class: "vs", text: "How then was it counted? When he was in circumcision, or in uncircumcision? Not in circumcision, but in uncircumcision."} ]
        , 11: [ {class: "vs", text: "He received the sign of circumcision, a seal of the righteousness of the faith which he had while he was in uncircumcision, that he might be the father of all those who believe, though they might be in uncircumcision, that righteousness might also be accounted to them."} ]
        , 12: [ {class: "vs", text: "He is the father of circumcision to those who not only are of the circumcision, but who also walk in the steps of that faith of our father Abraham, which he had in uncircumcision."} ]
        , 13: [ {class: "vs", text: "For the promise to Abraham and to his offspring that he should be heir of the world wasn’t through the law, but through the righteousness of faith."} ]
        , 14: [ {class: "vs", text: "For if those who are of the law are heirs, faith is made void, and the promise is made of no effect."} ]
        , 15: [ {class: "vs", text: "For the law produces wrath, for where there is no law, neither is there disobedience."} ]
        , 16: [ {class: "vs", text: "For this cause it is of faith, that it may be according to grace, to the end that the promise may be sure to all the offspring, not to that only which is of the law, but to that also which is of the faith of Abraham, who is the father of us all."} ]
        , 17: [ {class: "vs", text: "As it is written, “I have made you a father of many nations.” This is in the presence of him whom he believed: God, who gives life to the dead, and calls the things that are not, as though they were."} ]
        , 18: [ {class: "vs", text: "Besides hope, Abraham in hope believed, to the end that he might become a father of many nations, according to that which had been spoken, “So will your offspring be.”"} ]
        , 19: [ {class: "vs", text: "Without being weakened in faith, he didn’t consider his own body, already having been worn out, (he being about a hundred years old), and the deadness of Sarah’s womb."} ]
        , 20: [ {class: "vs", text: "Yet, looking to the promise of God, he didn’t waver through unbelief, but grew strong through faith, giving glory to God,"} ]
        , 21: [ {class: "vs", text: "and being fully assured that what he had promised, he was also able to perform."} ]
        , 22: [ {class: "vs", text: "Therefore it also was “credited to him for righteousness.”"} ]
        , 23: [ {class: "vs", text: "Now it was not written that it was accounted to him for his sake alone,"} ]
        , 24: [ {class: "vs", text: "but for our sake also, to whom it will be accounted, who believe in him who raised Jesus, our Lord, from the dead,"} ]
        , 25: [ {class: "vs", text: "who was delivered up for our trespasses, and was raised for our justification."} ]
        }
  , 5:  { 1:  [ {class: "vs", text: "Being therefore justified by faith, we have peace with God through our Lord Jesus Christ;"} ]
        , 2:  [ {class: "vs", text: "through whom we also have our access by faith into this grace in which we stand. We rejoice in hope of the glory of God."} ]
        , 3:  [ {class: "vs", text: "Not only this, but we also rejoice in our sufferings, knowing that suffering produces perseverance;"} ]
        , 4:  [ {class: "vs", text: "and perseverance, proven character; and proven character, hope:"} ]
        , 5:  [ {class: "vs", text: "and hope doesn’t disappoint us, because God’s love has been poured into our hearts through the Holy Spirit who was given to us."} ]
        , 6:  [ {class: "vs", text: "For while we were yet weak, at the right time Christ died for the ungodly."} ]
        , 7:  [ {class: "vs", text: "For one will hardly die for a righteous man. Yet perhaps for a righteous person someone would even dare to die."} ]
        , 8:  [ {class: "vs", text: "But God commends his own love toward us, in that while we were yet sinners, Christ died for us."} ]
        , 9:  [ {class: "vs", text: "Much more then, being now justified by his blood, we will be saved from God’s wrath through him."} ]
        , 10: [ {class: "vs", text: "For if while we were enemies, we were reconciled to God through the death of his Son, much more, being reconciled, we will be saved by his life."} ]
        , 11: [ {class: "vs", text: "Not only so, but we also rejoice in God through our Lord Jesus Christ, through whom we have now received the reconciliation."} ]
        , 12: [ {class: "vs", text: "Therefore as sin entered into the world through one man, and death through sin; so death passed to all men, because all sinned."} ]
        , 13: [ {class: "vs", text: "For until the law, sin was in the world; but sin is not charged when there is no law."} ]
        , 14: [ {class: "vs", text: "Nevertheless death reigned from Adam until Moses, even over those whose sins weren’t like Adam’s disobedience, who is a foreshadowing of him who was to come."} ]
        , 15: [ {class: "vs", text: "But the free gift isn’t like the trespass. For if by the trespass of the one the many died, much more did the grace of God, and the gift by the grace of the one man, Jesus Christ, abound to the many."} ]
        , 16: [ {class: "vs", text: "The gift is not as through one who sinned; for the judgment came by one to condemnation, but the free gift came of many trespasses to justification."} ]
        , 17: [ {class: "vs", text: "For if by the trespass of the one, death reigned through the one; so much more will those who receive the abundance of grace and of the gift of righteousness reign in life through the one, Jesus Christ."} ]
        , 18: [ {class: "vs", text: "So then as through one trespass, all men were condemned; even so through one act of righteousness, all men were justified to life."} ]
        , 19: [ {class: "vs", text: "For as through the one man’s disobedience many were made sinners, even so through the obedience of the one, many will be made righteous."} ]
        , 20: [ {class: "vs", text: "The law came in that the trespass might abound; but where sin abounded, grace abounded more exceedingly;"} ]
        , 21: [ {class: "vs", text: "that as sin reigned in death, even so grace might reign through righteousness to eternal life through Jesus Christ our Lord."} ]
        }
  , 6:  { 1:  [ {class: "vs", text: "What shall we say then? Shall we continue in sin, that grace may abound?"} ]
        , 2:  [ {class: "vs", text: "May it never be! We who died to sin, how could we live in it any longer?"} ]
        , 3:  [ {class: "vs", text: "Or don’t you know that all we who were baptized into Christ Jesus were baptized into his death?"} ]
        , 4:  [ {class: "vs", text: "We were buried therefore with him through baptism into death, that just as Christ was raised from the dead through the glory of the Father, so we also might walk in newness of life."} ]
        , 5:  [ {class: "vs", text: "For if we have become united with him in the likeness of his death, we will also be part of his resurrection;"} ]
        , 6:  [ {class: "vs", text: "knowing this, that our old man was crucified with him, that the body of sin might be done away with, so that we would no longer be in bondage to sin."} ]
        , 7:  [ {class: "vs", text: "For he who has died has been freed from sin."} ]
        , 8:  [ {class: "vs", text: "But if we died with Christ, we believe that we will also live with him;"} ]
        , 9:  [ {class: "vs", text: "knowing that Christ, being raised from the dead, dies no more. Death no longer has dominion over him!"} ]
        , 10: [ {class: "vs", text: "For the death that he died, he died to sin one time; but the life that he lives, he lives to God."} ]
        , 11: [ {class: "vs", text: "Thus consider yourselves also to be dead to sin, but alive to God in Christ Jesus our Lord."} ]
        , 12: [ {class: "vs", text: "Therefore don’t let sin reign in your mortal body, that you should obey it in its lusts."} ]
        , 13: [ {class: "vs", text: "Also, do not present your members to sin as instruments of unrighteousness, but present yourselves to God as alive from the dead, and your members as instruments of righteousness to God."} ]
        , 14: [ {class: "vs", text: "For sin will not have dominion over you. For you are not under law, but under grace."} ]
        , 15: [ {class: "vs", text: "What then? Shall we sin, because we are not under law, but under grace? May it never be!"} ]
        , 16: [ {class: "vs", text: "Don’t you know that when you present yourselves as servants and obey someone, you are the servants of whomever you obey; whether of sin to death, or of obedience to righteousness?"} ]
        , 17: [ {class: "vs", text: "But thanks be to God, that, whereas you were bondservants of sin, you became obedient from the heart to that form of teaching to which you were delivered."} ]
        , 18: [ {class: "vs", text: "Being made free from sin, you became bondservants of righteousness."} ]
        , 19: [ {class: "vs", text: "I speak in human terms because of the weakness of your flesh, for as you presented your members as servants to uncleanness and to wickedness upon wickedness, even so now present your members as servants to righteousness for sanctification."} ]
        , 20: [ {class: "vs", text: "For when you were servants of sin, you were free from righteousness."} ]
        , 21: [ {class: "vs", text: "What fruit then did you have at that time in the things of which you are now ashamed? For the end of those things is death."} ]
        , 22: [ {class: "vs", text: "But now, being made free from sin and having become servants of God, you have your fruit of sanctification and the result of eternal life."} ]
        , 23: [ {class: "vs", text: "For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord."} ]
        }
  , 7:  { 1:  [ {class: "vs", text: "Or don’t you know, brothers (for I speak to men who know the law), that the law has dominion over a man for as long as he lives?"} ]
        , 2:  [ {class: "vs", text: "For the woman that has a husband is bound by law to the husband while he lives, but if the husband dies, she is discharged from the law of the husband."} ]
        , 3:  [ {class: "vs", text: "So then if, while the husband lives, she is joined to another man, she would be called an adulteress. But if the husband dies, she is free from the law, so that she is no adulteress, though she is joined to another man."} ]
        , 4:  [ {class: "vs", text: "Therefore, my brothers, you also were made dead to the law through the body of Christ, that you would be joined to another, to him who was raised from the dead, that we might produce fruit to God."} ]
        , 5:  [ {class: "vs", text: "For when we were in the flesh, the sinful passions which were through the law worked in our members to bring out fruit to death."} ]
        , 6:  [ {class: "vs", text: "But now we have been discharged from the law, having died to that in which we were held; so that we serve in newness of the spirit, and not in oldness of the letter."} ]
        , 7:  [ {class: "vs", text: "What shall we say then? Is the law sin? May it never be! However, I wouldn’t have known sin, except through the law. For I wouldn’t have known coveting, unless the law had said, “You shall not covet.”"} ]
        , 8:  [ {class: "vs", text: "But sin, finding occasion through the commandment, produced in me all kinds of coveting. For apart from the law, sin is dead."} ]
        , 9:  [ {class: "vs", text: "I was alive apart from the law once, but when the commandment came, sin revived, and I died."} ]
        , 10: [ {class: "vs", text: "The commandment which was for life, this I found to be for death;"} ]
        , 11: [ {class: "vs", text: "for sin, finding occasion through the commandment, deceived me, and through it killed me."} ]
        , 12: [ {class: "vs", text: "Therefore the law indeed is holy, and the commandment holy, and righteous, and good."} ]
        , 13: [ {class: "vs", text: "Did then that which is good become death to me? May it never be! But sin, that it might be shown to be sin, was producing death in me through that which is good; that through the commandment sin might become exceedingly sinful."} ]
        , 14: [ {class: "vs", text: "For we know that the law is spiritual, but I am fleshly, sold under sin."} ]
        , 15: [ {class: "vs", text: "For I don’t know what I am doing. For I don’t practice what I desire to do; but what I hate, that I do."} ]
        , 16: [ {class: "vs", text: "But if what I don’t desire, that I do, I consent to the law that it is good."} ]
        , 17: [ {class: "vs", text: "So now it is no more I that do it, but sin which dwells in me."} ]
        , 18: [ {class: "vs", text: "For I know that in me, that is, in my flesh, dwells no good thing. For desire is present with me, but I don’t find it doing that which is good."} ]
        , 19: [ {class: "vs", text: "For the good which I desire, I don’t do; but the evil which I don’t desire, that I practice."} ]
        , 20: [ {class: "vs", text: "But if what I don’t desire, that I do, it is no more I that do it, but sin which dwells in me."} ]
        , 21: [ {class: "vs", text: "I find then the law that, to me, while I desire to do good, evil is present."} ]
        , 22: [ {class: "vs", text: "For I delight in God’s law after the inward man,"} ]
        , 23: [ {class: "vs", text: "but I see a different law in my members, warring against the law of my mind, and bringing me into captivity under the law of sin which is in my members."} ]
        , 24: [ {class: "vs", text: "What a wretched man I am! Who will deliver me out of the body of this death?"} ]
        , 25: [ {class: "vs", text: "I thank God through Jesus Christ, our Lord! So then with the mind, I myself serve God’s law, but with the flesh, sin’s law."} ]
        }
  , 8:  { 1:  [ {class: "vs", text: "There is therefore now no condemnation to those who are in Christ Jesus, who don’t walk according to the flesh, but according to the Spirit."} ]
        , 2:  [ {class: "vs", text: "For the law of the Spirit of life in Christ Jesus made me free from the law of sin and of death."} ]
        , 3:  [ {class: "vs", text: "For what the law couldn’t do, in that it was weak through the flesh, God did, sending his own Son in the likeness of sinful flesh and for sin, he condemned sin in the flesh;"} ]
        , 4:  [ {class: "vs", text: "that the ordinance of the law might be fulfilled in us, who walk not after the flesh, but after the Spirit."} ]
        , 5:  [ {class: "vs", text: "For those who live according to the flesh set their minds on the things of the flesh, but those who live according to the Spirit, the things of the Spirit."} ]
        , 6:  [ {class: "vs", text: "For the mind of the flesh is death, but the mind of the Spirit is life and peace;"} ]
        , 7:  [ {class: "vs", text: "because the mind of the flesh is hostile toward God; for it is not subject to God’s law, neither indeed can it be."} ]
        , 8:  [ {class: "vs", text: "Those who are in the flesh can’t please God."} ]
        , 9:  [ {class: "vs", text: "But you are not in the flesh but in the Spirit, if it is so that the Spirit of God dwells in you. But if any man doesn’t have the Spirit of Christ, he is not his."} ]
        , 10: [ {class: "vs", text: "If Christ is in you, the body is dead because of sin, but the spirit is alive because of righteousness."} ]
        , 11: [ {class: "vs", text: "But if the Spirit of him who raised up Jesus from the dead dwells in you, he who raised up Christ Jesus from the dead will also give life to your mortal bodies through his Spirit who dwells in you."} ]
        , 12: [ {class: "vs", text: "So then, brothers, we are debtors, not to the flesh, to live after the flesh."} ]
        , 13: [ {class: "vs", text: "For if you live after the flesh, you must die; but if by the Spirit you put to death the deeds of the body, you will live."} ]
        , 14: [ {class: "vs", text: "For as many as are led by the Spirit of God, these are children of God."} ]
        , 15: [ {class: "vs", text: "For you didn’t receive the spirit of bondage again to fear, but you received the Spirit of adoption, by whom we cry, “Abba! Father!”"} ]
        , 16: [ {class: "vs", text: "The Spirit himself testifies with our spirit that we are children of God;"} ]
        , 17: [ {class: "vs", text: "and if children, then heirs: heirs of God and joint heirs with Christ, if indeed we suffer with him, that we may also be glorified with him."} ]
        , 18: [ {class: "vs", text: "For I consider that the sufferings of this present time are not worthy to be compared with the glory which will be revealed toward us."} ]
        , 19: [ {class: "vs", text: "For the creation waits with eager expectation for the children of God to be revealed."} ]
        , 20: [ {class: "vs", text: "For the creation was subjected to vanity, not of its own will, but because of him who subjected it, in hope"} ]
        , 21: [ {class: "vs", text: "that the creation itself also will be delivered from the bondage of decay into the liberty of the glory of the children of God."} ]
        , 22: [ {class: "vs", text: "For we know that the whole creation groans and travails in pain together until now."} ]
        , 23: [ {class: "vs", text: "Not only so, but ourselves also, who have the first fruits of the Spirit, even we ourselves groan within ourselves, waiting for adoption, the redemption of our body."} ]
        , 24: [ {class: "vs", text: "For we were saved in hope, but hope that is seen is not hope. For who hopes for that which he sees?"} ]
        , 25: [ {class: "vs", text: "But if we hope for that which we don’t see, we wait for it with patience."} ]
        , 26: [ {class: "vs", text: "In the same way, the Spirit also helps our weaknesses, for we don’t know how to pray as we ought. But the Spirit himself makes intercession for us with groanings which can’t be uttered."} ]
        , 27: [ {class: "vs", text: "He who searches the hearts knows what is on the Spirit’s mind, because he makes intercession for the saints according to God."} ]
        , 28: [ {class: "vs", text: "We know that all things work together for good for those who love God, for those who are called according to his purpose."} ]
        , 29: [ {class: "vs", text: "For whom he foreknew, he also predestined to be conformed to the image of his Son, that he might be the firstborn among many brothers."} ]
        , 30: [ {class: "vs", text: "Whom he predestined, those he also called. Whom he called, those he also justified. Whom he justified, those he also glorified."} ]
        , 31: [ {class: "vs", text: "What then shall we say about these things? If God is for us, who can be against us?"} ]
        , 32: [ {class: "vs", text: "He who didn’t spare his own Son, but delivered him up for us all, how would he not also with him freely give us all things?"} ]
        , 33: [ {class: "vs", text: "Who could bring a charge against God’s chosen ones? It is God who justifies."} ]
        , 34: [ {class: "vs", text: "Who is he who condemns? It is Christ who died, yes rather, who was raised from the dead, who is at the right hand of God, who also makes intercession for us."} ]
        , 35: [ {class: "vs", text: "Who shall separate us from the love of Christ? Could oppression, or anguish, or persecution, or famine, or nakedness, or peril, or sword?"} ]
        , 36: [ {class: "endpara", text: "Even as it is written,"}
              , {class: "q", text: "“For your sake we are killed all day long."}
              , {class: "q2", text: "We were accounted as sheep for the slaughter.”"}
              ]
        , 37: [ {class: "vs", text: "No, in all these things, we are more than conquerors through him who loved us."} ]
        , 38: [ {class: "vs", text: "For I am persuaded that neither death, nor life, nor angels, nor principalities, nor things present, nor things to come, nor powers,"} ]
        , 39: [ {class: "vs", text: "nor height, nor depth, nor any other created thing will be able to separate us from God’s love which is in Christ Jesus our Lord."} ]
        }
  , 9:  { 1:  [ {class: "vs", text: "I tell the truth in Christ. I am not lying, my conscience testifying with me in the Holy Spirit"} ]
        , 2:  [ {class: "vs", text: "that I have great sorrow and unceasing pain in my heart."} ]
        , 3:  [ {class: "vs", text: "For I could wish that I myself were accursed from Christ for my brothers’ sake, my relatives according to the flesh"} ]
        , 4:  [ {class: "vs", text: "who are Israelites; whose is the adoption, the glory, the covenants, the giving of the law, the service, and the promises;"} ]
        , 5:  [ {class: "vs", text: "of whom are the fathers, and from whom is Christ as concerning the flesh, who is over all, God, blessed forever. Amen."} ]
        , 6:  [ {class: "vs", text: "But it is not as though the word of God has come to nothing. For they are not all Israel that are of Israel."} ]
        , 7:  [ {class: "vs", text: "Neither, because they are Abraham’s offspring, are they all children. But, “your offspring will be accounted as from Isaac.”"} ]
        , 8:  [ {class: "vs", text: "That is, it is not the children of the flesh who are children of God, but the children of the promise are counted as heirs."} ]
        , 9:  [ {class: "vs", text: "For this is a word of promise, “At the appointed time I will come, and Sarah will have a son.”"} ]
        , 10: [ {class: "vs", text: "Not only so, but Rebekah also conceived by one, by our father Isaac."} ]
        , 11: [ {class: "vs", text: "For being not yet born, neither having done anything good or bad, that the purpose of God according to election might stand, not of works, but of him who calls,"} ]
        , 12: [ {class: "vs", text: "it was said to her, “The elder will serve the younger.”"} ]
        , 13: [ {class: "vs", text: "Even as it is written, “Jacob I loved, but Esau I hated.”"} ]
        , 14: [ {class: "vs", text: "What shall we say then? Is there unrighteousness with God? May it never be!"} ]
        , 15: [ {class: "vs", text: "For he said to Moses, “I will have mercy on whom I have mercy, and I will have compassion on whom I have compassion.”"} ]
        , 16: [ {class: "vs", text: "So then it is not of him who wills, nor of him who runs, but of God who has mercy."} ]
        , 17: [ {class: "vs", text: "For the Scripture says to Pharaoh, “For this very purpose I caused you to be raised up, that I might show in you my power, and that my name might be proclaimed in all the earth.”"} ]
        , 18: [ {class: "vs", text: "So then, he has mercy on whom he desires, and he hardens whom he desires."} ]
        , 19: [ {class: "vs", text: "You will say then to me, “Why does he still find fault? For who withstands his will?”"} ]
        , 20: [ {class: "vs", text: "But indeed, O man, who are you to reply against God? Will the thing formed ask him who formed it, “Why did you make me like this?”"} ]
        , 21: [ {class: "vs", text: "Or hasn’t the potter a right over the clay, from the same lump to make one part a vessel for honor, and another for dishonor?"} ]
        , 22: [ {class: "vs", text: "What if God, willing to show his wrath and to make his power known, endured with much patience vessels of wrath prepared for destruction,"} ]
        , 23: [ {class: "vs", text: "and that he might make known the riches of his glory on vessels of mercy, which he prepared beforehand for glory,"} ]
        , 24: [ {class: "vs", text: "us, whom he also called, not from the Jews only, but also from the Gentiles?"} ]
        , 25: [ {class: "endpara", text: "As he says also in Hosea,"}
              , {class: "q", text: "“I will call them ‘my people,’ which were not my people;"}
              , {class: "q2", text: "and her ‘beloved,’ who was not beloved.”"}
              ]
        , 26: [ {class: "q", text: "“It will be that in the place where it was said to them, ‘You are not my people,’"}
              , {class: "q2", text: "there they will be called ‘children of the living God.’”"}
              ]
        , 27: [ {class: "endpara", text: "Isaiah cries concerning Israel,"}
              , {class: "q", text: "“If the number of the children of Israel are as the sand of the sea,"}
              , {class: "q2", text: "it is the remnant who will be saved;"}
              ]
        , 28: [ {class: "q", text: "for He will finish the work and cut it short in righteousness,"}
              , {class: "q2", text: "because the LORD will make a short work upon the earth.”"}
              ]
        , 29: [ {class: "endpara", text: "As Isaiah has said before,"}
                , {class: "q", text: "“Unless the Lord of Armies had left us a seed,"}
              , {class: "q2", text: "we would have become like Sodom,"}
              , {class: "q2", text: "and would have been made like Gomorrah.”"}
              ]
        , 30: [ {class: "vs", text: "What shall we say then? That the Gentiles, who didn’t follow after righteousness, attained to righteousness, even the righteousness which is of faith;"} ]
        , 31: [ {class: "vs", text: "but Israel, following after a law of righteousness, didn’t arrive at the law of righteousness."} ]
        , 32: [ {class: "vs", text: "Why? Because they didn’t seek it by faith, but as it were by works of the law. They stumbled over the stumbling stone;"} ]
        , 33: [ {class: "endpara", text: "even as it is written,"}
                , {class: "q", text: "“Behold, I lay in Zion a stumbling stone and a rock of offense;"}
              , {class: "q2", text: "and no one who believes in him will be disappointed.”"}
              ]
          }
  }