exports.timothy1 =
  { 1:  { 1:  [ {class: "vs", text: "Paul, an apostle of Jesus Christ according to the commandment of God our Savior and the Lord Jesus Christ our hope;"} ]
        , 2:  [ {class: "vs", text: "to Timothy, my true child in faith: Grace, mercy, and peace, from God our Father and Christ Jesus our Lord."} ]
        , 3:  [ {class: "vs", text: "As I urged you when I was going into Macedonia, stay at Ephesus that you might command certain men not to teach a different doctrine,"} ]
        , 4:  [ {class: "vs", text: "and not to pay attention to myths and endless genealogies, which cause disputes, rather than God’s stewardship, which is in faith—"} ]
        , 5:  [ {class: "vs", text: "but the goal of this command is love, out of a pure heart and a good conscience and sincere faith,"} ]
        , 6:  [ {class: "vs", text: "from which things some, having missed the mark, have turned away to vain talking,"} ]
        , 7:  [ {class: "vs", text: "desiring to be teachers of the law, though they understand neither what they say, nor about what they strongly affirm."} ]
        , 8:  [ {class: "vs", text: "But we know that the law is good, if a person uses it lawfully,"} ]
        , 9:  [ {class: "vs", text: "as knowing this, that law is not made for a righteous person, but for the lawless and insubordinate, for the ungodly and sinners, for the unholy and profane, for murderers of fathers and murderers of mothers, for manslayers,"} ]
        , 10: [ {class: "vs", text: "for the sexually immoral, for homosexuals, for slave-traders, for liars, for perjurers, and for any other thing contrary to the sound doctrine,"} ]
        , 11: [ {class: "vs", text: "according to the Good News of the glory of the blessed God, which was committed to my trust."} ]
        , 12: [ {class: "vs", text: "I thank him who enabled me, Christ Jesus our Lord, because he counted me faithful, appointing me to service;"} ]
        , 13: [ {class: "vs", text: "although I used to be a blasphemer, a persecutor, and insolent. However, I obtained mercy, because I did it ignorantly in unbelief."} ]
        , 14: [ {class: "vs", text: "The grace of our Lord abounded exceedingly with faith and love which is in Christ Jesus."} ]
        , 15: [ {class: "vs", text: "The saying is faithful and worthy of all acceptance, that Christ Jesus came into the world to save sinners, of whom I am chief."} ]
        , 16: [ {class: "vs", text: "However, for this cause I obtained mercy, that in me first, Jesus Christ might display all his patience for an example of those who were going to believe in him for eternal life."} ]
        , 17: [ {class: "vs", text: "Now to the King eternal, immortal, invisible, to God who alone is wise, be honor and glory forever and ever. Amen."} ]
        , 18: [ {class: "vs", text: "I commit this instruction to you, my child Timothy, according to the prophecies which were given to you before, that by them you may wage the good warfare,"} ]
        , 19: [ {class: "vs", text: "holding faith and a good conscience, which some having thrust away made a shipwreck concerning the faith,"} ]
        , 20: [ {class: "vs", text: "of whom are Hymenaeus and Alexander, whom I delivered to Satan, that they might be taught not to blaspheme."} ]
        }
  , 2:  { 1:  [ {class: "vs", text: "I exhort therefore, first of all, that petitions, prayers, intercessions, and givings of thanks be made for all men:"} ]
        , 2:  [ {class: "vs", text: "for kings and all who are in high places, that we may lead a tranquil and quiet life in all godliness and reverence."} ]
        , 3:  [ {class: "vs", text: "For this is good and acceptable in the sight of God our Savior,"} ]
        , 4:  [ {class: "vs", text: "who desires all people to be saved and come to full knowledge of the truth."} ]
        , 5:  [ {class: "vs", text: "For there is one God, and one mediator between God and men, the man Christ Jesus,"} ]
        , 6:  [ {class: "vs", text: "who gave himself as a ransom for all, the testimony in its own times,"} ]
        , 7:  [ {class: "vs", text: "to which I was appointed a preacher and an apostle—I am telling the truth in Christ, not lying—a teacher of the Gentiles in faith and truth."} ]
        , 8:  [ {class: "vs", text: "I desire therefore that the men in every place pray, lifting up holy hands without anger and doubting."} ]
        , 9:  [ {class: "vs", text: "In the same way, that women also adorn themselves in decent clothing, with modesty and propriety, not just with braided hair, gold, pearls, or expensive clothing,"} ]
        , 10: [ {class: "vs", text: "but with good works, which is appropriate for women professing godliness."} ]
        , 11: [ {class: "vs", text: "Let a woman learn in quietness with full submission."} ]
        , 12: [ {class: "vs", text: "But I don’t permit a woman to teach, nor to exercise authority over a man, but to be in quietness."} ]
        , 13: [ {class: "vs", text: "For Adam was formed first, then Eve."} ]
        , 14: [ {class: "vs", text: "Adam wasn’t deceived, but the woman, being deceived, has fallen into disobedience;"} ]
        , 15: [ {class: "vs", text: "but she will be saved through her childbearing, if they continue in faith, love, and sanctification with sobriety."} ]
        }
  , 3:  { 1:  [ {class: "vs", text: "This is a faithful saying: someone who seeks to be an overseer desires a good work."} ]
        , 2:  [ {class: "vs", text: "The overseer therefore must be without reproach, the husband of one wife, temperate, sensible, modest, hospitable, good at teaching;"} ]
        , 3:  [ {class: "vs", text: "not a drinker, not violent, not greedy for money, but gentle, not quarrelsome, not covetous;"} ]
        , 4:  [ {class: "vs", text: "one who rules his own house well, having children in subjection with all reverence;"} ]
        , 5:  [ {class: "vs", text: "(but how could someone who doesn’t know how to rule one’s own house take care of God’s assembly?)"} ]
        , 6:  [ {class: "vs", text: "not a new convert, lest being puffed up he fall into the same condemnation as the devil."} ]
        , 7:  [ {class: "vs", text: "Moreover he must have good testimony from those who are outside, to avoid falling into reproach and the snare of the devil."} ]
        , 8:  [ {class: "vs", text: "Servants, in the same way, must be reverent, not double-tongued, not addicted to much wine, not greedy for money,"} ]
        , 9:  [ {class: "vs", text: "holding the mystery of the faith in a pure conscience."} ]
        , 10: [ {class: "vs", text: "Let them also first be tested; then let them serve if they are blameless."} ]
        , 11: [ {class: "vs", text: "Their wives in the same way must be reverent, not slanderers, temperate, and faithful in all things."} ]
        , 12: [ {class: "vs", text: "Let servants be husbands of one wife, ruling their children and their own houses well."} ]
        , 13: [ {class: "vs", text: "For those who have served well gain for themselves a good standing, and great boldness in the faith which is in Christ Jesus."} ]
        , 14: [ {class: "vs", text: "These things I write to you, hoping to come to you shortly;"} ]
        , 15: [ {class: "vs", text: "but if I wait long, that you may know how men ought to behave themselves in God’s house, which is the assembly of the living God, the pillar and ground of the truth."} ]
        , 16: [ {class: "endpara", text: "Without controversy, the mystery of godliness is great:"}
              , {class: "q", text: "God was revealed in the flesh,"}
              , {class: "q", text: "justified in the spirit,"}
              , {class: "q", text: "seen by angels,"}
              , {class: "q", text: "preached among the nations,"}
              , {class: "q", text: "believed on in the world,"}
              , {class: "q", text: "and received up in glory."}
              ]
        }
  , 4:  { 1:  [ {class: "vs", text: "But the Spirit says expressly that in later times some will fall away from the faith, paying attention to seducing spirits and doctrines of demons,"} ]
        , 2:  [ {class: "vs", text: "through the hypocrisy of men who speak lies, branded in their own conscience as with a hot iron,"} ]
        , 3:  [ {class: "vs", text: "forbidding marriage and commanding to abstain from foods which God created to be received with thanksgiving by those who believe and know the truth."} ]
        , 4:  [ {class: "vs", text: "For every creature of God is good, and nothing is to be rejected, if it is received with thanksgiving."} ]
        , 5:  [ {class: "vs", text: "For it is sanctified through the word of God and prayer."} ]
        , 6:  [ {class: "vs", text: "If you instruct the brothers of these things, you will be a good servant of Christ Jesus, nourished in the words of the faith, and of the good doctrine which you have followed."} ]
        , 7:  [ {class: "vs", text: "But refuse profane and old wives’ fables. Exercise yourself toward godliness."} ]
        , 8:  [ {class: "vs", text: "For bodily exercise has some value, but godliness has value in all things, having the promise of the life which is now, and of that which is to come."} ]
        , 9:  [ {class: "vs", text: "This saying is faithful and worthy of all acceptance."} ]
        , 10: [ {class: "vs", text: "For to this end we both labor and suffer reproach, because we have set our trust in the living God, who is the Savior of all men, especially of those who believe."} ]
        , 11: [ {class: "vs", text: "Command and teach these things."} ]
        , 12: [ {class: "vs", text: "Let no man despise your youth; but be an example to those who believe, in word, in your way of life, in love, in spirit, in faith, and in purity."} ]
        , 13: [ {class: "vs", text: "Until I come, pay attention to reading, to exhortation, and to teaching."} ]
        , 14: [ {class: "vs", text: "Don’t neglect the gift that is in you, which was given to you by prophecy, with the laying on of the hands of the elders."} ]
        , 15: [ {class: "vs", text: "Be diligent in these things. Give yourself wholly to them, that your progress may be revealed to all."} ]
        , 16: [ {class: "vs", text: "Pay attention to yourself and to your teaching. Continue in these things, for in doing this you will save both yourself and those who hear you."} ]
        }
  , 5:  { 1:  [ {class: "vs", text: "Don’t rebuke an older man, but exhort him as a father; the younger men as brothers;"} ]
        , 2:  [ {class: "vs", text: "the elder women as mothers; the younger as sisters, in all purity."} ]
        , 3:  [ {class: "vs", text: "Honor widows who are widows indeed."} ]
        , 4:  [ {class: "vs", text: "But if any widow has children or grandchildren, let them learn first to show piety toward their own family and to repay their parents, for this is acceptable in the sight of God."} ]
        , 5:  [ {class: "vs", text: "Now she who is a widow indeed and desolate, has her hope set on God, and continues in petitions and prayers night and day."} ]
        , 6:  [ {class: "vs", text: "But she who gives herself to pleasure is dead while she lives."} ]
        , 7:  [ {class: "vs", text: "Also command these things, that they may be without reproach."} ]
        , 8:  [ {class: "vs", text: "But if anyone doesn’t provide for his own, and especially his own household, he has denied the faith, and is worse than an unbeliever."} ]
        , 9:  [ {class: "vs", text: "Let no one be enrolled as a widow under sixty years old, having been the wife of one man,"} ]
        , 10: [ {class: "vs", text: "being approved by good works, if she has brought up children, if she has been hospitable to strangers, if she has washed the saints’ feet, if she has relieved the afflicted, and if she has diligently followed every good work."} ]
        , 11: [ {class: "vs", text: "But refuse younger widows, for when they have grown wanton against Christ, they desire to marry,"} ]
        , 12: [ {class: "vs", text: "having condemnation, because they have rejected their first pledge."} ]
        , 13: [ {class: "vs", text: "Besides, they also learn to be idle, going about from house to house. Not only idle, but also gossips and busybodies, saying things which they ought not."} ]
        , 14: [ {class: "vs", text: "I desire therefore that the younger widows marry, bear children, rule the household, and give no occasion to the adversary for insulting."} ]
        , 15: [ {class: "vs", text: "For already some have turned away after Satan."} ]
        , 16: [ {class: "vs", text: "If any man or woman who believes has widows, let them relieve them, and don’t let the assembly be burdened, that it might relieve those who are widows indeed."} ]
        , 17: [ {class: "vs", text: "Let the elders who rule well be counted worthy of double honor, especially those who labor in the word and in teaching."} ]
        , 18: [ {class: "vs", text: "For the Scripture says, “You shall not muzzle the ox when it treads out the grain.” And,"}
              , {class: "vs", wj: true, text: "“The laborer is worthy of his wages.”"}
              ]
        , 19: [ {class: "vs", text: "Don’t receive an accusation against an elder, except at the word of two or three witnesses."} ]
        , 20: [ {class: "vs", text: "Those who sin, reprove in the sight of all, that the rest also may be in fear."} ]
        , 21: [ {class: "vs", text: "I command you in the sight of God, and the Lord Jesus Christ, and the chosen angels, that you observe these things without prejudice, doing nothing by partiality."} ]
        , 22: [ {class: "vs", text: "Lay hands hastily on no one. Don’t be a participant in other people’s sins. Keep yourself pure."} ]
        , 23: [ {class: "vs", text: "Be no longer a drinker of water only, but use a little wine for your stomach’s sake and your frequent infirmities."} ]
        , 24: [ {class: "vs", text: "Some men’s sins are evident, preceding them to judgment, and some also follow later."} ]
        , 25: [ {class: "vs", text: "In the same way also there are good works that are obvious, and those that are otherwise can’t be hidden."} ]
        }
  , 6:  { 1:  [ {class: "vs", text: "Let as many as are bondservants under the yoke count their own masters worthy of all honor, that the name of God and the doctrine not be blasphemed."} ]
        , 2:  [ {class: "vs", text: "Those who have believing masters, let them not despise them because they are brothers, but rather let them serve them, because those who partake of the benefit are believing and beloved. Teach and exhort these things."} ]
        , 3:  [ {class: "vs", text: "If anyone teaches a different doctrine, and doesn’t consent to sound words, the words of our Lord Jesus Christ, and to the doctrine which is according to godliness,"} ]
        , 4:  [ {class: "vs", text: "he is conceited, knowing nothing, but obsessed with arguments, disputes, and word battles, from which come envy, strife, insulting, evil suspicions,"} ]
        , 5:  [ {class: "vs", text: "constant friction of people of corrupt minds and destitute of the truth, who suppose that godliness is a means of gain. Withdraw yourself from such."} ]
        , 6:  [ {class: "vs", text: "But godliness with contentment is great gain."} ]
        , 7:  [ {class: "vs", text: "For we brought nothing into the world, and we certainly can’t carry anything out."} ]
        , 8:  [ {class: "vs", text: "But having food and clothing, we will be content with that."} ]
        , 9:  [ {class: "vs", text: "But those who are determined to be rich fall into a temptation, a snare, and many foolish and harmful lusts, such as drown men in ruin and destruction."} ]
        , 10: [ {class: "vs", text: "For the love of money is a root of all kinds of evil. Some have been led astray from the faith in their greed, and have pierced themselves through with many sorrows."} ]
        , 11: [ {class: "vs", text: "But you, man of God, flee these things, and follow after righteousness, godliness, faith, love, perseverance, and gentleness."} ]
        , 12: [ {class: "vs", text: "Fight the good fight of faith. Take hold of the eternal life to which you were called, and you confessed the good confession in the sight of many witnesses."} ]
        , 13: [ {class: "vs", text: "I command you before God, who gives life to all things, and before Christ Jesus, who before Pontius Pilate testified the good confession,"} ]
        , 14: [ {class: "vs", text: "that you keep the commandment without spot, blameless, until the appearing of our Lord Jesus Christ,"} ]
        , 15: [ {class: "vs", text: "which in its own times he will show, who is the blessed and only Ruler, the King of kings, and Lord of lords."} ]
        , 16: [ {class: "vs", text: "He alone has immortality, dwelling in unapproachable light, whom no man has seen, nor can see: to whom be honor and eternal power. Amen."} ]
        , 17: [ {class: "vs", text: "Charge those who are rich in this present world that they not be arrogant, nor have their hope set on the uncertainty of riches, but on the living God, who richly provides us with everything to enjoy;"} ]
        , 18: [ {class: "vs", text: "that they do good, that they be rich in good works, that they be ready to distribute, willing to share;"} ]
        , 19: [ {class: "vs", text: "laying up in store for themselves a good foundation against the time to come, that they may lay hold of eternal life."} ]
        , 20: [ {class: "vs", text: "Timothy, guard that which is committed to you, turning away from the empty chatter and oppositions of what is falsely called knowledge,"} ]
        , 21: [ {class: "vs", text: "which some profess, and thus have wandered from the faith.</p><p> Grace be with you. Amen."} ]
        }
  }