exports.titus =
  { 1:  { 1:  [ {class: "vs", text: "Paul, a servant of God, and an apostle of Jesus Christ, according to the faith of God’s chosen ones, and the knowledge of the truth which is according to godliness,"} ]
        , 2:  [ {class: "vs", text: "in hope of eternal life, which God, who can’t lie, promised before time began;"} ]
        , 3:  [ {class: "vs", text: "but in his own time revealed his word in the message with which I was entrusted according to the commandment of God our Savior;"} ]
        , 4:  [ {class: "vs", text: "to Titus, my true child according to a common faith: Grace, mercy, and peace from God the Father and the Lord Jesus Christ our Savior."} ]
        , 5:  [ {class: "vs", text: "I left you in Crete for this reason, that you would set in order the things that were lacking and appoint elders in every city, as I directed you,"} ]
        , 6:  [ {class: "vs", text: "if anyone is blameless, the husband of one wife, having children who believe, who are not accused of loose or unruly behavior."} ]
        , 7:  [ {class: "vs", text: "For the overseer must be blameless, as God’s steward, not self-pleasing, not easily angered, not given to wine, not violent, not greedy for dishonest gain;"} ]
        , 8:  [ {class: "vs", text: "but given to hospitality, a lover of good, sober minded, fair, holy, self-controlled,"} ]
        , 9:  [ {class: "vs", text: "holding to the faithful word which is according to the teaching, that he may be able to exhort in the sound doctrine, and to convict those who contradict him."} ]
        , 10: [ {class: "vs", text: "For there are also many unruly men, vain talkers and deceivers, especially those of the circumcision,"} ]
        , 11: [ {class: "vs", text: "whose mouths must be stopped: men who overthrow whole houses, teaching things which they ought not, for dishonest gain’s sake."} ]
        , 12: [ {class: "vs", text: "One of them, a prophet of their own, said, “Cretans are always liars, evil beasts, and idle gluttons.”"} ]
        , 13: [ {class: "vs", text: "This testimony is true. For this cause, reprove them sharply, that they may be sound in the faith,"} ]
        , 14: [ {class: "vs", text: "not paying attention to Jewish fables and commandments of men who turn away from the truth."} ]
        , 15: [ {class: "vs", text: "To the pure, all things are pure; but to those who are defiled and unbelieving, nothing is pure; but both their mind and their conscience are defiled."} ]
        , 16: [ {class: "vs", text: "They profess that they know God, but by their deeds they deny him, being abominable, disobedient, and unfit for any good work."} ]
        }
  , 2:  { 1:  [ {class: "vs", text: "But say the things which fit sound doctrine,"} ]
        , 2:  [ {class: "vs", text: "that older men should be temperate, sensible, sober minded, sound in faith, in love, and in perseverance:"} ]
        , 3:  [ {class: "vs", text: "and that older women likewise be reverent in behavior, not slanderers nor enslaved to much wine, teachers of that which is good,"} ]
        , 4:  [ {class: "vs", text: "that they may train the young wives to love their husbands, to love their children,"} ]
        , 5:  [ {class: "vs", text: "to be sober minded, chaste, workers at home, kind, being in subjection to their own husbands, that God’s word may not be blasphemed."} ]
        , 6:  [ {class: "vs", text: "Likewise, exhort the younger men to be sober minded."} ]
        , 7:  [ {class: "vs", text: "In all things be showing yourself an example of good works. In your teaching, be showing integrity, seriousness, incorruptibility,"} ]
        , 8:  [ {class: "vs", text: "and soundness of speech that can’t be condemned, that he who opposes you may be ashamed, having no evil thing to say about us."} ]
        , 9:  [ {class: "vs", text: "Exhort servants to be in subjection to their own masters and to be well-pleasing in all things, not contradicting,"} ]
        , 10: [ {class: "vs", text: "not stealing, but showing all good fidelity, that they may adorn the doctrine of God, our Savior, in all things."} ]
        , 11: [ {class: "vs", text: "For the grace of God has appeared, bringing salvation to all men,"} ]
        , 12: [ {class: "vs", text: "instructing us to the intent that, denying ungodliness and worldly lusts, we would live soberly, righteously, and godly in this present age;"} ]
        , 13: [ {class: "vs", text: "looking for the blessed hope and appearing of the glory of our great God and Savior, Jesus Christ,"} ]
        , 14: [ {class: "vs", text: "who gave himself for us, that he might redeem us from all iniquity, and purify for himself a people for his own possession, zealous for good works."} ]
        , 15: [ {class: "vs", text: "Say these things and exhort and reprove with all authority. Let no one despise you."} ]
        }
  , 3:  { 1:  [ {class: "vs", text: "Remind them to be in subjection to rulers and to authorities, to be obedient, to be ready for every good work,"} ]
        , 2:  [ {class: "vs", text: "to speak evil of no one, not to be contentious, to be gentle, showing all humility toward all men."} ]
        , 3:  [ {class: "vs", text: "For we were also once foolish, disobedient, deceived, serving various lusts and pleasures, living in malice and envy, hateful, and hating one another."} ]
        , 4:  [ {class: "vs", text: "But when the kindness of God our Savior and his love toward mankind appeared,"} ]
        , 5:  [ {class: "vs", text: "not by works of righteousness which we did ourselves, but according to his mercy, he saved us through the washing of regeneration and renewing by the Holy Spirit,"} ]
        , 6:  [ {class: "vs", text: "whom he poured out on us richly, through Jesus Christ our Savior;"} ]
        , 7:  [ {class: "vs", text: "that being justified by his grace, we might be made heirs according to the hope of eternal life."} ]
        , 8:  [ {class: "vs", text: "This saying is faithful, and concerning these things I desire that you affirm confidently, so that those who have believed God may be careful to maintain good works. These things are good and profitable to men;"} ]
        , 9:  [ {class: "vs", text: "but shun foolish questionings, genealogies, strife, and disputes about the law; for they are unprofitable and vain."} ]
        , 10: [ {class: "vs", text: "Avoid a factious man after a first and second warning,"} ]
        , 11: [ {class: "vs", text: "knowing that such a one is perverted and sins, being self-condemned."} ]
        , 12: [ {class: "vs", text: "When I send Artemas to you, or Tychicus, be diligent to come to me to Nicopolis, for I have determined to winter there."} ]
        , 13: [ {class: "vs", text: "Send Zenas, the lawyer, and Apollos on their journey speedily, that nothing may be lacking for them."} ]
        , 14: [ {class: "vs", text: "Let our people also learn to maintain good works for necessary uses, that they may not be unfruitful."} ]
        , 15: [ {class: "vs", text: "All who are with me greet you. Greet those who love us in faith. Grace be with you all. Amen."} ]
        }
  }