function book_name(token) {
  name = book_names[token]
  return (name === undefined) ? "Undefined" : name
}

function web_name(token) {
  name = web_names[book_names[token]]
  return (name === undefined) ? "Undefined" : name
}

function book_title(token) {
  title = book_titles[book_names[token]]
  return (title === undefined) ? "Undefined" : title
}

module.exports = {
      book_name: book_name
    , web_name: web_name
    , book_title: book_title
}

var book_names = {
  "1 chronicles": "1 chronicles",  "1 chron": "1 chronicles", "1 ch": "1 chronicles", "i ch": "1 chronicles", "1ch": "1 chronicles", "1 chr": "1 chronicles", "i chr": "1 chronicles", "1chr": "1 chronicles", "i chron": "1 chronicles", "1chron": "1 chronicles", "i chronicles": "1 chronicles", "1chronicles": "1 chronicles", "1st chronicles": "1 chronicles", "first chronicles": "1 chronicles",
  "1 corinthians": "1 corinthians", "1 cor": "1 corinthians", "1 co": "1 corinthians", "i co": "1 corinthians", "1co": "1 corinthians", "i cor": "1 corinthians", "1cor": "1 corinthians", "i corinthians": "1 corinthians", "1corinthians": "1 corinthians", "1st corinthians": "1 corinthians", "first corinthians": "1 corinthians",
  "1 esdras": "1 esdras",  "1 esdr": "1 esdras", "1 esd": "1 esdras", "i es": "1 esdras", "1es": "1 esdras", "i esd": "1 esdras", "1esd": "1 esdras", "i esdr": "1 esdras", "1esdr": "1 esdras", "i esdras": "1 esdras", "1esdras": "1 esdras", "1st esdras": "1 esdras", "first esdras": "1 esdras",
  "1 john": "1 john",  "1 john": "1 john", "1 jn": "1 john", "i jn": "1 john", "1jn": "1 john", "i jo": "1 john", "1jo": "1 john", "i joh": "1 john", "1joh": "1 john", "i jhn": "1 john", "1 jhn": "1 john", "1jhn": "1 john", "i john": "1 john", "1john": "1 john", "1st john": "1 john", "first john": "1 john",
  "1 kings": "1 kings", "1 kgs": "1 kings", "1 ki": "1 kings", "1k": "1 kings", "i kgs": "1 kings", "1kgs": "1 kings", "i ki": "1 kings", "1ki": "1 kings", "i kings": "1 kings", "1kings": "1 kings", "1st kgs": "1 kings", "1st kings": "1 kings", "first kings": "1 kings", "first kgs": "1 kings", "1kin": "1 kings",
  "1 maccabees": "1 maccabees", "1 macc": "1 maccabees", "1 mac": "1 maccabees", "1m": "1 maccabees", "i ma": "1 maccabees", "1ma": "1 maccabees", "i mac": "1 maccabees", "1mac": "1 maccabees", "i macc": "1 maccabees", "1macc": "1 maccabees", "i maccabees": "1 maccabees", "1maccabees": "1 maccabees", "1st maccabees": "1 maccabees", "first maccabees": "1 maccabees",
  "1 peter": "1 peter", "1 pet": "1 peter", "1 pe": "1 peter", "i pe": "1 peter", "1pe": "1 peter", "i pet": "1 peter", "1pet": "1 peter", "i pt": "1 peter", "1 pt": "1 peter", "1pt": "1 peter", "i peter": "1 peter", "1peter": "1 peter", "1st peter": "1 peter", "first peter": "1 peter",
  "1 samuel": "1 samuel",  "1 sam": "1 samuel", "1 sa": "1 samuel", "1samuel": "1 samuel", "1s": "1 samuel", "i sa": "1 samuel", "1 sm": "1 samuel", "1sa": "1 samuel", "i sam": "1 samuel", "1sam": "1 samuel", "i samuel": "1 samuel", "1st samuel": "1 samuel", "first samuel": "1 samuel",
  "1 thessalonians": "1 thessalonians", "1 thess": "1 thessalonians", "1 th": "1 thessalonians", "i th": "1 thessalonians", "1th": "1 thessalonians", "i thes": "1 thessalonians", "1thes": "1 thessalonians", "i thess": "1 thessalonians", "1thess": "1 thessalonians", "i thessalonians": "1 thessalonians", "1thessalonians": "1 thessalonians", "1st thessalonians": "1 thessalonians", "first thessalonians": "1 thessalonians",
  "1 timothy": "1 timothy", "1 tim": "1 timothy", "1 ti": "1 timothy", "i ti": "1 timothy", "1ti": "1 timothy", "i tim": "1 timothy", "1tim": "1 timothy", "i timothy": "1 timothy", "1timothy": "1 timothy", "1st timothy": "1 timothy", "first timothy": "1 timothy",
  "2 chronicles": "2 chronicles",  "2 chron": "2 chronicles", "2 ch": "2 chronicles", "ii ch": "2 chronicles", "2ch": "2 chronicles", "ii chr": "2 chronicles", "2chr": "2 chronicles", "ii chron": "2 chronicles", "2chron": "2 chronicles", "ii chronicles": "2 chronicles", "2chronicles": "2 chronicles", "2nd chronicles": "2 chronicles", "second chronicles": "2 chronicles",
  "2 corinthians": "2 corinthians", "2 cor": "2 corinthians", "2 co": "2 corinthians", "ii co": "2 corinthians", "2co": "2 corinthians", "ii cor": "2 corinthians", "2cor": "2 corinthians", "ii corinthians": "2 corinthians", "2corinthians": "2 corinthians", "2nd corinthians": "2 corinthians", "second corinthians": "2 corinthians",
  "2 esdras": "2 esdras",  "2 esdr": "2 esdras", "2 esd": "2 esdras", "ii es": "2 esdras", "2es": "2 esdras", "ii esd": "2 esdras", "2esd": "2 esdras", "ii esdr": "2 esdras", "2esdr": "2 esdras", "ii esdras": "2 esdras", "2esdras": "2 esdras", "2nd esdras": "2 esdras", "second esdras": "2 esdras",
  "2 john": "2 john",  "2 john": "2 john", "2 jn": "2 john", "ii jn": "2 john", "2jn": "2 john", "ii jo": "2 john", "2jo": "2 john", "ii joh": "2 john", "2joh": "2 john", "ii jhn": "2 john", "2 jhn": "2 john", "2jhn": "2 john", "ii john": "2 john", "2john": "2 john", "2nd john": "2 john", "second john": "2 john",
  "2 kings": "2 kings", "2 kgs": "2 kings", "2 ki": "2 kings", "2k": "2 kings", "ii kgs": "2 kings", "2kgs": "2 kings", "ii ki": "2 kings", "2ki": "2 kings", "ii kings": "2 kings", "2kings": "2 kings", "2nd kgs": "2 kings", "2nd kings": "2 kings", "second kings": "2 kings", "second kgs": "2 kings", "2kin": "2 kings",
  "2 maccabees": "2 maccabees", "2 macc": "2 maccabees", "2 mac": "2 maccabees", "2m": "2 maccabees", "ii ma": "2 maccabees", "2ma": "2 maccabees", "ii mac": "2 maccabees", "2mac": "2 maccabees", "ii macc": "2 maccabees", "2macc": "2 maccabees", "ii maccabees": "2 maccabees", "2maccabees": "2 maccabees", "2nd maccabees": "2 maccabees", "second maccabees": "2 maccabees",
  "2 peter": "2 peter", "2 pet": "2 peter", "2 pe": "2 peter", "ii pe": "2 peter", "2pe": "2 peter", "ii pet": "2 peter", "2pet": "2 peter", "ii pt": "2 peter", "2 pt": "2 peter", "2pt": "2 peter", "ii peter": "2 peter", "2peter": "2 peter", "2nd peter": "2 peter", "second peter": "2 peter",
  "2 samuel": "2 samuel",  "2 sam": "2 samuel", "2 sa": "2 samuel", "2s": "2 samuel", "ii sa": "2 samuel", "2 sm": "2 samuel", "2sa": "2 samuel", "ii sam": "2 samuel", "2sam": "2 samuel", "ii samuel": "2 samuel", "2samuel": "2 samuel", "2nd samuel": "2 samuel", "second samuel": "2 samuel",
  "2 thessalonians": "2 thessalonians", "2 thess": "2 thessalonians", "2 th": "2 thessalonians", "ii th": "2 thessalonians", "2th": "2 thessalonians", "ii thes": "2 thessalonians", "2thes": "2 thessalonians", "ii thess": "2 thessalonians", "2thess": "2 thessalonians", "ii thessalonians": "2 thessalonians", "2thessalonians": "2 thessalonians", "2nd thessalonians": "2 thessalonians", "second thessalonians": "2 thessalonians",
  "2 timothy": "2 timothy", "2 tim": "2 timothy", "2 ti": "2 timothy", "ii ti": "2 timothy", "2ti": "2 timothy", "ii tim": "2 timothy", "2tim": "2 timothy", "ii timothy": "2 timothy", "2timothy": "2 timothy", "2nd timothy": "2 timothy", "second timothy": "2 timothy",
  "3 john": "3 john",  "3 john": "3 john", "3 jn": "3 john", "iii jn": "3 john", "3jn": "3 john", "iii jo": "3 john", "3jo": "3 john", "iii joh": "3 john", "3joh": "3 john", "iii jhn": "3 john", "3 jhn": "3 john", "3jhn": "3 john", "iii john": "3 john", "3john": "3 john", "3rd john": "3 john", "third john": "3 john",
  "3 maccabees": "3 maccabees", "3 macc": "3 maccabees", "3 mac": "3 maccabees", "iii ma": "3 maccabees", "3ma": "3 maccabees", "iii mac": "3 maccabees", "3mac": "3 maccabees", "iii macc": "3 maccabees", "3macc": "3 maccabees", "iii maccabees": "3 maccabees", "3rd maccabees": "3 maccabees", "third maccabees": "3 maccabees",
  "4 maccabees": "4 maccabees", "4 macc": "4 maccabees", "4 mac": "4 maccabees", "iv ma": "4 maccabees", "4ma": "4 maccabees", "iv mac": "4 maccabees", "4mac": "4 maccabees", "iv macc": "4 maccabees", "4macc": "4 maccabees", "iv maccabees": "4 maccabees", "iiii maccabees": "4 maccabees", "4maccabees": "4 maccabees", "4th maccabees": "4 maccabees", "fourth maccabees": "4 maccabees",
  "acts": "acts",  "ac": "acts",
  "additional psalm": "additional psalm",  "add psalm": "additional psalm", "add ps": "additional psalm",
  "additions to esther": "additions to esther", "add esth": "additions to esther", "add es": "additions to esther", "rest of esther": "additions to esther", "the rest of esther": "additions to esther", "aes": "additions to esther", "addesth": "additions to esther",
  "amos": "amos",  "am": "amos",
  "baruch": "baruch",  "bar": "baruch",
  "bel and the dragon": "bel and the dragon",  "bel": "bel and the dragon",
  "colossians": "colossians",  "col": "colossians",
  "daniel": "daniel",  "dan": "daniel", "da": "daniel", "dn": "daniel",
  "deuteronomy": "deuteronomy", "deut": "deuteronomy", "dt": "deuteronomy",
  "ecclesiastes": "ecclesiastes",  "eccles": "ecclesiastes", "ec": "ecclesiastes", "ecc": "ecclesiastes", "eccl": "ecclesiastes", "qoh": "ecclesiastes", "qoheleth": "ecclesiastes",
  "ephesians": "ephesians", "ephes": "ephesians", "eph": "ephesians",
  "epistle to the laodiceans": "epistle to the laodiceans", "laodiceans": "epistle to the laodiceans", "laod": "epistle to the laodiceans", "ep laod": "epistle to the laodiceans", "epist laodiceans": "epistle to the laodiceans", "epistle laodiceans": "epistle to the laodiceans", "epistle to laodiceans": "epistle to the laodiceans",
  "esther": "esther",  "esth": "esther", "es": "esther",
  "exodus": "exodus",  "exo": "exodus", "ex": "exodus", "exod": "exodus",
  "ezekiel": "ezekiel", "ezek": "ezekiel", "eze": "ezekiel", "ezk": "ezekiel",
  "ezra": "ezra",  "ezra": "ezra", "ezr": "ezra",
  "galatians": "galatians", "gal": "galatians", "ga": "galatians",
  "genesis": "genesis", "gen": "genesis", "ge": "genesis", "gn": "genesis",
  "habakkuk": "habakkuk",  "hab": "habakkuk",
  "haggai": "haggai",  "hag": "haggai", "hg": "haggai",
  "hebrews": "hebrews",  "heb": "hebrews",
  "hosea": "hosea", "hos": "hosea", "ho": "hosea",
  "isaiah": "isaiah",  "isa": "isaiah", "is": "isaiah",
  "james": "james", "jas": "james", "jm": "james",
  "jeremiah": "jeremiah",  "jer": "jeremiah", "je": "jeremiah", "jr": "jeremiah",
  "job": "job", "jb": "job",
  "joel": "joel", "joe": "joel", "jl": "joel",
  "john": "john",  "jn": "john", "jhn": "john",
  "jonah": "jonah", "jnh": "jonah", "jon": "jonah",
  "joshua": "joshua",  "josh": "joshua", "jos": "joshua", "jsh": "joshua",
  "jude": "jude",  "jud": "jude",
  "judges": "judges",  "judg": "judges", "jdg": "judges", "jg": "judges", "jdgs": "judges",
  "judith": "judith",  "jdth": "judith", "jdt": "judith", "jth": "judith",
  "lamentations": "lamentations",  "lam": "lamentations", "la": "lamentations",
  "letter of jeremiah": "letter of jeremiah",  "let jer": "letter of jeremiah", "let jer": "letter of jeremiah", "lje": "letter of jeremiah", "ltr jer": "letter of jeremiah",
  "leviticus": "leviticus", "lev": "leviticus", "le": "leviticus", "lv": "leviticus",
  "luke": "luke",  "luk": "luke", "lk": "luke",
  "malachi": "malachi", "mal": "malachi", "ml": "malachi",
  "mark": "mark",  "mrk": "mark", "mk": "mark", "mr": "mark",
  "matthew": "matthew", "matt": "matthew", "mt": "matthew",
  "micah": "micah",  "mic": "micah",
  "nahum": "nahum", "nah": "nahum", "na": "nahum",
  "nehemiah": "nehemiah",  "neh": "nehemiah", "ne": "nehemiah",
  "numbers": "numbers", "num": "numbers", "nu": "numbers", "nm": "numbers", "nb": "numbers",
  "obadiah": "obadiah", "obad": "obadiah", "ob": "obadiah",
  "ode": "ode",
  "philemon": "philemon", "phm": "philemon",
  "philippians": "philippians", "phil": "philippians", "php": "philippians",
  "prayer of manasseh": "prayer of manasses",  "pr of man": "prayer of manasses", "pr man": "prayer of manasses", "pma": "prayer of manasses", "prayer of manasses": "prayer of manasses",
  "prayer of manasses": "prayer of manasses",  "pr of man": "prayer of manasses", "pr man": "prayer of manasses", "pma": "prayer of manasses", "prayer of manasses": "prayer of manasses",
  "proverbs": "proverbs",  "prov": "proverbs", "pr": "proverbs", "prv": "proverbs",
  "psalm": "psalms", "pslm": "psalms", "ps": "psalms", "psalms": "psalms", "psa": "psalms", "psm": "psalms", "pss": "psalms",
  "psalms of solomon": "psalms of solomon", "ps solomon": "psalms of solomon", "ps sol": "psalms of solomon", "psalms solomon": "psalms of solomon", "pssol": "psalms of solomon",
  "revelation": "revelation",  "rev": "revelation", "re": "revelation", "the revelation": "revelation",
  "romans": "romans",  "rom": "romans", "ro": "romans", "rm": "romans",
  "ruth": "ruth",  "rth": "ruth", "ru": "ruth",
  "sirach": "sirach",  "sir": "sirach", "ecclesiasticus": "sirach", "ecclus": "sirach",
  "song of solomon": "song of solomon", "song": "song of solomon", "so": "song of solomon", "canticle of canticles": "song of solomon", "canticles": "song of solomon", "song of songs": "song of solomon", "sos": "song of solomon",
  "song of three youths": "song of three youths",  "song of three": "song of three youths", "song thr": "song of three youths", "the song of three youths": "song of three youths", "pr az": "song of three youths", "prayer of azariah": "song of three youths", "azariah": "song of three youths", "the song of the three holy children": "song of three youths", "the song of three jews": "song of three youths", "song of the three holy children": "song of three youths", "song of thr": "song of three youths", "song of three children": "song of three youths", "song of three jews": "song of three youths",
  "susanna": "susanna",  "sus": "susanna",
  "titus": "titus",  "tit": "titus",
  "tobit": "tobit",  "tob": "tobit", "tb": "tobit",
  "wisdom of solomon": "wisdom of solomon", "wisd of sol": "wisdom of solomon", "wis": "wisdom of solomon", "wisd": "wisdom of solomon", "ws": "wisdom of solomon", "wisdom": "wisdom of solomon",
  "zechariah": "zechariah", "zech": "zechariah", "zec": "zechariah", "zc": "zechariah",
  "zephaniah": "zephaniah", "zeph": "zephaniah", "zep": "zephaniah", "zp": "zephaniah",
}

var web_names = {
  "1 chronicles": "1CH",
  "1 corinthians": "1CO",
  "1 esdras": "1ES",
  "1 john": "1JN",
  "1 kings": "1KI",
  "1 maccabees": "1MA",
  "1 peter": "1PE",
  "1 samuel": "1SA",
  "1 thessalonians": "1TH",
  "1 timothy": "1TI",
  "2 chronicles": "2CH",
  "2 corinthians": "2CO",
  "2 esdras": "2ES",
  "2 john": "2JN",
  "2 kings": "2KI",
  "2 maccabees": "2MA",
  "2 peter": "2PE",
  "2 samuel": "2SA",
  "2 thessalonians": "2TH",
  "2 timothy": "2TI",
  "3 john": "3JN",
  "3 maccabees": "3MA",
  "4 maccabees": "4MA",
  "acts": "ACT",
  "amos": "AMO",
  "baruch": "BAR",
  "colossians": "COL",
  "daniel (greek)": "DAG",
  "daniel": "DAN",
  "deuteronomy": "DEU",
  "ecclesiastes": "ECC",
  "ephesians": "EPH",
  "esther (greek)": "ESG",
  "esther": "EST",
  "exodus": "EXO",
  "ezekiel": "EZK",
  "ezra": "EZR",
  "galatians": "GAL",
  "genesis": "GEN",
  "glossary": "GLO",
  "habakkuk": "HAB",
  "haggai": "HAG",
  "hebrews": "HEB",
  "hosea": "HOS",
  "isaiah": "ISA",
  "james": "JAS",
  "jeremiah": "JER",
  "job": "JOB",
  "joel": "JOL",
  "john": "JHN",
  "jonah": "JON",
  "joshua": "JOS",
  "jude": "JUD",
  "judges": "JDG",
  "judith": "JDT",
  "lamentations": "LAM",
  "leviticus": "LEV",
  "luke": "LUK",
  "malachi": "MAL",
  "mark": "MRK",
  "matthew": "MAT",
  "micah": "MIC",
  "nahum": "NAM",
  "nehemiah": "NEH",
  "numbers": "NUM",
  "obadiah": "OBA",
  "philemon": "PHM",
  "philippians": "PHP",
  "prayer of manasses": "MAN",
  "preface": "FRT",
  "proverbs": "PRO",
  "psalm 151": "PS2",
  "psalms": "PSA",
  "revelation": "REV",
  "romans": "ROM",
  "ruth": "RUT",
  "sirach": "SIR",
  "song of solomon": "SNG",
  "titus": "TIT",
  "tobit": "TOB",
  "wisdom of solomon": "WIS",
  "zechariah": "ZEC",
  "zephaniah": "ZEP",  
  }

var book_titles = {
  "1 chronicles": "1 Chronicles",
  "1 corinthians": "1 Corinthians",
  "1 esdras": "1 Esdras",
  "1 john": "1 John",
  "1 kings": "1 Kings",
  "1 maccabees": "1 Maccabees",
  "1 peter": "1 Peter",
  "1 samuel": "1 Samuel",
  "1 thessalonians": "1 Thessalonians",
  "1 timothy": "1 Timothy",
  "2 chronicles": "2 Chronicles",
  "2 corinthians": "2 Corinthians",
  "2 esdras": "2 Esdras",
  "2 john": "2 John",
  "2 kings": "2 Kings",
  "2 maccabees": "2 Maccabees",
  "2 peter": "2 Peter",
  "2 samuel": "2 Samuel",
  "2 thessalonians": "2 Thessalonians",
  "2 timothy": "2 Timothy",
  "3 john": "3 John",
  "3 maccabees": "3 Maccabees",
  "4 maccabees": "4 Maccabees",
  "acts": "Acts",
  "amos": "Amos",
  "baruch": "Baruch",
  "colossians": "Colossians",
  "daniel (greek)": "Daniel (Greek)",
  "daniel": "Daniel",
  "deuteronomy": "Deuteronomy",
  "ecclesiastes": "Ecclesiastes",
  "ephesians": "Ephesians",
  "esther (greek)": "Esther (Greek)",
  "esther": "Esther",
  "exodus": "Exodus",
  "ezekiel": "Ezekiel",
  "ezra": "Ezra",
  "galatians": "Galatians",
  "genesis": "Genesis",
  "glossary": "Glossary",
  "habakkuk": "Habakkuk",
  "haggai": "Haggai",
  "hebrews": "Hebrews",
  "hosea": "Hosea",
  "isaiah": "Isaiah",
  "james": "James",
  "jeremiah": "Jeremiah",
  "job": "Job",
  "joel": "Joel",
  "john": "John",
  "jonah": "Jonah",
  "joshua": "Joshua",
  "jude": "Jude",
  "judges": "Judges",
  "judith": "Judith",
  "lamentations": "Lamentations",
  "leviticus": "Leviticus",
  "luke": "Luke",
  "malachi": "Malachi",
  "mark": "Mark",
  "matthew": "Matthew",
  "micah": "Micah",
  "nahum": "Nahum",
  "nehemiah": "Nehemiah",
  "numbers": "Numbers",
  "obadiah": "Obadiah",
  "philemon": "Philemon",
  "philippians": "Philippians",
  "prayer of manasses": "Prayer of Manasses",
  "preface": "Preface",
  "proverbs": "Proverbs",
  "psalm 151": "Psalm 151",
  "psalms": "Psalms",
  "revelation": "Revelation",
  "romans": "Romans",
  "ruth": "Ruth",
  "sirach": "Sirach",
  "song of solomon": "Song of Solomon",
  "titus": "Titus",
  "tobit": "Tobit",
  "wisdom of solomon": "Wisdom of Solomon",
  "zechariah": "Zechariah",
  "zephaniah": "Zephaniah",
}
