'use strict';
// prepare sqlite db
var sqlite = require('SQLite')
  , db = sqlite.open("file.sqlite")
  ;
db.execute("create table if not exists daily_colors (id integer primary key, season text, week integer, day text, color text, title text)")
db.execute("create table if not exists eu_colors (id integer primary key, season text, week integer, order integer, color text, title text)")
db.execute("create table if not exists daily_reading (id integer primary key, season text, week integer, day text, reading text, order integer, of_type text, ref text)")
db.execute("create table if not exists eu_readings (id integer primary key, season text, week integer, reading text, order integer, of_type text, ref text)")

//daily colors
//season week day color title
 //daily colors
//season week day color title
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 1, 'Sunday', 'violet, blue', 'First Sunday in Advent')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 1, 'Monday', 'violet, blue', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 1, 'Tuesday',  'violet, blue', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 1, 'Wednesday', 'violet, blue', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 1, 'Thursday', 'violet, blue', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 1, 'Friday', 'violet, blue', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 1, 'Saturday', 'violet, blue', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 2, 'Sunday', 'violet, blue', 'Second Sunday in Advent')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 2, 'Monday', 'violet, blue', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 2, 'Tuesday', 'violet, blue', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 2, 'Wednesday', 'violet, blue', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 2, 'Thursday', 'violet, blue', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 2, 'Friday', 'violet, blue', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 2, 'Saturday', 'violet, blue', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 3, 'Sunday', 'rose, violet, blue', 'Third Sunday in Advent')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 3, 'Monday', 'rose, violet, blue', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 3, 'Tuesday', 'rose, violet, blue', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 3, 'Wednesday', 'violet', 'Wednesday Ember Day')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 3, 'Thursday', 'rose, violet, blue', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 3, 'Friday', 'green', 'Friday Ember Day')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 3, 'Saturday', 'violet', 'Saturday Ember Day')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 4, 'Sunday', 'violet, blue', 'Fourth Sunday in Advent')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 4, 'Monday', 'violet, blue', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 4, 'Tuesday', 'violet, blue', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 4, 'Wednesday', 'violet, blue', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 4, 'Thursday', 'violet, blue', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 4, 'Friday', 'violet, blue', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('advent', 4, 'Saturday', 'violet, blue', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('christmas', 1, 'christmasEve', 'violet, blue', 'Christmas Eve')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('christmas', 1, 'christmasDay', 'white, gold', 'Christmas Day')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('christmas', 1, 'stStephen', 'red', 'St Stephen')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('christmas', 1, 'stjohn', 'white, gold', 'St john Evangelist')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('christmas', 1, 'holyInnocents', 'red', 'Holy Innocents')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('christmas', 1, 'Sunday', 'white, gold', '* First Sunday of Christmas')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('christmas', 1, 'Dec29', 'white, gold', 'December 29')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('christmas', 1, 'Dec30', 'white, gold', 'December 30')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('christmas', 1, 'Dec31', 'white, gold', 'December 31')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('christmas', 1, 'octaveChristmas', 'white, gold', 'Octave Day of Christmas')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('christmas', 2, 'Sunday', 'white, gold', 'Second Sunday of Christmas')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('christmas', 2, 'Jan02', 'white, gold', 'January 2')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('christmas', 2, 'Jan03', 'white, gold', 'January 3')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('christmas', 2, 'Jan04', 'white, gold', 'January 4')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('christmas', 2, 'Jan05', 'white, gold', 'January 5')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 0, 'Epiphany', 'white, gold', 'Epiphany')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 0, 'Monday', 'white, gold', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 0, 'Tuesday', 'white, gold', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 0, 'Wednesday', 'white, gold', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 0, 'Thursday', 'white, gold', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 0, 'Friday', 'white, gold', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 0, 'Saturday', 'white, gold', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 1, 'Sunday', 'white, gold', 'First Sunday of Epiphany')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 1, 'Monday', 'white, gold', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 1, 'Tuesday', 'white, gold', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 1, 'Wednesday', 'white, gold', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 1, 'Thursday', 'white, gold', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 1, 'Friday', 'white, gold', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 1, 'Saturday', 'white, gold', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 2, 'Sunday', 'green', 'Second Sunday of Epiphany')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 2, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 2, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 2, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 2, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 2, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 2, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 3, 'Sunday', 'green', 'Third Sunday of Epiphany')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 3, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 3, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 3, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 3, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 3, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 3, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 4, 'Sunday', 'green', 'Fourth Sunday of Epiphany')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 4, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 4, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 4, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 4, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 4, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 4, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 5, 'Sunday', 'green', 'Fifth Sunday of Epiphany')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 5, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 5, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 5, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 5, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 5, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 5, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 6, 'Sunday', 'green', 'Sixth Sunday of Epiphany')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 6, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 6, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 6, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 6, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 6, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 6, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 7, 'Sunday', 'green', 'Seventh Sunday of Epiphany')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 7, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 7, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 7, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 7, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 7, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 7, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 8, 'Sunday', 'green', 'Eighth Sunday of Epiphany')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 8, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 8, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 8, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 8, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 8, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 8, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 9, 'Sunday', 'white', 'The Last Sunday of Epiphany [Transfiguration]')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 9, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 9, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 9, 'Wednesday', 'violet', 'Ash Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 9, 'Thursday', 'violet', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 9, 'Friday', 'violet', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('epiphany', 9, 'Saturday', 'violet', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 1, 'Sunday', 'violet', 'First Sunday in Lent')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 1, 'Monday', 'violet', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 1, 'Tuesday', 'violet', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 1, 'Wednesday', 'violet', 'Wednesday Ember Day')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 1, 'Thursday', 'violet', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 1, 'Friday', 'violet', 'Friday Ember Day')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 1, 'Saturday', 'violet', 'Saturday Ember Day')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 2, 'Sunday', 'violet', 'Second Sunday in Lent')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 2, 'Monday', 'violet', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 2, 'Tuesday', 'violet', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 2, 'Wednesday', 'violet', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 2, 'Thursday', 'violet', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 2, 'Friday', 'violet', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 2, 'Saturday', 'violet', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 3, 'Sunday', 'violet', 'Third Sunday in Lent')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 3, 'Monday', 'violet', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 3, 'Tuesday', 'violet', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 3, 'Wednesday', 'violet', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 3, 'Thursday', 'violet', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 3, 'Friday', 'violet', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 3, 'Saturday', 'violet', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 4, 'Sunday', 'rose, violet', 'Fourth Sunday in Lent')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 4, 'Monday', 'violet', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 4, 'Tuesday', 'rose, violet', 'Fourth Sunday in Lent')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 4, 'Wednesday', 'violet', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 4, 'Thursday', 'violet', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 4, 'Friday', 'violet', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 4, 'Saturday', 'violet', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 5, 'Sunday', 'violet', 'Fifth Sunday in Lent [Passion]')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 5, 'Monday', 'violet', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 5, 'Tuesday', 'violet', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 5, 'Wednesday', 'violet', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 5, 'Thursday', 'violet', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 5, 'Friday', 'violet', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('lent', 5, 'Saturday', 'violet', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('palmSunday', 1, 'Sunday', 'red', 'Palm Sunday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('palmSunday', 1, 'Monday', 'violet', 'Monday in Holy Week')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('palmSunday', 1, 'Tuesday', 'violet', 'Tuesday in Holy Week')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('palmSunday', 1, 'Wednesday', 'violet', 'Wednesday in Holy Week')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('palmSunday', 1, 'Thursday', 'white', 'Maundy Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('palmSunday', 1, 'Friday', 'red', 'Good Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('palmSunday', 1, 'Saturday', 'violet', 'Holy Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easterDay', 1, 'Sunday', 'white', 'Easter Day')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easterDay', 1, 'Monday', 'white', 'Monday of Easter Week')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easterDay', 1, 'Tuesday', 'white', 'Tuesday of Easter Week')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easterDay', 1, 'Wednesday', 'white', 'Wednesday of Easter Week')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easterDay', 1, 'Thursday', 'white', 'Thursday of Easter Week')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easterDay', 1, 'Friday', 'white', 'Friday of Easter Week')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easterDay', 1, 'Saturday', 'white', 'Saturday of Easter Week')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 2, 'Sunday', 'white', 'Second Sunday of Easter')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 2, 'Monday', 'white', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 2, 'Tuesday', 'white', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 2, 'Wednesday', 'white', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 2, 'Thursday', 'white', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 2, 'Friday', 'white', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 2, 'Saturday', 'white', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 3, 'Sunday', 'white', 'Third Sunday of Easter')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 3, 'Monday', 'white', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 3, 'Tuesday', 'white', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 3, 'Wednesday', 'white', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 3, 'Thursday', 'white', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 3, 'Friday', 'white', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 3, 'Saturday', 'white', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 4, 'Sunday', 'white', 'Fourth Sunday of Easter')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 4, 'Monday', 'white', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 4, 'Tuesday', 'white', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 4, 'Wednesday', 'white', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 4, 'Thursday', 'white', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 4, 'Friday', 'white', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 4, 'Saturday', 'white', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 5, 'Sunday', 'white', 'Fifth Sunday of Easter')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 5, 'Monday', 'white', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 5, 'Tuesday', 'white', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 5, 'Wednesday', 'white', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 5, 'Thursday', 'white', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 5, 'Friday', 'white', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 5, 'Saturday', 'white', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 6, 'Sunday', 'white', 'Sixth Sunday of Easter [Rogation]')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 6, 'Monday', 'violet', 'Monday Rogation Days')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 6, 'Tuesday', 'violet', 'Tuesday Rogation Days')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 6, 'Wednesday', 'violet', 'Wednesday Rogation Days')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 6, 'Thursday', 'white', 'Thursday Ascension Day')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 6, 'Friday', 'white', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 6, 'Saturday', 'white', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 7, 'Sunday', 'white', 'Sunday after Ascension Day')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 7, 'Monday', 'white', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 7, 'Tuesday', 'white', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 7, 'Wednesday', 'white', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 7, 'Thursday', 'white', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 7, 'Friday', 'white', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('easter', 7, 'Saturday', 'white', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('ascension', 1, 'Thursday', 'white', 'Thursday Ascension Day')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('ascension', 1, 'Friday', 'white', 'Friday after Ascension')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('ascension', 1, 'Saturday', 'white', 'Saturday after Ascension')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('pentecost', 1, 'Sunday', 'red', 'Pentecost')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('pentecost', 1, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('pentecost', 1, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('pentecost', 1, 'Wednesday', 'violet', 'Wednesday Ember Day')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('pentecost', 1, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('pentecost', 1, 'Friday', 'violet', 'Friday Ember Day')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('pentecost', 1, 'Saturday', 'violet', 'Saturday Ember Day')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('trinity', 1, 'Sunday', 'white', 'Trinity Sunday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('trinity', 1, 'Monday', 'white', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('trinity', 1, 'Tuesday', 'white', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('trinity', 1, 'Wednesday', 'white', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('trinity', 1, 'Thursday', 'white', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('trinity', 1, 'Friday', 'white', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('trinity', 1, 'Saturday', 'white', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 1, 'Sunday', 'green', 'Sunday closest to May 11')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 1, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 1, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 1, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 1, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 1, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 1, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 2, 'Sunday', 'green', 'Sunday closest to May 18')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 2, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 2, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 2, 'Wednesday', 'green', 'Ash Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 2, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 2, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 2, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 3, 'Sunday', 'green', 'Sunday closest to May 25')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 3, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 3, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 3, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 3, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 3, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 3, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 4, 'Sunday', 'green', 'Sunday closest to June 1')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 4, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 4, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 4, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 4, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 4, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 4, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 5, 'Sunday', 'green', 'Sunday closest to June 8')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 5, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 5, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 5, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 5, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 5, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 5, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 6, 'Sunday', 'green', 'Sunday closest to June 15')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 6, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 6, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 6, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 6, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 6, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 6, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 7, 'Sunday', 'green', 'Sunday closest to June 22')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 7, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 7, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 7, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 7, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 7, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 7, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 8, 'Sunday', 'green', 'Sunday closest to June 29')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 8, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 8, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 8, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 8, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 8, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 8, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 9, 'Sunday', 'green', 'Sunday closest to July 6')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 9, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 9, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 9, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 9, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 9, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 9, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 10, 'Sunday', 'green', 'Sunday closest to July 13')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 10, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 10, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 10, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 10, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 10, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 10, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 11, 'Sunday', 'green', 'Sunday closest to July 20')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 11, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 11, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 11, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 11, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 11, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 11, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 12, 'Sunday', 'green', 'Sunday closest to July 27')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 12, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 12, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 12, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 12, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 12, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 12, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 13, 'Sunday', 'green', 'Sunday closest to August 3')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 13, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 13, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 13, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 13, 'Thursday', 'green', 'Thursd')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 13, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 13, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 14, 'Sunday', 'green', 'Sunday closest to August 10')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 14, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 14, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 14, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 14, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 14, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 14, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 15, 'Sunday', 'green', 'Sunday closest to August 17')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 15, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 15, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 15, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 15, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 15, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 15, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 16, 'Sunday', 'green', 'Sunday closest to August 24')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 16, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 16, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 16, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 16, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 16, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 16, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 17, 'Sunday', 'green', 'Sunday closest to August 31')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 17, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 17, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 17, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 17, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 17, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 17, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 18, 'Sunday', 'green', 'Sunday closest to September 7')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 18, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 18, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 18, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 18, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 18, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 18, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 19, 'Sunday', 'green', 'Sunday closest to September 14')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 19, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 19, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 19, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 19, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 19, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 19, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 20, 'Sunday', 'green', 'Sunday closest to September 21')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 20, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 20, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 20, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 20, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 20, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 20, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 21, 'Sunday', 'green', 'Sunday closest to September 28')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 21, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 21, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 21, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 21, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 21, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 21, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 22, 'Sunday', 'green', 'Sunday closest to October 5')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 22, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 22, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 22, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 22, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 22, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 22, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 23, 'Sunday', 'green', 'Sunday closest to October 12')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 23, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 23, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 23, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 23, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 23, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 23, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 24, 'Sunday', 'green', 'Sunday closest to October 19')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 24, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 24, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 24, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 24, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 24, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 24, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 25, 'Sunday', 'green', 'Sunday closest to October 26')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 25, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 25, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 25, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 25, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 25, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 25, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 26, 'Sunday', 'green', 'Sunday closest to November 2')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 26, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 26, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 26, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 26, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 26, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 26, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 27, 'Sunday', 'green', 'Sunday closest to November 9')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 27, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 27, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 27, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 27, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 27, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 27, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 28, 'Sunday', 'green', 'Sunday closest to November 16')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 28, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 28, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 28, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 28, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 28, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 28, 'Saturday', 'green', 'Saturday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 29, 'Sunday', 'green', 'Sunday closest to November 23')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 29, 'Monday', 'green', 'Monday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 29, 'Tuesday', 'green', 'Tuesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 29, 'Wednesday', 'green', 'Wednesday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 29, 'Thursday', 'green', 'Thursday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 29, 'Friday', 'green', 'Friday')");
db.execute("insert into daily_colors (season, week, day, colors, title) values ('proper', 29, 'Saturday', 'green', 'Saturday')");